// apps/web/src/vue/features/documents/OriginPanel.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref, watch } from "vue";
import {
  createOriginProject,
  createTaskFromDocument,
  documentTaskProjectsQuery,
  originErrorText,
  taskOriginsQuery,
} from "@/features/collections/origin-api";
import { originCreateSurface } from "@/features/collections/origin-create-surface";
import { itemPath } from "@/lib/href";

// Tasks this document started, or the documents a task came from
// (features/collections/origin-panel.tsx). Create-task lives on the document
// page only. Links to the other app are full page loads.
const props = defineProps<{
  workspaceId: string;
  slug: string;
  documentId?: string;
  taskId?: string;
  hideWhenEmpty?: boolean;
}>();
const queryClient = useQueryClient();
const after = ref<string | null>(null);
const projectId = ref("");
const title = ref("");
const requestId = ref(crypto.randomUUID());
const projectName = ref("");
const projectKey = ref("");

const origins = useQuery(() =>
  taskOriginsQuery(props.workspaceId, { documentId: props.documentId, taskId: props.taskId }, after.value),
);
const projects = useQuery(() => documentTaskProjectsQuery(props.workspaceId, props.documentId));
const hide = computed(
  () =>
    Boolean(props.hideWhenEmpty) &&
    !origins.isLoading.value &&
    !origins.isError.value &&
    origins.data.value?.count === 0,
);
const heading = computed(() =>
  props.documentId ? t("collection.linkedTasks") : t("collection.sourceDocument"),
);

watch(
  [() => projects.data.value, projectId],
  ([data]) => {
    if (!data) return;
    if (!data.items.some((item) => item.id === projectId.value)) projectId.value = data.suggestedId ?? "";
  },
  { immediate: true },
);

const createTask = useMutation({
  mutationFn: () =>
    createTaskFromDocument(props.workspaceId, props.documentId!, {
      projectId: projectId.value,
      requestId: requestId.value,
      title: title.value.trim(),
    }),
  onSuccess: async () => {
    after.value = null;
    title.value = "";
    requestId.value = crypto.randomUUID();
    await queryClient.invalidateQueries({ queryKey: ["task-origins", props.workspaceId, props.documentId] });
    await queryClient.invalidateQueries({ queryKey: ["tasks", props.workspaceId] });
  },
});

const createProject = useMutation({
  mutationFn: () => createOriginProject(props.workspaceId, projectKey.value, projectName.value),
  onSuccess: async (project) => {
    projectId.value = project.id;
    requestId.value = crypto.randomUUID();
    projectName.value = "";
    projectKey.value = "";
    await queryClient.invalidateQueries({ queryKey: ["task-projects", props.workspaceId, props.documentId] });
    await queryClient.invalidateQueries({ queryKey: ["projects", props.workspaceId] });
  },
});

const surface = computed(() =>
  originCreateSurface({
    isLoading: projects.isLoading.value,
    isError: projects.isError.value,
    itemCount: projects.data.value?.items.length,
    canCreateProject: projects.data.value?.canCreateProject,
  }),
);

function preventImeSubmit(event: KeyboardEvent): void {
  if (event.key === "Enter" && event.isComposing) event.preventDefault();
}

// A changed request is a new request: the id makes a retried submit idempotent.
function onProjectChange(event: Event): void {
  projectId.value = (event.target as HTMLSelectElement).value;
  requestId.value = crypto.randomUUID();
}

function onTitleInput(event: Event): void {
  title.value = (event.target as HTMLInputElement).value;
  requestId.value = crypto.randomUUID();
}

function submitTask(): void {
  if (projectId.value && title.value.trim()) createTask.mutate();
}

function submitProject(): void {
  if (projectName.value.trim() && projectKey.value.trim()) createProject.mutate();
}

const fieldClass = "h-10 rounded-md border border-default bg-default px-2";
</script>

<template>
  <section
    v-if="!hide"
    :aria-label="heading"
    class="flex flex-col gap-3 rounded-md border border-default p-4"
  >
    <h2 class="text-lg">{{ heading }} ({{ origins.data.value?.count ?? 0 }})</h2>
    <p v-if="origins.isLoading.value" role="status">{{ t("collection.origins.loading") }}</p>
    <p v-if="origins.isError.value" role="alert">{{ originErrorText(origins.error.value, t("collection.origins.error")) }}</p>
    <a
      v-for="item in origins.data.value?.items ?? []"
      :key="item.taskId"
      class="text-sm underline"
      :href="itemPath(slug, documentId ? item.taskDisplayId : item.documentDisplayId)"
    >
      {{
        documentId
          ? `${item.taskDisplayId} · ${item.taskTitle}`
          : `${item.documentDisplayId} · ${item.documentTitle}`
      }}
    </a>
    <p v-if="origins.data.value && origins.data.value.count === 0">{{ t("collection.noOrigins") }}</p>
    <UButton v-if="after" class="w-fit" variant="outline" color="neutral" @click="after = null">
      {{ t("collection.origins.first") }}
    </UButton>
    <UButton
      v-if="origins.data.value?.nextCursor"
      class="w-fit"
      variant="outline"
      color="neutral"
      @click="after = origins.data.value?.nextCursor ?? null"
    >
      {{ t("collection.origins.next") }}
    </UButton>
    <div v-if="documentId" class="flex flex-col gap-3">
      <p v-if="surface === 'loading'" role="status">{{ t("collection.taskCreation.projectsLoading") }}</p>
      <p v-if="surface === 'error'" role="alert">
        {{ originErrorText(projects.error.value, t("collection.taskCreation.projectsError")) }}
      </p>
      <form
        v-if="surface === 'create-task' && projects.data.value"
        class="flex flex-wrap items-end gap-2"
        @keydown="preventImeSubmit"
        @submit.prevent="submitTask"
      >
        <div class="flex flex-col gap-1">
          <label :for="`origin-project-${documentId}`" class="text-sm font-medium">{{ t("collection.taskProject") }}</label>
          <select
            :id="`origin-project-${documentId}`"
            :class="fieldClass"
            :value="projectId"
            @change="onProjectChange"
          >
            <option v-for="project in projects.data.value.items" :key="project.id" :value="project.id">
              {{ project.name }} ({{ project.key }})
            </option>
          </select>
        </div>
        <div class="flex flex-col gap-1">
          <label :for="`origin-title-${documentId}`" class="text-sm font-medium">{{ t("collection.taskTitle") }}</label>
          <input
            :id="`origin-title-${documentId}`"
            :class="fieldClass"
            :value="title"
            @input="onTitleInput"
          />
        </div>
        <UButton type="submit" :disabled="!projectId || !title.trim() || createTask.isPending.value">
          {{ t("collection.createTask") }}
        </UButton>
      </form>
      <form
        v-if="surface === 'create-project'"
        class="flex flex-wrap items-end gap-2"
        @keydown="preventImeSubmit"
        @submit.prevent="submitProject"
      >
        <p class="w-full">{{ t("collection.projectRequired") }}</p>
        <div class="flex flex-col gap-1">
          <label :for="`origin-project-name-${documentId}`" class="text-sm font-medium">{{ t("collection.projectName") }}</label>
          <input :id="`origin-project-name-${documentId}`" v-model="projectName" :class="fieldClass" />
        </div>
        <div class="flex flex-col gap-1">
          <label :for="`origin-project-key-${documentId}`" class="text-sm font-medium">{{ t("project.keyLabel") }}</label>
          <input :id="`origin-project-key-${documentId}`" v-model="projectKey" :class="fieldClass" />
        </div>
        <UButton type="submit" :disabled="!projectName.trim() || !projectKey.trim() || createProject.isPending.value">
          {{ t("project.new") }}
        </UButton>
      </form>
      <p v-if="surface === 'unavailable'">{{ t("collection.taskCreation.unavailable") }}</p>
      <p v-if="createTask.isError.value" role="alert">
        {{ originErrorText(createTask.error.value, t("collection.taskCreation.error")) }}
      </p>
      <p v-if="createProject.isError.value" role="alert">
        {{ originErrorText(createProject.error.value, t("collection.taskCreation.projectError")) }}
      </p>
    </div>
  </section>
</template>

// apps/web/src/features/collections/origin-panel.tsx
import { t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { itemPath } from "@/lib/href";
import {
  createOriginProject,
  createTaskFromDocument,
  documentTaskProjectsQuery,
  originErrorText as errorText,
  taskOriginsQuery,
} from "./origin-api";
import { originCreateSurface } from "./origin-create-surface";

type OriginPanelProps = {
  workspaceId: string;
  slug: string;
  documentId?: string;
  taskId?: string;
  hideWhenEmpty?: boolean;
};

function preventImeSubmit(event: React.KeyboardEvent<HTMLFormElement>) {
  if (event.key === "Enter" && event.nativeEvent.isComposing) {
    event.preventDefault();
  }
}

/** Current permission, rather than permission when the link was created, controls each page. */
export function OriginPanel({ workspaceId, slug, documentId, taskId, hideWhenEmpty }: OriginPanelProps) {
  const queryClient = useQueryClient();
  const [after, setAfter] = useState<string | null>(null);
  const [projectId, setProjectId] = useState("");
  const [title, setTitle] = useState("");
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [projectName, setProjectName] = useState("");
  const [projectKey, setProjectKey] = useState("");

  const origins = useQuery(taskOriginsQuery(workspaceId, { documentId, taskId }, after));
  const projects = useQuery(documentTaskProjectsQuery(workspaceId, documentId));
  useEffect(() => {
    if (!projects.data) return;
    if (!projects.data.items.some((item) => item.id === projectId)) {
      setProjectId(projects.data.suggestedId ?? "");
    }
  }, [projects.data, projectId]);

  const createTask = useMutation({
    mutationFn: () => createTaskFromDocument(workspaceId, documentId!, { projectId, requestId, title: title.trim() }),
    onSuccess: async () => {
      setAfter(null);
      setTitle("");
      setRequestId(crypto.randomUUID());
      await queryClient.invalidateQueries({ queryKey: ["task-origins", workspaceId, documentId] });
      await queryClient.invalidateQueries({ queryKey: ["tasks", workspaceId] });
    },
  });
  const createProject = useMutation({
    mutationFn: () => createOriginProject(workspaceId, projectKey, projectName),
    onSuccess: async (project) => {
      setProjectId(project.id);
      setRequestId(crypto.randomUUID());
      setProjectName("");
      setProjectKey("");
      await queryClient.invalidateQueries({ queryKey: ["task-projects", workspaceId, documentId] });
      await queryClient.invalidateQueries({ queryKey: ["projects", workspaceId] });
    },
  });

  const createSurface = originCreateSurface({
    isLoading: projects.isLoading,
    isError: projects.isError,
    itemCount: projects.data?.items.length,
    canCreateProject: projects.data?.canCreateProject,
  });

  if (hideWhenEmpty && !origins.isLoading && !origins.isError && origins.data?.count === 0) return null;
  return (
    <section aria-label={documentId ? t("collection.linkedTasks") : t("collection.sourceDocument")} className="flex flex-col gap-3 rounded-md border border-border p-4">
      <h2 className="text-title">{documentId ? t("collection.linkedTasks") : t("collection.sourceDocument")} ({origins.data?.count ?? 0})</h2>
      {origins.isLoading ? <p role="status">{t("collection.origins.loading")}</p> : null}
      {origins.isError ? <p role="alert">{errorText(origins.error, t("collection.origins.error"))}</p> : null}
      {origins.data?.items.map((item) => (
        <Link key={item.taskId} className="text-ui underline" to={itemPath(slug, documentId ? item.taskDisplayId : item.documentDisplayId)}>
          {documentId ? `${item.taskDisplayId} · ${item.taskTitle}` : `${item.documentDisplayId} · ${item.documentTitle}`}
        </Link>
      ))}
      {origins.data && origins.data.count === 0 ? <p>{t("collection.noOrigins")}</p> : null}
      {after ? <Button type="button" variant="outline" onClick={() => setAfter(null)}>{t("collection.origins.first")}</Button> : null}
      {origins.data?.nextCursor ? <Button type="button" variant="outline" onClick={() => setAfter(origins.data!.nextCursor ?? null)}>{t("collection.origins.next")}</Button> : null}
      {documentId ? (
        <div className="flex flex-col gap-3">
          {createSurface === "loading" ? <p role="status">{t("collection.taskCreation.projectsLoading")}</p> : null}
          {createSurface === "error" ? <p role="alert">{errorText(projects.error, t("collection.taskCreation.projectsError"))}</p> : null}
          {createSurface === "create-task" && projects.data ? (
            <form className="flex flex-wrap items-end gap-2" onKeyDown={preventImeSubmit} onSubmit={(event) => { event.preventDefault(); if (projectId && title.trim()) createTask.mutate(); }}>
              <div><Label htmlFor={`origin-project-${documentId}`}>{t("collection.taskProject")}</Label>
                <select id={`origin-project-${documentId}`} className="h-10 rounded-md border border-input bg-background px-2" value={projectId} onChange={(event) => { setProjectId(event.target.value); setRequestId(crypto.randomUUID()); }}>
                  {projects.data.items.map((project) => <option key={project.id} value={project.id}>{project.name} ({project.key})</option>)}
                </select>
              </div>
              <div><Label htmlFor={`origin-title-${documentId}`}>{t("collection.taskTitle")}</Label><Input id={`origin-title-${documentId}`} value={title} onChange={(event) => { setTitle(event.target.value); setRequestId(crypto.randomUUID()); }} /></div>
              <Button type="submit" disabled={!projectId || !title.trim() || createTask.isPending}>{t("collection.createTask")}</Button>
            </form>
          ) : null}
          {createSurface === "create-project" ? (
            <form className="flex flex-wrap items-end gap-2" onKeyDown={preventImeSubmit} onSubmit={(event) => { event.preventDefault(); if (projectName.trim() && projectKey.trim()) createProject.mutate(); }}>
              <p className="w-full">{t("collection.projectRequired")}</p>
              <div><Label htmlFor={`origin-project-name-${documentId}`}>{t("collection.projectName")}</Label><Input id={`origin-project-name-${documentId}`} value={projectName} onChange={(event) => setProjectName(event.target.value)} /></div>
              <div><Label htmlFor={`origin-project-key-${documentId}`}>{t("project.keyLabel")}</Label><Input id={`origin-project-key-${documentId}`} value={projectKey} onChange={(event) => setProjectKey(event.target.value)} /></div>
              <Button type="submit" disabled={!projectName.trim() || !projectKey.trim() || createProject.isPending}>{t("project.new")}</Button>
            </form>
          ) : null}
          {createSurface === "unavailable" ? <p>{t("collection.taskCreation.unavailable")}</p> : null}
          {createTask.isError ? <p role="alert">{errorText(createTask.error, t("collection.taskCreation.error"))}</p> : null}
          {createProject.isError ? <p role="alert">{errorText(createProject.error, t("collection.taskCreation.projectError"))}</p> : null}
        </div>
      ) : null}
    </section>
  );
}
