// apps/web/src/vue/features/settings/ConfirmDialog.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useId } from "vue";
import NativeModal from "../../components/NativeModal.vue";
import "@/features/projects/projects.css";

withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    body: string;
    actionLabel: string;
    pending?: boolean;
    error?: string | null;
  }>(),
  { pending: false, error: null },
);

const emit = defineEmits<{ close: []; confirm: [] }>();
const titleId = useId();
const bodyId = useId();
</script>

<template>
  <NativeModal :open="open" :labelled-by="titleId" @close="emit('close')">
    <div class="max-w-md rounded-md border border-default bg-default p-4">
      <h2 :id="titleId" class="text-lg font-medium">{{ title }}</h2>
      <p :id="bodyId" class="mt-2 break-all text-sm text-muted">{{ body }}</p>
      <p v-if="error" role="alert" class="settings-notice settings-notice--danger mt-2">{{ error }}</p>
      <div class="mt-4 flex justify-end gap-2">
        <UButton type="button" size="sm" variant="outline" color="neutral" @click="emit('close')">
          {{ t("common.dismiss") }}
        </UButton>
        <UButton type="button" size="sm" :disabled="pending" @click="emit('confirm')">{{ actionLabel }}</UButton>
      </div>
    </div>
  </NativeModal>
</template>

// apps/web/src/features/settings/confirm-dialog.tsx
import { t } from "@fvoci/i18n";
import { useEffect, useId, useRef } from "react";
import { Button } from "@/components/ui/button";

/** Same alertdialog shape as the token revoke confirm: focus lands on the action, Escape cancels. */
export function ConfirmDialog({
  title,
  body,
  actionLabel,
  pending,
  error,
  onCancel,
  onConfirm,
}: {
  title: string;
  body: string;
  actionLabel: string;
  pending: boolean;
  error: string | null;
  onCancel: () => void;
  onConfirm: () => void;
}) {
  const titleId = useId();
  const bodyId = useId();
  const confirmRef = useRef<HTMLButtonElement>(null);
  const openerRef = useRef<Element | null>(null);

  useEffect(() => {
    openerRef.current = document.activeElement;
    confirmRef.current?.focus();
    return () => {
      if (openerRef.current instanceof HTMLElement && openerRef.current.isConnected) {
        openerRef.current.focus();
      }
    };
  }, []);

  return (
    <div
      role="alertdialog"
      aria-modal="true"
      aria-labelledby={titleId}
      aria-describedby={bodyId}
      className="fixed inset-0 z-20 flex items-center justify-center bg-black/40 p-4"
      onKeyDown={(event) => {
        if (event.key === "Escape") {
          event.preventDefault();
          onCancel();
        }
      }}
    >
      <div className="max-w-md rounded-md border border-border bg-background p-4">
        <h2 id={titleId} className="text-title">
          {title}
        </h2>
        <p id={bodyId} className="mt-2 text-ui break-all text-muted-foreground">
          {body}
        </p>
        {error ? (
          <p role="alert" className="settings-notice settings-notice--danger mt-2">
            {error}
          </p>
        ) : null}
        <div className="mt-4 flex justify-end gap-2">
          <Button type="button" variant="outline" size="sm" onClick={onCancel}>
            {t("common.dismiss")}
          </Button>
          <Button ref={confirmRef} type="button" size="sm" disabled={pending} onClick={onConfirm}>
            {actionLabel}
          </Button>
        </div>
      </div>
    </div>
  );
}
