// apps/web/src/vue/features/settings/ConfirmAction.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { ref, useId } from "vue";
import NativeModal from "../../components/NativeModal.vue";
import "@/features/projects/projects.css";

const props = withDefaults(
  defineProps<{
    title: string;
    description: string;
    actionLabel: string;
    disabled?: boolean;
    run: () => Promise<void> | void;
  }>(),
  { disabled: false },
);

const open = ref(false);
const busy = ref(false);
const titleId = useId();

function close(): void {
  open.value = false;
}

async function confirm(): Promise<void> {
  busy.value = true;
  try {
    await props.run();
  } finally {
    busy.value = false;
    close();
  }
}
</script>

<template>
  <UButton type="button" size="sm" variant="outline" color="neutral" :disabled="disabled" @click="open = true">
    <slot />
  </UButton>
  <NativeModal :open="open" :labelled-by="titleId" @close="close">
    <div class="max-w-md rounded-md border border-default bg-default p-4">
      <h2 :id="titleId" class="text-lg font-medium">{{ title }}</h2>
      <p class="mt-2 break-keep text-sm text-muted">{{ description }}</p>
      <div class="mt-4 flex justify-end gap-2">
        <UButton type="button" size="sm" variant="outline" color="neutral" @click="close">{{
          t("common.cancel")
        }}</UButton>
        <UButton type="button" size="sm" color="error" :disabled="busy" @click="confirm">{{ actionLabel }}</UButton>
      </div>
    </div>
  </NativeModal>
</template>

// apps/web/src/components/confirm-action.tsx
// Adapted from source apps/web/src/components/confirm-action.tsx using this
// app's alertdialog pattern (see features/settings/workspace-tokens.tsx).
import { t } from "@fvoci/i18n";
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";

export function ConfirmActionButton({
  title,
  description,
  actionLabel,
  disabled,
  destructive = true,
  triggerVariant = "outline",
  onConfirm,
  children,
}: {
  title: string;
  description: string;
  actionLabel: string;
  disabled?: boolean;
  destructive?: boolean;
  triggerVariant?: "default" | "outline" | "destructive";
  onConfirm: () => Promise<void> | void;
  children: ReactNode;
}) {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const titleId = useId();
  const confirmRef = useRef<HTMLButtonElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (open) confirmRef.current?.focus();
  }, [open]);

  function close() {
    setOpen(false);
    triggerRef.current?.focus();
  }

  return (
    <>
      <Button
        ref={triggerRef}
        type="button"
        variant={triggerVariant}
        size="sm"
        disabled={disabled}
        onClick={() => setOpen(true)}
      >
        {children}
      </Button>
      {open ? (
        <div
          role="alertdialog"
          aria-modal="true"
          aria-labelledby={titleId}
          className="fixed inset-0 z-20 flex items-center justify-center bg-black/40 p-4"
          onKeyDown={(event) => {
            if (event.key === "Escape") {
              event.preventDefault();
              close();
            }
          }}
        >
          <div className="max-w-md rounded-md border border-border bg-background p-4">
            <h2 id={titleId} className="text-title">
              {title}
            </h2>
            <p className="mt-2 break-keep text-ui text-muted-foreground">{description}</p>
            <div className="mt-4 flex justify-end gap-2">
              <Button type="button" variant="outline" size="sm" onClick={close}>
                {t("common.cancel")}
              </Button>
              <Button
                ref={confirmRef}
                type="button"
                size="sm"
                variant={destructive ? "destructive" : "default"}
                disabled={busy}
                onClick={() => {
                  setBusy(true);
                  void Promise.resolve(onConfirm()).finally(() => {
                    setBusy(false);
                    close();
                  });
                }}
              >
                {actionLabel}
              </Button>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}
