// apps/web/src/pages/AdminAuditPage.tsx
// Adapted from source apps/web/src/routes/settings.audit.tsx.
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import { AdminShell } from "@/features/settings/admin-shell";
import { AuditSettingsView } from "@/features/settings/settings-audit";
import { ProblemError } from "@/lib/api";
import { FALLBACK_TZ } from "@/lib/datetime";
import { meQuery } from "@/lib/queries";
import { adminAuditQuery } from "@/lib/queries/admin";

function AuditLog() {
  const me = useQuery(meQuery);
  const audit = useQuery(adminAuditQuery);
  // A 404 here is the enterprise gate (the source hides audit without a license).
  const eeRequired = audit.error instanceof ProblemError && audit.error.status === 404;
  const failure = !eeRequired && audit.error
    ? audit.error instanceof ProblemError
      ? audit.error.title
      : t("error.network")
    : null;
  return (
    <AuditSettingsView
      items={audit.data?.items ?? []}
      timeZone={me.data?.timezone ?? FALLBACK_TZ}
      loading={audit.isLoading}
      eeRequired={eeRequired}
      error={failure}
    />
  );
}

export function AdminAuditPage() {
  return (
    <AdminShell active="audit">
      <AuditLog />
    </AdminShell>
  );
}

// apps/web/src/vue/pages/AdminAuditPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { ProblemError } from "@/lib/api";
import { FALLBACK_TZ } from "@/lib/datetime";
import { meQuery } from "@/lib/queries";
import { adminAuditQuery } from "@/lib/queries/admin";
import AdminShell from "../components/AdminShell.vue";
import AuditSettingsView from "../features/settings/AuditSettingsView.vue";

const me = useQuery(meQuery);
const audit = useQuery(adminAuditQuery);
const eeRequired = computed(() => audit.error.value instanceof ProblemError && audit.error.value.status === 404);
const failure = computed(() => {
  if (eeRequired.value || !audit.error.value) return null;
  return audit.error.value instanceof ProblemError ? audit.error.value.title : t("error.network");
});
</script>

<template>
  <AdminShell active="audit">
    <AuditSettingsView
      :items="audit.data.value?.items ?? []"
      :time-zone="me.data.value?.timezone ?? FALLBACK_TZ"
      :loading="audit.isLoading.value"
      :ee-required="eeRequired"
      :error="failure"
    />
  </AdminShell>
</template>
