// apps/web/src/pages/HomePage.tsx
import { t } from "@fvoci/i18n";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { AuthenticatedLegalNav } from "@/features/legal/operator-info";
import { logout as logoutRequest } from "@/features/notifications/push-logout";
import { EmptyWorkspace } from "@/features/workspace/empty-workspace";
import { WorkspaceCreateDialog } from "@/features/workspace/workspace-create-dialog";
import { api, ensureOk, ProblemError, problemMessage } from "@/lib/api";
import { wikiPath } from "@/lib/href";
import { meQuery, workspacesQuery } from "@/lib/queries";
import { useState } from "react";

function DeniedBanner() {
  const [params, setParams] = useSearchParams();
  if (params.get("denied") !== "workspace") return null;
  return (
    <div role="alert" className="border-b border-border bg-muted px-4 py-2 text-ui text-muted-foreground">
      <span className="break-keep">{t("error.denied")}</span>
      <button
        type="button"
        className="ml-3 underline underline-offset-2"
        onClick={() => {
          params.delete("denied");
          setParams(params, { replace: true });
        }}
      >
        {t("common.dismiss")}
      </button>
    </div>
  );
}

export function HomePage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [createOpen, setCreateOpen] = useState(false);
  const [logoutError, setLogoutError] = useState<string | null>(null);
  const me = useQuery(meQuery);
  const workspaces = useQuery(workspacesQuery);

  if (me.isError) {
    return <Navigate to="/login" replace />;
  }

  async function logout() {
    setLogoutError(null);
    let result;
    try {
      result = await logoutRequest();
    } catch {
      setLogoutError(t("error.network"));
      return;
    }
    if (!result.response.ok) {
      setLogoutError(
        problemMessage(new ProblemError(result.response.status), "error.auth.logout"),
      );
      return;
    }
    await queryClient.resetQueries();
    await navigate("/login", { replace: true });
  }

  if (workspaces.isLoading || me.isLoading) {
    return <p className="p-8 text-muted-foreground">{t("load.loading")}</p>;
  }

  const items = workspaces.data?.items ?? [];

  if (items.length === 0) {
    return (
      <div className="app-shell">
        <DeniedBanner />
        <main className="app-shell__main">
          {me.data?.isInstanceAdmin ? (
            <Link to="/settings/admin" className="text-ui underline underline-offset-2">
              {t("admin.console")}
            </Link>
          ) : null}
          <EmptyWorkspace
            isAdmin={me.data?.isInstanceAdmin === true}
            onCreate={async (input) => {
              await ensureOk(await api.POST("/api/v1/workspaces", { body: input }));
              await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
            }}
            onLogout={() => {
              void logout();
            }}
            error={logoutError ?? (workspaces.isError ? t("load.listFailed") : null)}
            onRetry={() => {
              void workspaces.refetch();
            }}
          />
        </main>
        <footer className="border-t border-border px-4 py-3">
          <AuthenticatedLegalNav />
        </footer>
      </div>
    );
  }

  return (
    <div className="app-shell">
      <DeniedBanner />
      {logoutError ? (
        <div role="alert" className="border-b border-border bg-muted px-4 py-2 text-ui text-muted-foreground">
          {logoutError}
        </div>
      ) : null}
      <header className="app-shell__header">
        <h1 className="text-title font-semibold">{t("dashboard.title")}</h1>
        <div className="flex gap-2">
          {me.data?.isInstanceAdmin ? (
            <Link
              to="/settings/admin"
              className="inline-flex h-8 items-center rounded-md border border-border px-3 text-sm font-medium hover:bg-accent"
            >
              {t("admin.console")}
            </Link>
          ) : null}
          {me.data?.isInstanceAdmin ? (
            <Button type="button" size="sm" onClick={() => setCreateOpen(true)}>
              {t("workspace.create")}
            </Button>
          ) : null}
          <Link to="/settings/account" className="self-center text-ui underline underline-offset-2">
            {t("settings.account")}
          </Link>
          <Button type="button" size="sm" variant="outline" onClick={() => void logout()}>
            {t("nav.logout")}
          </Button>
        </div>
      </header>
      <main className="app-shell__main">
        <div className="workspace-list">
          {items.map((workspace) => (
            <Link
              key={workspace.id}
              className="workspace-list__item"
              to={wikiPath(workspace.slug)}
            >
              <div>
                <strong>{workspace.name}</strong>
                <p className="text-dense text-muted-foreground">{workspace.slug}</p>
                <p className="text-dense text-muted-foreground">
                  {t("dashboard.workspace.documentCount", { count: workspace.documentCount })}
                  {" · "}
                  {t("dashboard.workspace.assignedCount", { count: workspace.assignedCount })}
                </p>
              </div>
              <span className="text-caption text-muted-foreground">{workspace.role}</span>
            </Link>
          ))}
        </div>
      </main>
      <footer className="border-t border-border px-4 py-3">
        <AuthenticatedLegalNav />
      </footer>
      <WorkspaceCreateDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        onCreate={async (input) => {
          await ensureOk(await api.POST("/api/v1/workspaces", { body: input }));
          await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
        }}
      />
    </div>
  );
}

// apps/web/src/vue/pages/HomePage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref, watchEffect } from "vue";
import { useRoute, useRouter } from "vue-router";
import { logout as logoutRequest } from "@/features/notifications/push-logout";
import { api, ensureOk, ProblemError, problemMessage } from "@/lib/api";
import { wikiPath } from "@/lib/href";
import { meQuery, workspacesQuery } from "@/lib/queries";
import AuthenticatedLegalNav from "../features/legal/AuthenticatedLegalNav.vue";
import EmptyWorkspace from "../features/workspace/EmptyWorkspace.vue";
import WorkspaceCreateDialog from "../features/workspace/WorkspaceCreateDialog.vue";
import { loginPath, redirectTo } from "../session/navigation";
import "@/features/workspace/workspace-aux.css";
import "../features/workspace/workspace-home.css";

// / is not a live Vue path (src/app-boundary.ts). The page is a lazy chunk;
// until the boundary moves, boot still loads the React HomePage.

const route = useRoute();
const router = useRouter();
const queryClient = useQueryClient();
const createOpen = ref(false);
const logoutError = ref<string | null>(null);
const me = useQuery(meQuery);
const workspaces = useQuery(workspacesQuery);

const denied = computed(() => route.query.denied === "workspace");
const items = computed(() => workspaces.data.value?.items ?? []);
const leaving = computed(() => me.isError.value);

watchEffect(() => {
  if (me.isError.value) redirectTo(loginPath(window.location));
});

function dismissDenied(): void {
  const query = { ...route.query };
  delete query.denied;
  void router.replace({ query });
}

async function logout(): Promise<void> {
  logoutError.value = null;
  let result;
  try {
    result = await logoutRequest();
  } catch {
    logoutError.value = t("error.network");
    return;
  }
  if (!result.response.ok) {
    logoutError.value = problemMessage(new ProblemError(result.response.status), "error.auth.logout");
    return;
  }
  await queryClient.resetQueries();
  redirectTo("/login");
}

async function createWorkspace(input: { name: string; slug: string }): Promise<void> {
  await ensureOk(await api.POST("/api/v1/workspaces", { body: input }));
  await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
}
</script>

<template>
  <p v-if="workspaces.isLoading.value || me.isLoading.value || leaving" class="p-8 text-muted">
    {{ t("load.loading") }}
  </p>
  <div v-else class="app-shell">
    <div
      v-if="denied"
      role="alert"
      class="border-b border-default bg-elevated px-4 py-2 text-sm text-muted"
    >
      <span class="break-keep">{{ t("error.denied") }}</span>
      <button type="button" class="ml-3 underline underline-offset-2" @click="dismissDenied">
        {{ t("common.dismiss") }}
      </button>
    </div>
    <div
      v-if="items.length > 0 && logoutError"
      role="alert"
      class="border-b border-default bg-elevated px-4 py-2 text-sm text-muted"
    >
      {{ logoutError }}
    </div>
    <template v-if="items.length === 0">
      <main class="app-shell__main">
        <a
          v-if="me.data.value?.isInstanceAdmin"
          href="/settings/admin"
          class="text-sm underline underline-offset-2"
        >
          {{ t("admin.console") }}
        </a>
        <EmptyWorkspace
          :is-admin="me.data.value?.isInstanceAdmin === true"
          :on-create="createWorkspace"
          :on-logout="() => void logout()"
          :error="logoutError ?? (workspaces.isError.value ? t('load.listFailed') : null)"
          :on-retry="() => void workspaces.refetch()"
        />
      </main>
    </template>
    <template v-else>
      <header class="app-shell__header">
        <h1 class="text-lg font-semibold">{{ t("dashboard.title") }}</h1>
        <div class="flex gap-2">
          <a
            v-if="me.data.value?.isInstanceAdmin"
            href="/settings/admin"
            class="inline-flex h-8 items-center rounded-md border border-default px-3 text-sm font-medium hover:bg-elevated"
          >
            {{ t("admin.console") }}
          </a>
          <UButton
            v-if="me.data.value?.isInstanceAdmin"
            type="button"
            size="sm"
            @click="createOpen = true"
          >
            {{ t("workspace.create") }}
          </UButton>
          <a href="/settings/account" class="self-center text-sm underline underline-offset-2">
            {{ t("settings.account") }}
          </a>
          <UButton type="button" size="sm" variant="outline" color="neutral" @click="() => void logout()">
            {{ t("nav.logout") }}
          </UButton>
        </div>
      </header>
      <main class="app-shell__main">
        <div class="workspace-list">
          <a
            v-for="workspace in items"
            :key="workspace.id"
            class="workspace-list__item"
            :href="wikiPath(workspace.slug)"
          >
            <div>
              <strong>{{ workspace.name }}</strong>
              <p class="text-xs text-muted">{{ workspace.slug }}</p>
              <p class="text-xs text-muted">
                {{ t("dashboard.workspace.documentCount", { count: workspace.documentCount }) }}
                ·
                {{ t("dashboard.workspace.assignedCount", { count: workspace.assignedCount }) }}
              </p>
            </div>
            <span class="text-xs text-muted">{{ workspace.role }}</span>
          </a>
        </div>
      </main>
      <WorkspaceCreateDialog :open="createOpen" :on-create="createWorkspace" @close="createOpen = false" />
    </template>
    <footer class="border-t border-default px-4 py-3">
      <AuthenticatedLegalNav />
    </footer>
  </div>
</template>
