// apps/web/src/pages/LegalPage.tsx
// Adapted from source apps/web/src/routes/legal.$kind.tsx and features/legal/legal.tsx.
import { asSafeHtml, SafeHtmlView } from "@fvoci/editor/safe-html";
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import { useParams, useSearchParams } from "react-router-dom";
import { loadErrorMessage, QueryError, QueryLoading } from "@/components/query-status";
import { AuthAlert } from "@/features/auth/auth-form";
import { AuthLayout, AuthPanel } from "@/features/auth/auth-layout";
import { ProblemError } from "@/lib/api";
import { formatDateKo } from "@/lib/datetime";
import { legalDocQuery, legalVersionsQuery, selectLegalVersions } from "@/lib/queries/admin";

export function LegalPage() {
  const { kind = "" } = useParams<{ kind: string }>();
  const [params] = useSearchParams();
  const raw = params.get("version");
  const version = raw && /^\d+$/.test(raw) ? Number(raw) : undefined;
  const doc = useQuery(legalDocQuery(kind, version));
  const versions = useQuery({ ...legalVersionsQuery(kind), select: selectLegalVersions });

  if (doc.error instanceof ProblemError && doc.error.status === 404) {
    return (
      <AuthLayout>
        <AuthPanel title={kind}>
          <AuthAlert>{t("legal.empty")}</AuthAlert>
        </AuthPanel>
      </AuthLayout>
    );
  }
  if (doc.data === undefined) {
    return (
      <AuthLayout>
        {doc.isError ? (
          <QueryError message={loadErrorMessage(doc.error)} onRetry={() => void doc.refetch()} />
        ) : (
          <QueryLoading />
        )}
      </AuthLayout>
    );
  }

  const current = doc.data;
  const others = (versions.data ?? []).filter((v) => v.version !== current.version);

  return (
    <AuthLayout>
      <AuthPanel
        title={current.title}
        lead={t("legal.meta", { version: current.version, date: formatDateKo(current.effectiveAt) })}
      >
        <SafeHtmlView className="break-keep text-ui text-foreground" html={asSafeHtml(current.bodyHtml)} />
        {others.length > 0 ? (
          <div className="auth-shell__stack border-t border-border pt-5">
            <p className="text-ui font-medium text-foreground">{t("legal.previous")}</p>
            {others.map((v) => (
              <a key={v.version} href={`/legal/${kind}?version=${v.version}`} className="auth-shell__link break-keep">
                v{v.version}({formatDateKo(v.effectiveAt)})
              </a>
            ))}
          </div>
        ) : null}
      </AuthPanel>
    </AuthLayout>
  );
}

// apps/web/src/vue/pages/LegalPage.vue
<script setup lang="ts">
import { asSafeHtml, SafeHtml } from "@fvoci/editor/vue/safe-html";
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { useRoute } from "vue-router";
import { loadErrorMessage, ProblemError } from "@/lib/api";
import { formatDateKo } from "@/lib/datetime";
import { legalDocQuery, legalVersionsQuery, selectLegalVersions } from "@/lib/queries/legal";
import QueryError from "../components/QueryError.vue";
import QueryLoading from "../components/QueryLoading.vue";
import AuthAlert from "../features/auth/AuthAlert.vue";
import AuthLayout from "../features/auth/AuthLayout.vue";
import AuthPanel from "../features/auth/AuthPanel.vue";

const route = useRoute();
const kind = computed(() => (typeof route.params.kind === "string" ? route.params.kind : ""));
const version = computed(() => {
  const raw = typeof route.query.version === "string" ? route.query.version : null;
  return raw && /^\d+$/.test(raw) ? Number(raw) : undefined;
});
const doc = useQuery(() => legalDocQuery(kind.value, version.value));
const versions = useQuery(() => ({
  ...legalVersionsQuery(kind.value),
  select: selectLegalVersions,
}));

const missing = computed(() => doc.error.value instanceof ProblemError && doc.error.value.status === 404);
const others = computed(() =>
  (versions.data.value ?? []).filter((entry) => entry.version !== doc.data.value?.version),
);
</script>

<template>
  <AuthLayout v-if="missing">
    <AuthPanel :title="kind">
      <AuthAlert :message="t('legal.empty')" />
    </AuthPanel>
  </AuthLayout>
  <AuthLayout v-else-if="doc.data.value === undefined">
    <QueryError
      v-if="doc.isError.value"
      :message="loadErrorMessage(doc.error.value)"
      @retry="() => void doc.refetch()"
    />
    <QueryLoading v-else />
  </AuthLayout>
  <AuthLayout v-else-if="doc.data.value">
    <AuthPanel
      :title="doc.data.value.title"
      :lead="t('legal.meta', { version: doc.data.value.version, date: formatDateKo(doc.data.value.effectiveAt) })"
    >
      <SafeHtml class="auth-shell__doc-body break-keep" :html="asSafeHtml(doc.data.value.bodyHtml)" />
      <div v-if="others.length > 0" class="auth-shell__stack border-t border-default pt-5">
        <p class="auth-shell__text auth-shell__text--strong">{{ t("legal.previous") }}</p>
        <a
          v-for="entry in others"
          :key="entry.version"
          :href="`/legal/${kind}?version=${entry.version}`"
          class="auth-shell__link break-keep"
        >
          v{{ entry.version }}({{ formatDateKo(entry.effectiveAt) }})
        </a>
      </div>
    </AuthPanel>
  </AuthLayout>
</template>
