// apps/web/src/pages/MagicLinkPage.tsx
import { useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { MagicLinkView } from "@/features/auth/magic-link";
import { MfaStep } from "@/features/auth/mfa";
import { api, ensureOk } from "@/lib/api";

export function MagicLinkPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const token = searchParams.get("token");
  const [mfaToken, setMfaToken] = useState<string | null>(null);

  async function enterApp(): Promise<void> {
    await queryClient.invalidateQueries();
    await navigate("/", { replace: true });
  }

  if (mfaToken !== null) {
    return (
      <MfaStep
        mfaToken={mfaToken}
        onBack={() => {
          void navigate("/login");
        }}
        onVerified={enterApp}
      />
    );
  }

  return (
    <MagicLinkView
      token={token}
      onConsume={async (value) => {
        const result = await ensureOk(
          await api.POST("/api/v1/auth/magic-link/consume", {
            body: { token: value },
          }),
        );
        if (result.mfaToken) {
          setMfaToken(result.mfaToken);
          return;
        }
        await enterApp();
      }}
    />
  );
}

// apps/web/src/vue/pages/MagicLinkPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery } from "@tanstack/vue-query";
import { computed, ref, watchEffect } from "vue";
import { useRoute } from "vue-router";
import { api, ensureOk } from "@/lib/api";
import { setupStatusQuery } from "@/lib/queries";
import { redirectTo } from "../session/navigation";
import MagicLinkView from "../features/auth/MagicLinkView.vue";
import MfaStep from "../features/auth/MfaStep.vue";

const route = useRoute();
const setup = useQuery(setupStatusQuery);
const token = computed(() => {
  const value = route.query.token;
  return typeof value === "string" && value.length > 0 ? value : null;
});
const mfaToken = ref<string | null>(null);
const leaving = computed(() => setup.data.value?.needed === true);

watchEffect(() => {
  if (setup.isLoading.value || setup.isError.value) return;
  if (setup.data.value?.needed) {
    redirectTo("/setup");
  }
});

async function enterApp(): Promise<void> {
  // A full load clears anonymous queries after sign-in.
  window.location.replace("/");
}

function leaveToLogin(): void {
  window.location.assign("/login");
}

async function onConsume(value: string): Promise<void> {
  const result = await ensureOk(
    await api.POST("/api/v1/auth/magic-link/consume", {
      body: { token: value },
    }),
  );
  if (result.mfaToken) {
    mfaToken.value = result.mfaToken;
    return;
  }
  await enterApp();
}
</script>

<template>
  <p v-if="setup.isLoading.value || leaving" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="setup.isError.value" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="setup.refetch()">{{ t("load.retry") }}</UButton>
  </div>
  <MfaStep
    v-else-if="mfaToken !== null"
    :mfa-token="mfaToken"
    @back="leaveToLogin"
    @verified="enterApp"
  />
  <MagicLinkView v-else :token="token" :consume-token="onConsume" />
</template>
