// apps/web/src/pages/MyTasksPage.tsx
// Source routes/w.$slug.my-tasks.tsx + features/tasks/my-tasks-view.tsx: open
// tasks assigned to the viewer across every project they can view.
import { t } from "@fvoci/i18n";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { EmptyState } from "@/components/empty-state";
import { QueryError, QueryLoading, loadErrorMessage } from "@/components/query-status";
import { projectsQuery } from "@/features/projects/queries";
import { mergeTaskListPages } from "@/features/tasks/task-list-page";
import { TaskListLoadMore } from "@/features/tasks/task-list-load-more";
import { groupTasksByProject, myTasksQuery, workspaceStatusesQuery } from "@/features/tasks/my-tasks";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { ProblemError } from "@/lib/api";
import { FALLBACK_TZ, formatDateKo } from "@/lib/datetime";
import { formatDisplayId, itemPath } from "@/lib/href";
import { meQuery } from "@/lib/queries";
import "@/features/projects/projects.css";

export function MyTasksPage() {
  const { slug, workspace } = useWorkspaceContext();
  const workspaceId = workspace?.id ?? "";
  const tasks = useInfiniteQuery(myTasksQuery(workspaceId));
  const statuses = useQuery(workspaceStatusesQuery(workspaceId));
  const projects = useQuery(projectsQuery(workspaceId));
  const me = useQuery(meQuery);

  if (!workspace) return null;

  const merged = mergeTaskListPages(tasks.data?.pages ?? []);
  const items = merged?.items ?? [];
  const projectById = new Map((projects.data?.items ?? []).map((p) => [p.id, p]));
  const statusById = new Map((statuses.data?.items ?? []).map((s) => [s.id, s]));
  const timeZone = me.data?.timezone ?? FALLBACK_TZ;
  /* A rejected later page after the list changed: restart from the top like the source. */
  const cursorStale =
    tasks.error instanceof ProblemError && tasks.error.status === 400 && items.length > 0;

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="myTasks"
    >
      <div className="task-home" data-testid="my-tasks">
        <div className="task-home__head">
          <h1 className="task-home__title">{t("task.mine")}</h1>
        </div>
        {tasks.isLoading ? <QueryLoading /> : null}
        {tasks.isError && items.length === 0 ? (
          <QueryError
            message={loadErrorMessage(tasks.error)}
            onRetry={() => {
              void tasks.refetch();
            }}
          />
        ) : null}
        {tasks.isSuccess && items.length === 0 ? <EmptyState title={t("task.assigned.empty")} /> : null}
        <div className="flex flex-col gap-8">
          {groupTasksByProject(items).map(([projectId, projectItems]) => {
            const project = projectById.get(projectId);
            return (
              <section key={projectId} className="flex flex-col gap-1">
                <h2 className="border-b border-border pb-2 text-ui font-medium">
                  <span className="tabular-nums text-muted-foreground">{project?.key ?? "—"}</span>
                  {project?.name ? <span className="ml-2 break-keep">{project.name}</span> : null}
                </h2>
                <ul className="task-status-list">
                  {projectItems.map((item) => {
                    const displayId = project ? formatDisplayId(project.key, item.number) : null;
                    const status = statusById.get(item.statusId);
                    const due = item.dueDate ?? item.dueAt;
                    const row = (
                      <>
                        <span className="task-row__id">{displayId ?? item.id.slice(0, 8)}</span>
                        <span className="task-row__title">{item.title}</span>
                        {status ? <span className="project-list__private">{status.name}</span> : null}
                        {due ? (
                          <span className="project-list__private">{formatDateKo(due, timeZone)}</span>
                        ) : null}
                      </>
                    );
                    return (
                      <li key={item.id}>
                        {displayId ? (
                          <Link to={itemPath(slug, displayId)} className="task-row" data-testid={`my-task-${item.id}`}>
                            {row}
                          </Link>
                        ) : (
                          <span className="task-row">{row}</span>
                        )}
                      </li>
                    );
                  })}
                </ul>
              </section>
            );
          })}
        </div>
        {cursorStale ? (
          <p role="status" className="break-keep text-ui text-muted-foreground">
            {t("task.mine.cursorRestarted")}
          </p>
        ) : null}
        {tasks.hasNextPage || cursorStale ? (
          <TaskListLoadMore
            error={tasks.isFetchNextPageError && !cursorStale ? t("task.mine.loadMoreFailed") : null}
            pending={tasks.isFetchingNextPage}
            onLoadMore={() => {
              if (cursorStale) void tasks.refetch();
              else void tasks.fetchNextPage();
            }}
          />
        ) : null}
      </div>
    </WorkspaceShell>
  );
}

// apps/web/src/vue/pages/MyTasksPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useInfiniteQuery, useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { useRoute } from "vue-router";
import { projectsQuery } from "@/features/projects/queries";
import { groupTasksByProject, myTasksQuery, workspaceStatusesQuery } from "@/features/tasks/my-tasks";
import { mergeTaskListPages } from "@/features/tasks/task-list-page";
import { loadErrorMessage, ProblemError } from "@/lib/api";
import { FALLBACK_TZ } from "@/lib/datetime";
import { meQuery } from "@/lib/queries";
import QueryError from "../components/QueryError.vue";
import QueryLoading from "../components/QueryLoading.vue";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import MyTaskRow from "../features/tasks/MyTaskRow.vue";
import { useWorkspaceSession } from "../session/useWorkspaceSession";
import "@/features/projects/projects.css";

const route = useRoute();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const workspaceId = computed(() => workspace.value?.id ?? "");

const tasks = useInfiniteQuery(() => ({
  ...myTasksQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
}));
const statuses = useQuery(() => ({
  ...workspaceStatusesQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
}));
const projects = useQuery(() => ({
  ...projectsQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
}));
const me = useQuery(meQuery);

const items = computed(() => mergeTaskListPages(tasks.data.value?.pages ?? [])?.items ?? []);
const grouped = computed(() => groupTasksByProject(items.value));
const projectById = computed(() => new Map((projects.data.value?.items ?? []).map((project) => [project.id, project])));
const statusById = computed(() => new Map((statuses.data.value?.items ?? []).map((status) => [status.id, status])));
const timeZone = computed(() => me.data.value?.timezone ?? FALLBACK_TZ);
const cursorStale = computed(
  () => tasks.error.value instanceof ProblemError && tasks.error.value.status === 400 && items.value.length > 0,
);

function onLoadMore(): void {
  if (cursorStale.value) void tasks.refetch();
  else void tasks.fetchNextPage();
}
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :slug="slug" :workspace-name="workspace.name" active="myTasks">
    <div class="task-home" data-testid="my-tasks">
      <div class="task-home__head">
        <h1 class="task-home__title">{{ t("task.mine") }}</h1>
      </div>
      <QueryLoading v-if="tasks.isLoading.value" />
      <QueryError
        v-else-if="tasks.isError.value && items.length === 0"
        :message="loadErrorMessage(tasks.error.value)"
        @retry="() => void tasks.refetch()"
      />
      <p v-else-if="tasks.isSuccess.value && items.length === 0" class="break-keep text-lg font-semibold">
        {{ t("task.assigned.empty") }}
      </p>
      <div class="flex flex-col gap-8">
        <section v-for="[projectId, projectItems] in grouped" :key="projectId" class="flex flex-col gap-1">
          <h2 class="border-b border-default pb-2 text-sm font-medium">
            <span class="tabular-nums text-muted">{{ projectById.get(projectId)?.key ?? "—" }}</span>
            <span v-if="projectById.get(projectId)?.name" class="ml-2 break-keep">{{
              projectById.get(projectId)?.name
            }}</span>
          </h2>
          <ul class="task-status-list">
            <li v-for="item in projectItems" :key="item.id">
              <MyTaskRow
                :slug="slug"
                :item-id="item.id"
                :title="item.title"
                :number="item.number"
                :project-key="projectById.get(projectId)?.key"
                :status-name="statusById.get(item.statusId)?.name"
                :due="item.dueDate ?? item.dueAt"
                :time-zone="timeZone"
              />
            </li>
          </ul>
        </section>
      </div>
      <p v-if="cursorStale" role="status" class="break-keep text-sm text-muted">{{ t("task.mine.cursorRestarted") }}</p>
      <div v-if="tasks.hasNextPage.value || cursorStale" class="flex flex-col items-start gap-2">
        <p v-if="tasks.isFetchNextPageError.value && !cursorStale" role="alert">{{ t("task.mine.loadMoreFailed") }}</p>
        <UButton
          type="button"
          variant="outline"
          color="neutral"
          :disabled="tasks.isFetchingNextPage.value"
          @click="onLoadMore"
        >
          {{ tasks.isFetchingNextPage.value ? t("load.loading") : t("task.list.loadMore") }}
        </UButton>
      </div>
    </div>
  </WorkspaceShell>
</template>
