// apps/web/src/pages/ProjectsPage.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { loadErrorMessage } from "@/components/query-status";
import { ProjectsView } from "@/features/projects/projects-view";
import { projectsQuery, type CreateProjectBody } from "@/features/projects/queries";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { api, ensureOk } from "@/lib/api";
import { membersQuery, meQuery } from "@/lib/queries";
import { projectTasksPath } from "@/lib/href";
import type { CloneProjectBody } from "@/features/projects/queries";

export function ProjectsPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { slug, workspace } = useWorkspaceContext();
  const listQuery = useQuery(projectsQuery(workspace?.id ?? ""));
  const members = useQuery(membersQuery(workspace?.id ?? ""));
  const me = useQuery(meQuery);

  const cloneProject = useMutation({
    mutationFn: async ({ projectId, body }: { projectId: string; body: CloneProjectBody }) =>
      ensureOk(
        await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/clone", {
          params: { path: { workspace_id: workspace!.id, project_id: projectId } },
          body,
        }),
      ),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["projects", workspace?.id] });
    },
  });

  const createProject = useMutation({
    mutationFn: async (body: CreateProjectBody) =>
      ensureOk(
        await api.POST("/api/v1/workspaces/{workspace_id}/projects", {
          params: { path: { workspace_id: workspace!.id } },
          body,
        }),
      ),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["projects", workspace?.id] });
    },
  });

  if (!workspace) return null;

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="projects"
    >
      <ProjectsView
        slug={slug}
        projects={listQuery.data?.items ?? []}
        members={members.data?.items ?? []}
        currentUserId={me.data?.userId ?? null}
        loading={listQuery.isLoading}
        error={listQuery.isError ? loadErrorMessage(listQuery.error) : null}
        creating={createProject.isPending}
        cloning={cloneProject.isPending}
        onRetry={() => {
          void listQuery.refetch();
        }}
        onCreate={async (input) => {
          const project = await createProject.mutateAsync(input);
          await navigate(projectTasksPath(slug, project.key));
        }}
        onClone={async (projectId, input) => {
          const project = await cloneProject.mutateAsync({ projectId, body: input });
          await navigate(projectTasksPath(slug, project.key));
        }}
      />
    </WorkspaceShell>
  );
}

// apps/web/src/vue/pages/ProjectsPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed } from "vue";
import { useRoute } from "vue-router";
import {
  projectsQuery,
  type CloneProjectBody,
  type CreateProjectBody,
} from "@/features/projects/queries";
import { api, ensureOk, loadErrorMessage } from "@/lib/api";
import { projectTasksPath } from "@/lib/href";
import { membersQuery, meQuery } from "@/lib/queries";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import ProjectsView from "../features/projects/ProjectsView.vue";
import { useWorkspaceSession } from "../session/useWorkspaceSession";

const route = useRoute();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const workspaceId = computed(() => workspace.value?.id ?? "");
const queryClient = useQueryClient();

const listQuery = useQuery(() => projectsQuery(workspaceId.value));
const members = useQuery(() => membersQuery(workspaceId.value));
const me = useQuery(meQuery);

const createProject = useMutation({
  mutationFn: async (body: CreateProjectBody) =>
    ensureOk(
      await api.POST("/api/v1/workspaces/{workspace_id}/projects", {
        params: { path: { workspace_id: workspace.value!.id } },
        body,
      }),
    ),
  onSuccess: async () => {
    await queryClient.invalidateQueries({ queryKey: ["projects", workspace.value?.id] });
  },
});

const cloneProject = useMutation({
  mutationFn: async ({ projectId, body }: { projectId: string; body: CloneProjectBody }) =>
    ensureOk(
      await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/clone", {
        params: { path: { workspace_id: workspace.value!.id, project_id: projectId } },
        body,
      }),
    ),
  onSuccess: async () => {
    await queryClient.invalidateQueries({ queryKey: ["projects", workspace.value?.id] });
  },
});

async function onCreate(input: CreateProjectBody): Promise<void> {
  const project = await createProject.mutateAsync(input);
  window.location.assign(projectTasksPath(slug.value, project.key));
}

async function onClone(projectId: string, input: CloneProjectBody): Promise<void> {
  const project = await cloneProject.mutateAsync({ projectId, body: input });
  window.location.assign(projectTasksPath(slug.value, project.key));
}
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :slug="slug" :workspace-id="workspace.id" :workspace-name="workspace.name" active="projects">
    <ProjectsView
      :slug="slug"
      :projects="listQuery.data.value?.items ?? []"
      :members="members.data.value?.items ?? []"
      :current-user-id="me.data.value?.userId ?? null"
      :loading="listQuery.isLoading.value"
      :error="listQuery.isError.value ? loadErrorMessage(listQuery.error.value) : null"
      :creating="createProject.isPending.value"
      :cloning="cloneProject.isPending.value"
      :on-retry="() => void listQuery.refetch()"
      :on-create="onCreate"
      :on-clone="onClone"
    />
  </WorkspaceShell>
</template>
