// apps/web/src/pages/ResetPasswordPage.tsx
import { useSearchParams, useNavigate } from "react-router-dom";
import { ResetPasswordView } from "@/features/auth/reset-password";
import { api, ensureOk } from "@/lib/api";

export function ResetPasswordPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const token = searchParams.get("token");

  return (
    <ResetPasswordView
      token={token}
      onConfirm={async (newPassword) => {
        if (!token) return;
        await ensureOk(
          await api.POST("/api/v1/auth/password-reset/confirm", {
            body: { token, newPassword },
          }),
        );
        await navigate("/login?reset=1", { replace: true });
      }}
    />
  );
}

// apps/web/src/vue/pages/ResetPasswordPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery } from "@tanstack/vue-query";
import { computed, watchEffect } from "vue";
import { useRoute, useRouter } from "vue-router";
import { api, ensureOk } from "@/lib/api";
import { setupStatusQuery } from "@/lib/queries";
import { redirectTo } from "../session/navigation";
import ResetPasswordView from "../features/auth/ResetPasswordView.vue";

const route = useRoute();
const router = useRouter();
const setup = useQuery(setupStatusQuery);
const token = computed(() => {
  const value = route.query.token;
  return typeof value === "string" && value.length > 0 ? value : null;
});
const leaving = computed(() => setup.data.value?.needed === true);

watchEffect(() => {
  if (setup.isLoading.value || setup.isError.value) return;
  if (setup.data.value?.needed) {
    redirectTo("/setup");
  }
});

async function onConfirm(newPassword: string): Promise<void> {
  const value = token.value;
  if (!value) return;
  await ensureOk(
    await api.POST("/api/v1/auth/password-reset/confirm", {
      body: { token: value, newPassword },
    }),
  );
  await router.replace("/login?reset=1");
}
</script>

<template>
  <p v-if="setup.isLoading.value || leaving" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="setup.isError.value" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="setup.refetch()">{{ t("load.retry") }}</UButton>
  </div>
  <ResetPasswordView v-else :token="token" :submit-confirm="onConfirm" />
</template>
