// apps/web/src/pages/SetupPage.tsx
import { t } from "@fvoci/i18n";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Navigate, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { SetupForm } from "@/features/auth/setup";
import { api, ensureOk } from "@/lib/api";
import { setupStatusQuery } from "@/lib/queries";

export function SetupPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const statusQuery = useQuery(setupStatusQuery);

  if (statusQuery.isLoading) {
    return <p role="status">{t("load.loading")}</p>;
  }

  if (statusQuery.isError) {
    return (
      <div className="p-8">
        <p role="alert" className="text-muted-foreground">{t("load.failed")}</p>
        <Button type="button" size="sm" className="mt-2" onClick={() => void statusQuery.refetch()}>
          {t("load.retry")}
        </Button>
      </div>
    );
  }

  if (statusQuery.data && !statusQuery.data.needed) {
    return <Navigate to="/login" replace />;
  }

  return (
    <SetupForm
      brandingName={statusQuery.data?.branding.name}
      onSubmit={async (input) => {
        await ensureOk(
          await api.POST("/api/v1/setup", {
            body: {
              email: input.email,
              password: input.password,
              givenName: input.givenName,
              familyName: input.familyName || undefined,
              workspaceSlug: input.workspaceSlug,
              workspaceName: input.workspaceName,
            },
          }),
        );
        await queryClient.invalidateQueries();
        await navigate("/", { replace: true });
      }}
    />
  );
}

// apps/web/src/vue/pages/SetupPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, watchEffect } from "vue";
import { useRouter } from "vue-router";
import { api, ensureOk } from "@/lib/api";
import type { SetupInput } from "@/lib/contracts";
import { setupStatusQuery } from "@/lib/queries";
import SetupForm from "../features/auth/SetupForm.vue";

// First-instance setup (branding and the first administrator). Boot sends
// `/setup` to this Vue page (`src/app-boundary.ts` `/^\/setup\/?$/i`).

const router = useRouter();
const queryClient = useQueryClient();
const setup = useQuery(setupStatusQuery);
const brandingName = computed(() => setup.data.value?.branding.name);
const leaving = computed(() => setup.data.value?.needed === false);

watchEffect(() => {
  if (setup.isLoading.value || setup.isError.value) return;
  if (setup.data.value && !setup.data.value.needed) {
    // /login is already a Vue page: stay in this app.
    void router.replace("/login");
  }
});

async function onSubmit(input: SetupInput): Promise<void> {
  await ensureOk(
    await api.POST("/api/v1/setup", {
      body: {
        email: input.email,
        password: input.password,
        givenName: input.givenName,
        familyName: input.familyName || undefined,
        workspaceSlug: input.workspaceSlug,
        workspaceName: input.workspaceName,
      },
    }),
  );
  await queryClient.invalidateQueries();
  // Home is the React app: a full load.
  window.location.replace("/");
}
</script>

<template>
  <p v-if="setup.isLoading.value || leaving" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="setup.isError.value" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="setup.refetch()">{{ t("load.retry") }}</UButton>
  </div>
  <SetupForm v-else :branding-name="brandingName" :submit-setup="onSubmit" />
</template>
