// apps/web/src/features/documents/document-tags-bar.tsx
// Adapted from source apps/web/src/features/documents/document-tags-bar.tsx.
// The popover becomes an inline disclosure panel (this app has no popover primitive).
import { t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useId, useRef, useState } from "react";
import { QueryError, QueryLoading, loadErrorMessage } from "@/components/query-status";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { problemMessage } from "@/lib/api";
import {
  documentAssignedTagsQuery,
  documentTagPoolQuery,
  type DocumentTag,
} from "@/lib/queries/collections";
import { assignDocumentTag, createDocumentTag, removeDocumentTag } from "./document-tags-api";
import { TagChip } from "./tag-chip";
import "@/features/collections/collections.css";

export function DocumentTagsBar({
  workspaceId,
  documentId,
  projectId,
  readOnly,
}: {
  workspaceId: string;
  documentId: string;
  projectId: string | null;
  readOnly: boolean;
}) {
  const queryClient = useQueryClient();
  const panelId = useId();
  const triggerRef = useRef<HTMLButtonElement>(null);
  const [open, setOpen] = useState(false);
  const [filter, setFilter] = useState("");
  const [mutationError, setMutationError] = useState<string | null>(null);
  const assignedOptions = documentAssignedTagsQuery(workspaceId, documentId, projectId);
  const assignedQuery = useQuery(assignedOptions);
  const poolQuery = useQuery({ ...documentTagPoolQuery(workspaceId), enabled: open && !readOnly });

  const assigned = assignedQuery.data ?? [];
  const assignedIds = new Set(assigned.map((tag) => tag.id));
  const pool = poolQuery.data?.items ?? [];
  const needle = filter.trim().toLowerCase();
  const candidates = pool.filter(
    (tag) => !assignedIds.has(tag.id) && (needle === "" || tag.name.toLowerCase().includes(needle)),
  );
  const exact = pool.find((tag) => tag.name.toLowerCase() === needle);
  const canCreate = (poolQuery.data?.canCreate ?? false) && needle !== "" && exact === undefined;

  async function invalidate() {
    await queryClient.invalidateQueries({ queryKey: ["document-tags", workspaceId] });
  }

  function close() {
    setOpen(false);
    setFilter("");
    triggerRef.current?.focus();
  }

  const assign = useMutation({
    mutationFn: (tagId: string) => assignDocumentTag(workspaceId, documentId, projectId, tagId),
    onMutate: () => setMutationError(null),
    onError: (err) => setMutationError(problemMessage(err, "error.http.fallback")),
    onSuccess: async (tag: DocumentTag) => {
      queryClient.setQueryData(assignedOptions.queryKey, (items: DocumentTag[] = []) => [
        ...items.filter((item) => item.id !== tag.id),
        tag,
      ]);
      await invalidate();
      close();
    },
  });

  const create = useMutation({
    mutationFn: (name: string) => createDocumentTag(queryClient, workspaceId, name),
    onMutate: () => setMutationError(null),
    onError: (err) => setMutationError(problemMessage(err, "error.http.fallback")),
    onSuccess: async (created) => {
      await assign.mutateAsync(created.id).catch(() => undefined);
    },
  });

  const remove = useMutation({
    mutationFn: (tagId: string) => removeDocumentTag(workspaceId, documentId, projectId, tagId),
    onMutate: () => setMutationError(null),
    onError: (err) => setMutationError(problemMessage(err, "error.http.fallback")),
    onSuccess: async (_ok, tagId) => {
      queryClient.setQueryData(assignedOptions.queryKey, (items: DocumentTag[] = []) =>
        items.filter((tag) => tag.id !== tagId),
      );
      await invalidate();
    },
  });

  const pending = assign.isPending || create.isPending || remove.isPending;

  if (readOnly && assignedQuery.isSuccess && assigned.length === 0) return null;

  return (
    <div className="tags-bar" role="group" aria-label={t("doc.tags")} data-testid="document-tags-bar">
      {assignedQuery.isPending ? <QueryLoading /> : null}
      {assignedQuery.isError ? (
        <QueryError
          message={loadErrorMessage(assignedQuery.error)}
          onRetry={() => void assignedQuery.refetch()}
        />
      ) : null}
      {assigned.map((tag) => (
        <span key={tag.id} className="tags-bar__item">
          <TagChip name={tag.name} color={tag.color} />
          {readOnly ? null : (
            <button
              type="button"
              className="tags-bar__remove"
              aria-label={`${t("doc.tags.remove")}: ${tag.name}`}
              disabled={pending}
              onClick={() => remove.mutate(tag.id)}
            >
              <span aria-hidden="true">×</span>
            </button>
          )}
        </span>
      ))}
      {readOnly ? null : (
        <Button
          ref={triggerRef}
          type="button"
          size="sm"
          variant="outline"
          aria-expanded={open}
          aria-controls={panelId}
          onClick={() => (open ? close() : setOpen(true))}
        >
          {t("doc.tags.add")}
        </Button>
      )}
      {open && !readOnly ? (
        <div
          id={panelId}
          className="tags-bar__picker"
          onKeyDown={(event) => {
            if (event.key === "Escape") {
              event.preventDefault();
              close();
            }
          }}
        >
          <Input
            className="h-9"
            value={filter}
            aria-label={t("doc.tags")}
            maxLength={100}
            disabled={pending}
            autoFocus
            onChange={(event) => setFilter(event.target.value)}
            onKeyDown={(event) => {
              if (event.key !== "Enter" || event.nativeEvent.isComposing) return;
              event.preventDefault();
              const first = exact && !assignedIds.has(exact.id) ? exact : candidates[0];
              if (first) assign.mutate(first.id);
              else if (canCreate) create.mutate(filter.trim());
            }}
          />
          {poolQuery.isPending ? <QueryLoading /> : null}
          {poolQuery.isError ? (
            <QueryError
              message={loadErrorMessage(poolQuery.error)}
              onRetry={() => void poolQuery.refetch()}
            />
          ) : null}
          {poolQuery.isSuccess ? (
            <ul className="tags-bar__options">
              {candidates.map((tag) => (
                <li key={tag.id}>
                  <button
                    type="button"
                    className="tags-bar__option"
                    disabled={pending}
                    onClick={() => assign.mutate(tag.id)}
                  >
                    <TagChip name={tag.name} color={tag.color} />
                  </button>
                </li>
              ))}
              {canCreate ? (
                <li>
                  <button
                    type="button"
                    className="tags-bar__option"
                    disabled={pending}
                    onClick={() => create.mutate(filter.trim())}
                  >
                    {t("doc.tags.create", { name: filter.trim() })}
                  </button>
                </li>
              ) : null}
              {candidates.length === 0 && !canCreate ? (
                <li className="px-2 py-1 text-ui text-muted-foreground">{t("doc.tags.empty")}</li>
              ) : null}
            </ul>
          ) : null}
        </div>
      ) : null}
      {mutationError ? (
        <p role="alert" className="basis-full text-ui text-destructive">
          {mutationError}
        </p>
      ) : null}
    </div>
  );
}

// apps/web/src/vue/features/documents/DocumentTagsBar.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, nextTick, ref, useId, useTemplateRef } from "vue";
import {
  assignDocumentTag,
  createDocumentTag,
  removeDocumentTag,
} from "@/features/documents/document-tags-api";
import { loadErrorMessage, problemMessage } from "@/lib/api";
import {
  documentAssignedTagsQuery,
  documentTagPoolQuery,
  type DocumentTag,
} from "@/lib/queries/collections";
import QueryError from "../../components/QueryError.vue";
import QueryLoading from "../../components/QueryLoading.vue";
import "@/features/collections/collections.css";

// The document's tags with an inline picker (features/documents/document-tags-bar.tsx).
const props = defineProps<{
  workspaceId: string;
  documentId: string;
  projectId: string | null;
  readOnly: boolean;
}>();
const queryClient = useQueryClient();
const panelId = useId();
const trigger = useTemplateRef<{ $el?: Element }>("trigger");
const open = ref(false);
const filter = ref("");
const mutationError = ref<string | null>(null);
const assignedOptions = computed(() =>
  documentAssignedTagsQuery(props.workspaceId, props.documentId, props.projectId),
);
const assignedQuery = useQuery(assignedOptions);
const poolQuery = useQuery(() => ({
  ...documentTagPoolQuery(props.workspaceId),
  enabled: open.value && !props.readOnly,
}));

const assigned = computed(() => assignedQuery.data.value ?? []);
const assignedIds = computed(() => new Set(assigned.value.map((tag) => tag.id)));
const pool = computed(() => poolQuery.data.value?.items ?? []);
const needle = computed(() => filter.value.trim().toLowerCase());
const candidates = computed(() =>
  pool.value.filter(
    (tag) => !assignedIds.value.has(tag.id) && (needle.value === "" || tag.name.toLowerCase().includes(needle.value)),
  ),
);
const exact = computed(() => pool.value.find((tag) => tag.name.toLowerCase() === needle.value));
const canCreate = computed(
  () => (poolQuery.data.value?.canCreate ?? false) && needle.value !== "" && exact.value === undefined,
);

async function invalidate(): Promise<void> {
  await queryClient.invalidateQueries({ queryKey: ["document-tags", props.workspaceId] });
}

function close(): void {
  open.value = false;
  filter.value = "";
  const element = trigger.value?.$el;
  if (element instanceof HTMLElement) element.focus();
}

const assign = useMutation({
  mutationFn: (tagId: string) => assignDocumentTag(props.workspaceId, props.documentId, props.projectId, tagId),
  onMutate: () => {
    mutationError.value = null;
  },
  onError: (err: unknown) => {
    mutationError.value = problemMessage(err, "error.http.fallback");
  },
  onSuccess: async (tag: DocumentTag) => {
    queryClient.setQueryData(assignedOptions.value.queryKey, (items: DocumentTag[] = []) => [
      ...items.filter((item) => item.id !== tag.id),
      tag,
    ]);
    await invalidate();
    close();
  },
});

const create = useMutation({
  mutationFn: (name: string) => createDocumentTag(queryClient, props.workspaceId, name),
  onMutate: () => {
    mutationError.value = null;
  },
  onError: (err: unknown) => {
    mutationError.value = problemMessage(err, "error.http.fallback");
  },
  onSuccess: async (created) => {
    await assign.mutateAsync(created.id).catch(() => undefined);
  },
});

const remove = useMutation({
  mutationFn: (tagId: string) => removeDocumentTag(props.workspaceId, props.documentId, props.projectId, tagId),
  onMutate: () => {
    mutationError.value = null;
  },
  onError: (err: unknown) => {
    mutationError.value = problemMessage(err, "error.http.fallback");
  },
  onSuccess: async (_ok, tagId) => {
    queryClient.setQueryData(assignedOptions.value.queryKey, (items: DocumentTag[] = []) =>
      items.filter((tag) => tag.id !== tagId),
    );
    await invalidate();
  },
});

const pending = computed(() => assign.isPending.value || create.isPending.value || remove.isPending.value);
const hidden = computed(() => props.readOnly && assignedQuery.isSuccess.value && assigned.value.length === 0);
const filterInput = useTemplateRef<HTMLInputElement>("filterInput");

function toggle(): void {
  if (open.value) {
    close();
    return;
  }
  open.value = true;
  void nextTick(() => filterInput.value?.focus());
}

function onFilterKeydown(event: KeyboardEvent): void {
  if (event.key !== "Enter" || event.isComposing) return;
  event.preventDefault();
  const first = exact.value && !assignedIds.value.has(exact.value.id) ? exact.value : candidates.value[0];
  if (first) assign.mutate(first.id);
  else if (canCreate.value) create.mutate(filter.value.trim());
}

function onPanelKeydown(event: KeyboardEvent): void {
  if (event.key !== "Escape") return;
  event.preventDefault();
  close();
}
</script>

<template>
  <div v-if="!hidden" class="tags-bar" role="group" :aria-label="t('doc.tags')" data-testid="document-tags-bar">
    <QueryLoading v-if="assignedQuery.isPending.value" />
    <QueryError
      v-if="assignedQuery.isError.value"
      :message="loadErrorMessage(assignedQuery.error.value)"
      @retry="assignedQuery.refetch()"
    />
    <span v-for="tag in assigned" :key="tag.id" class="tags-bar__item">
      <span class="tag-chip" :data-color="tag.color">{{ tag.name }}</span>
      <button
        v-if="!readOnly"
        type="button"
        class="tags-bar__remove"
        :aria-label="`${t('doc.tags.remove')}: ${tag.name}`"
        :disabled="pending"
        @click="remove.mutate(tag.id)"
      >
        <span aria-hidden="true">×</span>
      </button>
    </span>
    <UButton
      v-if="!readOnly"
      ref="trigger"
      size="sm"
      variant="outline"
      color="neutral"
      :aria-expanded="open"
      :aria-controls="panelId"
      @click="toggle"
    >
      {{ t("doc.tags.add") }}
    </UButton>
    <div v-if="open && !readOnly" :id="panelId" class="tags-bar__picker" @keydown="onPanelKeydown">
      <input
        ref="filterInput"
        v-model="filter"
        class="h-9 w-full rounded-md border border-default bg-default px-3 text-sm"
        :aria-label="t('doc.tags')"
        maxlength="100"
        :disabled="pending"
        @keydown="onFilterKeydown"
      />
      <QueryLoading v-if="poolQuery.isPending.value" />
      <QueryError
        v-if="poolQuery.isError.value"
        :message="loadErrorMessage(poolQuery.error.value)"
        @retry="poolQuery.refetch()"
      />
      <ul v-if="poolQuery.isSuccess.value" class="tags-bar__options">
        <li v-for="tag in candidates" :key="tag.id">
          <button type="button" class="tags-bar__option" :disabled="pending" @click="assign.mutate(tag.id)">
            <span class="tag-chip" :data-color="tag.color">{{ tag.name }}</span>
          </button>
        </li>
        <li v-if="canCreate">
          <button type="button" class="tags-bar__option" :disabled="pending" @click="create.mutate(filter.trim())">
            {{ t("doc.tags.create", { name: filter.trim() }) }}
          </button>
        </li>
        <li v-if="candidates.length === 0 && !canCreate" class="px-2 py-1 text-sm text-muted">{{ t("doc.tags.empty") }}</li>
      </ul>
    </div>
    <p v-if="mutationError" role="alert" class="basis-full text-sm text-error">{{ mutationError }}</p>
  </div>
</template>
