// apps/web/src/features/settings/admin-shell.tsx
// Instance-admin area frame: the source's account settings nav entries for
// instance admins (settings-nav.tsx: legal, audit, admin) under one header.
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { Link, Navigate } from "react-router-dom";
import { QueryLoading } from "@/components/query-status";
import { meQuery } from "@/lib/queries";
import "@/features/documents/document-shell.css";
import "./settings-shell.css";

export type AdminNav = "admin" | "audit" | "legal";

const NAV: { key: AdminNav; to: string; label: () => string }[] = [
  { key: "admin", to: "/settings/admin", label: () => t("settings.admin") },
  { key: "audit", to: "/settings/audit", label: () => t("audit.title") },
  { key: "legal", to: "/settings/legal", label: () => t("settings.legal") },
];

/**
 * Renders children only for a signed-in instance admin; everyone else goes
 * home (source `beforeLoad`: `if (!me.isInstanceAdmin) redirect("/")`). The
 * server still answers 404 to non-admins on every /admin route.
 */
export function AdminShell({ active, children }: { active: AdminNav; children: ReactNode }) {
  const me = useQuery(meQuery);
  if (me.isError) return <Navigate to="/login" replace />;
  if (me.isLoading || !me.data) return <QueryLoading />;
  if (!me.data.isInstanceAdmin) return <Navigate to="/" replace />;

  return (
    <div className="app-shell">
      <header className="app-shell__header workspace-shell__header">
        <div className="workspace-shell__brand">
          <Link to="/" className="text-ui underline underline-offset-2">
            {t("nav.backHome")}
          </Link>
          <nav className="workspace-shell__nav" aria-label={t("admin.console")}>
            {NAV.map((item) => (
              <Link
                key={item.key}
                to={item.to}
                className={active === item.key ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
                aria-current={active === item.key ? "page" : undefined}
              >
                {item.label()}
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main className="app-shell__main">
        <div className="settings-page">{children}</div>
      </main>
    </div>
  );
}

// apps/web/src/vue/components/AdminShell.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import { RouterLink } from "vue-router";
import { useQuery } from "@tanstack/vue-query";
import { computed, watchEffect } from "vue";
import { meQuery } from "@/lib/queries";
import { loginPath, redirectTo } from "../session/navigation";
import QueryLoading from "./QueryLoading.vue";
import "@/features/settings/settings-shell.css";

export type AdminNav = "admin" | "audit" | "legal";

const props = defineProps<{ active: AdminNav }>();

const NAV: {
  key: AdminNav;
  to: string;
  labelKey: "settings.admin" | "audit.title" | "settings.legal";
}[] = [
  { key: "admin", to: "/settings/admin", labelKey: "settings.admin" },
  { key: "audit", to: "/settings/audit", labelKey: "audit.title" },
  { key: "legal", to: "/settings/legal", labelKey: "settings.legal" },
];

// Source `beforeLoad`: signed-out → /login; not an instance admin → /.
const me = useQuery(meQuery);
const ready = computed(() => me.data.value);
watchEffect(() => {
  if (me.isError.value) redirectTo(loginPath(window.location));
  else if (me.data.value && !me.data.value.isInstanceAdmin) redirectTo("/");
});
</script>

<template>
  <QueryLoading v-if="me.isLoading.value || !ready" />
  <div v-else-if="ready.isInstanceAdmin" class="flex min-h-screen flex-col">
    <header
      class="flex flex-wrap items-center justify-between gap-3 border-b border-default px-4 py-3"
    >
      <div class="flex flex-wrap items-center gap-4">
        <a href="/" class="underline underline-offset-2">{{ t("nav.backHome") }}</a>
        <nav class="flex flex-wrap items-center gap-3" :aria-label="t('admin.console')">
          <RouterLink
            v-for="item in NAV"
            :key="item.key"
            :to="item.to"
            :class="props.active === item.key ? 'font-medium text-highlighted' : undefined"
            :aria-current="props.active === item.key ? 'page' : undefined"
            >{{ t(item.labelKey) }}</RouterLink
          >
        </nav>
      </div>
    </header>
    <main class="flex-1 p-4">
      <div class="settings-page">
        <slot />
      </div>
    </main>
  </div>
</template>
