// apps/web/src/features/workspace/workspace-shell.tsx
import { t } from "@fvoci/i18n";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { AuthenticatedLegalNav } from "@/features/legal/operator-info";
import { SearchCommand } from "@/features/workspace/search-command";
import { NotificationBell } from "@/features/notifications/notification-bell";
import {
  myTasksPath,
  projectsPath,
  searchPath,
  settingsPath,
  wikiPath,
  notificationsPath,
  workspaceHomePath,
} from "@/lib/href";
import { api, ProblemError, problemMessage } from "@/lib/api";
import { workspacesQuery } from "@/lib/queries";
import "@/features/workspace/workspace-aux.css";

export type WorkspaceNav =
  | "home"
  | "wiki"
  | "settings"
  | "projects"
  | "myTasks"
  | "search"
  | "notifications";

function landingPath(slug: string, activeNav: WorkspaceNav): string {
  if (activeNav === "settings") return settingsPath(slug);
  if (activeNav === "projects") return projectsPath(slug);
  if (activeNav === "myTasks") return myTasksPath(slug);
  if (activeNav === "search") return searchPath(slug);
  if (activeNav === "notifications") return notificationsPath(slug);
  if (activeNav === "home") return workspaceHomePath(slug);
  return wikiPath(slug);
}

interface WorkspaceShellProps {
  slug: string;
  workspaceId: string;
  workspaceName: string;
  activeNav: WorkspaceNav;
  children: React.ReactNode;
}

export function WorkspaceShell({
  slug,
  workspaceId,
  workspaceName,
  activeNav,
  children,
}: WorkspaceShellProps) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const workspaces = useQuery(workspacesQuery);
  const items = workspaces.data?.items ?? [];
  const [logoutError, setLogoutError] = useState<string | null>(null);

  async function logout() {
    setLogoutError(null);
    let result;
    try {
      result = await api.POST("/api/v1/auth/logout");
    } catch {
      setLogoutError(t("error.network"));
      return;
    }
    if (!result.response.ok) {
      setLogoutError(
        problemMessage(new ProblemError(result.response.status), "error.auth.logout"),
      );
      return;
    }
    await queryClient.resetQueries();
    await navigate("/login", { replace: true });
  }

  return (
    <div className="app-shell">
      {logoutError ? (
        <div
          role="alert"
          className="border-b border-border bg-muted px-4 py-2 text-ui text-muted-foreground"
        >
          {logoutError}
        </div>
      ) : null}
      <header className="app-shell__header workspace-shell__header">
        <div className="workspace-shell__brand">
          <Link to="/" className="text-ui underline underline-offset-2">
            {t("nav.backHome")}
          </Link>
          <nav className="workspace-shell__nav" aria-label={t("nav.workspace")}>
            <Link
              to={workspaceHomePath(slug)}
              className={activeNav === "home" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "home" ? "page" : undefined}
            >
              {t("nav.home")}
            </Link>
            <Link
              to={wikiPath(slug)}
              className={activeNav === "wiki" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "wiki" ? "page" : undefined}
            >
              {t("nav.wiki")}
            </Link>
            <Link
              to={projectsPath(slug)}
              className={activeNav === "projects" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "projects" ? "page" : undefined}
            >
              {t("nav.projects")}
            </Link>
            <Link
              to={myTasksPath(slug)}
              className={activeNav === "myTasks" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "myTasks" ? "page" : undefined}
            >
              {t("task.mine")}
            </Link>
            <Link
              to={searchPath(slug)}
              className={activeNav === "search" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "search" ? "page" : undefined}
            >
              {t("nav.search")}
            </Link>
            <Link
              to={settingsPath(slug)}
              className={activeNav === "settings" ? "workspace-shell__nav-link is-active" : "workspace-shell__nav-link"}
              aria-current={activeNav === "settings" ? "page" : undefined}
            >
              {t("nav.settings")}
            </Link>
          </nav>
        </div>
        <div className="workspace-shell__controls">
          {items.length > 1 ? (
            <div className="workspace-shell__switch">
              <Label htmlFor="workspace-switch" className="sr-only">
                {t("workspace.switch")}
              </Label>
              <select
                id="workspace-switch"
                className="workspace-shell__select"
                value={workspaceId}
                onChange={(event) => {
                  const next = items.find((item) => item.id === event.target.value);
                  if (!next) return;
                  void navigate(landingPath(next.slug, activeNav));
                }}
              >
                {items.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name}
                  </option>
                ))}
              </select>
            </div>
          ) : (
            <span className="workspace-shell__name">{workspaceName}</span>
          )}
          <SearchCommand slug={slug} workspaceId={workspaceId} />
          <NotificationBell slug={slug} workspaceId={workspaceId} />
          <Link to="/settings/account" className="text-ui underline underline-offset-2">
            {t("settings.account")}
          </Link>
          <Button
            type="button"
            size="sm"
            variant="outline"
            onClick={() => {
              void logout();
            }}
          >
            {t("nav.logout")}
          </Button>
        </div>
      </header>
      <main className="app-shell__main">{children}</main>
      <footer className="border-t border-border px-4 py-3">
        <AuthenticatedLegalNav />
      </footer>
    </div>
  );
}

// apps/web/src/vue/components/WorkspaceShell.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { landingPath } from "@/features/workspace/workspace-nav";
import {
  myTasksPath,
  projectsPath,
  searchPath,
  settingsPath,
  wikiPath,
  workspaceHomePath,
} from "@/lib/href";
import { workspacesQuery } from "@/lib/queries";
import LegalNav from "../features/shell/LegalNav.vue";
import NotificationBell from "../features/shell/NotificationBell.vue";
import SearchPalette from "../features/shell/SearchPalette.vue";
import { useLogout } from "../features/shell/useLogout";
import { usePushSessionRebind } from "../features/shell/usePushSessionRebind";

// The React app's workspace shell (features/workspace/workspace-shell.tsx):
// section links, the workspace switch, the search palette, the notification
// bell, account and logout, and the legal footer. Every link and switch
// target outside this app is a React page, reached with a full page load.
const props = withDefaults(
  defineProps<{
    slug: string;
    workspaceId: string;
    workspaceName: string;
    /** The section the page belongs to. */
    active?: "wiki" | "projects";
  }>(),
  { active: "projects" },
);

const workspaces = useQuery(workspacesQuery);
const items = computed(() => workspaces.data.value?.items ?? []);
const { error: logoutError, logout } = useLogout();
usePushSessionRebind(() => props.workspaceId);

function onSwitch(event: Event): void {
  const select = event.target as HTMLSelectElement;
  const next = items.value.find((item) => item.id === select.value);
  if (next) window.location.assign(landingPath(next.slug, props.active));
  // Keep the current workspace selected until the next page actually loads.
  select.value = props.workspaceId;
}
</script>

<template>
  <div class="flex min-h-screen flex-col">
    <div v-if="logoutError" role="alert" class="border-b border-default bg-muted px-4 py-2 text-sm text-muted">
      {{ logoutError }}
    </div>
    <header class="flex flex-wrap items-center justify-between gap-3 border-b border-default px-4 py-3">
      <div class="flex flex-wrap items-center gap-4">
        <a href="/" class="underline underline-offset-2">{{ t("nav.backHome") }}</a>
        <nav class="flex flex-wrap items-center gap-3" :aria-label="t('nav.workspace')">
          <a :href="workspaceHomePath(slug)">{{ t("nav.home") }}</a>
          <a
            :href="wikiPath(slug)"
            :class="active === 'wiki' ? 'font-medium text-highlighted' : undefined"
            :aria-current="active === 'wiki' ? 'page' : undefined"
            >{{ t("nav.wiki") }}</a
          >
          <a
            :href="projectsPath(slug)"
            :class="active === 'projects' ? 'font-medium text-highlighted' : undefined"
            :aria-current="active === 'projects' ? 'page' : undefined"
            >{{ t("nav.projects") }}</a
          >
          <a :href="myTasksPath(slug)">{{ t("task.mine") }}</a>
          <a :href="searchPath(slug)">{{ t("nav.search") }}</a>
          <a :href="settingsPath(slug)">{{ t("nav.settings") }}</a>
        </nav>
      </div>
      <div class="flex flex-wrap items-center gap-3">
        <div v-if="items.length > 1">
          <label for="workspace-switch" class="sr-only">{{ t("workspace.switch") }}</label>
          <select
            id="workspace-switch"
            class="rounded-md border border-default bg-default px-2 py-1 text-sm"
            :value="workspaceId"
            @change="onSwitch"
          >
            <option v-for="item in items" :key="item.id" :value="item.id">{{ item.name }}</option>
          </select>
        </div>
        <span v-else class="font-medium" data-slot="workspace-name">{{ workspaceName }}</span>
        <SearchPalette :slug="slug" :workspace-id="workspaceId" />
        <NotificationBell :slug="slug" :workspace-id="workspaceId" />
        <a href="/settings/account" class="underline underline-offset-2">
          {{ t("settings.account") }}
        </a>
        <UButton size="sm" variant="outline" color="neutral" @click="logout">{{ t("nav.logout") }}</UButton>
      </div>
    </header>
    <main class="flex-1 p-4">
      <slot />
    </main>
    <footer class="border-t border-default px-4 py-3">
      <LegalNav />
    </footer>
  </div>
</template>
