// apps/web/src/features/tasks/task-backlinks.tsx
// Ported from source apps/web/src/features/workspace/backlinks-list.tsx and the
// task detail screen's backlinks query: shown only when something links here.
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { api, ensureOk } from "@/lib/api";
import { itemPath } from "@/lib/href";

export function TaskBacklinks({
  slug,
  workspaceId,
  taskId,
}: {
  slug: string;
  workspaceId: string;
  taskId: string;
}) {
  const backlinks = useQuery({
    queryKey: ["backlinks", "task", workspaceId, taskId] as const,
    queryFn: async () =>
      ensureOk(
        await api.GET("/api/v1/workspaces/{workspace_id}/tasks/{task_id}/backlinks", {
          params: { path: { workspace_id: workspaceId, task_id: taskId } },
        }),
      ),
    enabled: Boolean(workspaceId) && Boolean(taskId),
    retry: false,
  });
  const items = backlinks.data?.items ?? [];
  if (items.length === 0) return null;
  return (
    <section className="flex flex-col gap-2" data-testid="task-backlinks">
      <h2 className="text-doc font-medium">{t("backlinks.title")}</h2>
      <ul className="flex flex-col gap-1">
        {items.map((item) => (
          <li key={item.id}>
            {item.from.displayId ? (
              <Link to={itemPath(slug, item.from.displayId)} className="break-keep hover:underline">
                {item.from.title}
              </Link>
            ) : (
              <span className="break-keep">{item.from.title}</span>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

// apps/web/src/vue/features/tasks/TaskBacklinks.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { taskBacklinksQuery } from "@/features/tasks/queries";
import { itemPath } from "@/lib/href";
import AppLink from "../../components/AppLink.vue";

const props = defineProps<{
  slug: string;
  workspaceId: string;
  taskId: string;
}>();

const backlinks = useQuery(() => taskBacklinksQuery(props.workspaceId, props.taskId));
const items = computed(() => backlinks.data.value?.items ?? []);
</script>

<template>
  <section v-if="items.length > 0" class="flex flex-col gap-2" data-testid="task-backlinks">
    <h2 class="text-sm font-medium">{{ t("backlinks.title") }}</h2>
    <ul class="flex flex-col gap-1">
      <li v-for="item in items" :key="item.id">
        <AppLink
          v-if="item.from.displayId"
          :to="itemPath(slug, item.from.displayId)"
          class="break-keep hover:underline"
        >
          {{ item.from.title }}
        </AppLink>
        <span v-else class="break-keep">{{ item.from.title }}</span>
      </li>
    </ul>
  </section>
</template>
