// apps/web/src/vue/features/documents/ShareDialog.vue
<script setup lang="ts">
import { isI18nKey, t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref, useId } from "vue";
import {
  copyText,
  createDocumentShareLink,
  formatShareDate,
  revokeShareLink,
} from "@/features/share/share-api";
import { problemMessage } from "@/lib/api";
import { publicInstanceQuery, refreshPublicInstance } from "@/lib/queries/instance";
import { documentShareLinksQuery, type ShareDocumentTarget } from "@/lib/queries/share";
import { SHARE_POLICY_DEFAULT, selectedShareExpires, shareExpiresOptions } from "@/lib/share-links";
import NativeModal from "../../components/NativeModal.vue";
import "@/features/projects/projects.css";
import "@/features/share/share.css";

// The document's share links (features/share/share-dialog.tsx). Expiry
// choices and whether links can be created come from the public instance
// share policy; the server enforces the same policy on create.
const props = defineProps<{ workspaceId: string; target: ShareDocumentTarget }>();
const queryClient = useQueryClient();
const titleId = useId();
const expiresId = useId();
const open = ref(false);
const createdUrl = ref<string | null>(null);
const copied = ref(false);
const actionError = ref<string | null>(null);
const expiresInDays = ref<number | null>(null);
const instance = useQuery(publicInstanceQuery);
const policy = computed(() => instance.data.value?.values.share ?? SHARE_POLICY_DEFAULT);
const expiresOptions = computed(() => shareExpiresOptions(policy.value));
const selectedExpires = computed(() => selectedShareExpires(expiresInDays.value, policy.value));
const createEnabled = computed(() => instance.isSuccess.value && policy.value.enabled);
const linksOptions = computed(() => documentShareLinksQuery(props.workspaceId, props.target));
const list = useQuery(() => ({ ...linksOptions.value, enabled: open.value }));

async function invalidateLinks(): Promise<void> {
  await queryClient.invalidateQueries({ queryKey: linksOptions.value.queryKey });
}

const create = useMutation({
  mutationFn: (days: number) => createDocumentShareLink(props.workspaceId, props.target, days),
  onSuccess: async (created) => {
    actionError.value = null;
    copied.value = false;
    createdUrl.value = created.url;
    await invalidateLinks();
  },
  onError: (err: unknown) => {
    actionError.value = problemMessage(err, "error.share.failed");
  },
});

const revoke = useMutation({
  mutationFn: (id: string) => revokeShareLink(props.workspaceId, id),
  onSuccess: async () => {
    actionError.value = null;
    await invalidateLinks();
  },
  onError: (err: unknown) => {
    actionError.value = problemMessage(err, "error.share.failed");
  },
});

const pending = computed(() => create.isPending.value || revoke.isPending.value);
const links = computed(() => list.data.value?.items ?? []);
const error = computed(
  () =>
    actionError.value ??
    (instance.error.value
      ? problemMessage(instance.error.value, "error.share.failed")
      : !policy.value.enabled
        ? t("share.disabled")
        : null) ??
    (list.error.value ? problemMessage(list.error.value, "error.share.failed") : null),
);

function expiresLabel(days: number): string {
  const key = `share.expires.${days}`;
  return isI18nKey(key) ? t(key) : String(days);
}

// `/instance` is cached (query 30 s, HTTP 60 s); an admin may just have
// changed the policy. The server enforces it on create either way.
function openDialog(): void {
  void refreshPublicInstance(queryClient).catch(() => undefined);
  open.value = true;
}

function close(): void {
  open.value = false;
  createdUrl.value = null;
  actionError.value = null;
}

function copy(url: string): void {
  void copyText(url).then(
    () => {
      copied.value = true;
    },
    () => {
      copied.value = false;
    },
  );
}

function revokeRow(id: string): void {
  if (!window.confirm(`${t("share.revoke.confirm.title")}\n${t("share.revoke.confirm.body")}`)) return;
  revoke.mutate(id);
}
</script>

<template>
  <UButton size="sm" variant="outline" color="neutral" @click="openDialog">{{ t("share.create") }}</UButton>
  <NativeModal :open="open" :labelled-by="titleId" @close="close">
    <div class="share-dialog">
      <div>
        <h2 :id="titleId" class="project-dialog__title">{{ t("share.create") }}</h2>
        <p class="share-dialog__empty">{{ t("share.document") }}</p>
      </div>
      <section class="share-dialog__stack">
        <div class="share-dialog__field">
          <label :for="expiresId" class="text-sm font-medium">{{ t("share.expiresIn") }}</label>
          <select
            :id="expiresId"
            class="document-page__field-select"
            :value="String(selectedExpires)"
            :disabled="!createEnabled || pending"
            @change="expiresInDays = Number(($event.target as HTMLSelectElement).value)"
          >
            <option v-for="days in expiresOptions" :key="days" :value="String(days)">{{ expiresLabel(days) }}</option>
          </select>
        </div>
        <UButton size="sm" class="w-fit" :disabled="pending || !createEnabled" @click="create.mutate(selectedExpires)">
          {{ t("share.create") }}
        </UButton>
        <!-- WHY: 공유 링크 원문은 생성 직후 한 번만 보여 준다. 목록은 id·만료만 둔다. -->
        <div v-if="createdUrl" class="share-dialog__secret">
          <input
            :aria-label="t('share.url')"
            readonly
            :value="createdUrl"
            class="h-9 w-full rounded-md border border-default bg-default px-3 font-mono text-sm"
          />
          <UButton size="sm" variant="outline" color="neutral" @click="copy(createdUrl)">
            {{ copied ? t("share.copied") : t("share.copy") }}
          </UButton>
        </div>
        <p v-if="error" class="share-dialog__alert" role="alert">{{ error }}</p>
      </section>
      <section class="share-dialog__stack">
        <p v-if="list.isLoading.value" role="status" class="share-dialog__empty">{{ t("load.loading") }}</p>
        <p v-if="!list.isLoading.value && !list.isError.value && links.length === 0" class="share-dialog__empty">
          {{ t("share.empty") }}
        </p>
        <table v-if="links.length > 0" class="share-dialog__table">
          <thead>
            <tr>
              <th scope="col">{{ t("share.document") }}</th>
              <th scope="col">{{ t("share.expires") }}</th>
              <th scope="col"><span class="sr-only">{{ t("share.revoke") }}</span></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in links" :key="row.id">
              <td>{{ row.documentId ? t("share.document") : t("share.project") }}</td>
              <td>{{ formatShareDate(row.expiresAt) }}</td>
              <td class="text-right">
                <UButton size="sm" variant="outline" color="error" :disabled="pending" @click="revokeRow(row.id)">
                  {{ t("share.revoke") }}
                </UButton>
              </td>
            </tr>
          </tbody>
        </table>
      </section>
      <div class="flex justify-end">
        <UButton size="sm" variant="outline" color="neutral" @click="close">{{ t("common.dismiss") }}</UButton>
      </div>
    </div>
  </NativeModal>
</template>

// apps/web/src/features/share/share-dialog.tsx
import { isI18nKey, t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useId, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeModal } from "@/features/projects/native-modal";
import { problemMessage } from "@/lib/api";
import { documentShareLinksQuery, type ShareDocumentTarget } from "@/lib/queries/share";
import { publicInstanceQuery, refreshPublicInstance } from "@/lib/queries/admin";
import {
  SHARE_POLICY_DEFAULT,
  selectedShareExpires,
  shareExpiresOptions,
} from "@/lib/share-links";
import "@/features/projects/projects.css";
import {
  copyText,
  createDocumentShareLink,
  formatShareDate as formatDate,
  revokeShareLink,
} from "./share-api";
import "./share.css";

function RevealedShareUrl({ url }: { url: string }) {
  const [copied, setCopied] = useState(false);
  /* WHY: 공유 링크 원문은 생성 직후 한 번만 보여 준다. 목록은 id·만료만 두고 토큰을 다시 그리지 않는다. */
  return (
    <div className="share-dialog__secret">
      <Input aria-label={t("share.url")} readOnly value={url} className="font-mono" />
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={() => {
          void copyText(url).then(
            () => setCopied(true),
            () => setCopied(false),
          );
        }}
      >
        {copied ? t("share.copied") : t("share.copy")}
      </Button>
    </div>
  );
}

/**
 * Source `ShareDialog` for one document. Expiry choices and whether links can
 * be created come from the public instance share policy (`/instance`); the
 * server enforces the same policy on create.
 */
export function ShareDialog({
  workspaceId,
  target,
}: {
  workspaceId: string;
  target: ShareDocumentTarget;
}) {
  const queryClient = useQueryClient();
  const titleId = useId();
  const expiresId = useId();
  const [open, setOpen] = useState(false);
  const [createdUrl, setCreatedUrl] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [expiresInDays, setExpiresInDays] = useState<number | null>(null);
  const instanceQuery = useQuery(publicInstanceQuery);
  const policy = instanceQuery.data?.values.share ?? SHARE_POLICY_DEFAULT;
  const expiresOptions = shareExpiresOptions(policy);
  const selectedExpires = selectedShareExpires(expiresInDays, policy);
  const createEnabled = instanceQuery.isSuccess && policy.enabled;
  const linksQuery = documentShareLinksQuery(workspaceId, target);
  const list = useQuery({ ...linksQuery, enabled: open });

  async function invalidateLinks(): Promise<void> {
    await queryClient.invalidateQueries({ queryKey: linksQuery.queryKey });
  }

  const create = useMutation({
    mutationFn: (days: number) => createDocumentShareLink(workspaceId, target, days),
    onSuccess: async (created) => {
      setActionError(null);
      setCreatedUrl(created.url);
      await invalidateLinks();
    },
    onError: (err: unknown) => {
      setActionError(problemMessage(err, "error.share.failed"));
    },
  });

  const revoke = useMutation({
    mutationFn: (id: string) => revokeShareLink(workspaceId, id),
    onSuccess: async () => {
      setActionError(null);
      await invalidateLinks();
    },
    onError: (err: unknown) => {
      setActionError(problemMessage(err, "error.share.failed"));
    },
  });

  const pending = create.isPending || revoke.isPending;
  const links = list.data?.items ?? [];
  const error =
    actionError ??
    (instanceQuery.error
      ? problemMessage(instanceQuery.error, "error.share.failed")
      : !policy.enabled
        ? t("share.disabled")
        : null) ??
    (list.error ? problemMessage(list.error, "error.share.failed") : null);

  // `/instance` is cached (query 30 s, HTTP 60 s); an admin may just have
  // changed the policy. The server enforces it on create either way.
  function openDialog() {
    void refreshPublicInstance(queryClient).catch(() => undefined);
    setOpen(true);
  }

  function close() {
    setOpen(false);
    setCreatedUrl(null);
    setActionError(null);
  }

  return (
    <>
      <Button type="button" size="sm" variant="outline" onClick={openDialog}>
        {t("share.create")}
      </Button>
      <NativeModal open={open} labelledBy={titleId} onClose={close}>
        <div className="share-dialog">
          <div>
            <h2 id={titleId} className="project-dialog__title">
              {t("share.create")}
            </h2>
            <p className="share-dialog__empty">{t("share.document")}</p>
          </div>
          <section className="share-dialog__stack">
            <div className="share-dialog__field">
              <Label htmlFor={expiresId}>{t("share.expiresIn")}</Label>
              <select
                id={expiresId}
                className="document-page__field-select"
                value={String(selectedExpires)}
                disabled={!createEnabled || pending}
                onChange={(event) => setExpiresInDays(Number(event.target.value))}
              >
                {expiresOptions.map((days) => {
                  const key = `share.expires.${days}`;
                  return (
                    <option key={days} value={String(days)}>
                      {isI18nKey(key) ? t(key) : String(days)}
                    </option>
                  );
                })}
              </select>
            </div>
            <Button
              type="button"
              size="sm"
              disabled={pending || !createEnabled}
              onClick={() => create.mutate(selectedExpires)}
            >
              {t("share.create")}
            </Button>
            {createdUrl ? <RevealedShareUrl key={createdUrl} url={createdUrl} /> : null}
            {error ? (
              <p className="share-dialog__alert" role="alert">
                {error}
              </p>
            ) : null}
          </section>
          <section className="share-dialog__stack">
            {list.isLoading ? (
              <p role="status" className="share-dialog__empty">
                {t("load.loading")}
              </p>
            ) : null}
            {!list.isLoading && !list.isError && links.length === 0 ? (
              <p className="share-dialog__empty">{t("share.empty")}</p>
            ) : null}
            {links.length > 0 ? (
              <table className="share-dialog__table">
                <thead>
                  <tr>
                    <th scope="col">{t("share.document")}</th>
                    <th scope="col">{t("share.expires")}</th>
                    <th scope="col">
                      <span className="sr-only">{t("share.revoke")}</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {links.map((row) => (
                    <tr key={row.id}>
                      <td>{row.documentId ? t("share.document") : t("share.project")}</td>
                      <td>{formatDate(row.expiresAt)}</td>
                      <td className="text-right">
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          className="text-destructive"
                          disabled={pending}
                          onClick={() => {
                            if (
                              !window.confirm(
                                `${t("share.revoke.confirm.title")}\n${t("share.revoke.confirm.body")}`,
                              )
                            ) {
                              return;
                            }
                            revoke.mutate(row.id);
                          }}
                        >
                          {t("share.revoke")}
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : null}
          </section>
          <div className="flex justify-end">
            <Button type="button" size="sm" variant="outline" onClick={close}>
              {t("common.dismiss")}
            </Button>
          </div>
        </div>
      </NativeModal>
    </>
  );
}
