// apps/web/src/vue/features/documents/StarToggle.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref } from "vue";
import { toggleStar } from "@/features/share/share-api";
import { problemMessage } from "@/lib/api";
import { starsQuery } from "@/lib/queries/share";

// Star/unstar the page's item (features/share/star-toggle.tsx).
const props = defineProps<{ workspaceId: string; type: "document" | "task"; targetId: string }>();
const queryClient = useQueryClient();
const stars = useQuery(() => starsQuery(props.workspaceId));
const error = ref<string | null>(null);
const star = computed(() =>
  stars.data.value?.items.find((item) => item.type === props.type && item.targetId === props.targetId),
);

const toggle = useMutation({
  mutationFn: () => toggleStar(props.workspaceId, star.value, props.type, props.targetId),
  onSuccess: async () => {
    error.value = null;
    await queryClient.invalidateQueries({ queryKey: ["stars", props.workspaceId] });
  },
  onError: (err: unknown) => {
    error.value = problemMessage(err, "load.failed");
  },
});
</script>

<template>
  <UButton
    size="sm"
    variant="outline"
    color="neutral"
    :disabled="stars.isLoading.value || toggle.isPending.value"
    @click="toggle.mutate()"
  >
    <span aria-hidden="true" class="mr-1">{{ star ? "★" : "☆" }}</span>{{ star ? t("cmdk.unstar") : t("cmdk.star") }}
  </UButton>
  <p v-if="error" role="alert" class="document-page__error">{{ error }}</p>
</template>

// apps/web/src/features/share/star-toggle.tsx
import { t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { problemMessage } from "@/lib/api";
import { starsQuery } from "@/lib/queries/share";
import { toggleStar } from "./share-api";

/** Source cmdk star/unstar action, surfaced as a toggle on the item page. */
export function StarToggle({
  workspaceId,
  type,
  targetId,
}: {
  workspaceId: string;
  type: "document" | "task";
  targetId: string;
}) {
  const queryClient = useQueryClient();
  const stars = useQuery(starsQuery(workspaceId));
  const [error, setError] = useState<string | null>(null);
  const star = stars.data?.items.find((item) => item.type === type && item.targetId === targetId);

  const toggle = useMutation({
    mutationFn: () => toggleStar(workspaceId, star, type, targetId),
    onSuccess: async () => {
      setError(null);
      await queryClient.invalidateQueries({ queryKey: ["stars", workspaceId] });
    },
    onError: (err: unknown) => {
      setError(problemMessage(err, "load.failed"));
    },
  });

  return (
    <>
      <Button
        type="button"
        size="sm"
        variant="outline"
        disabled={stars.isLoading || toggle.isPending}
        onClick={() => toggle.mutate()}
      >
        <span aria-hidden className="mr-1">
          {star ? "★" : "☆"}
        </span>
        {star ? t("cmdk.unstar") : t("cmdk.star")}
      </Button>
      {error ? (
        <p role="alert" className="document-page__error">
          {error}
        </p>
      ) : null}
    </>
  );
}
