// apps/web/src/vue/features/shell/NotificationBell.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useId } from "vue";
import { useRouter } from "vue-router";
import type { NotificationItem } from "@/features/notifications/notification-target";
import { loadErrorMessage } from "@/lib/api";
import { notificationsPath } from "@/lib/href";
import QueryError from "../../components/QueryError.vue";
import { useNotificationBell } from "./useNotificationBell";

// The header bell (features/notifications/notification-bell.tsx): a button
// named by the unread count that opens the latest notifications below it.
const props = defineProps<{ slug: string; workspaceId: string }>();
const router = useRouter();
const panelId = useId();
const bell = useNotificationBell({
  workspaceId: () => props.workspaceId,
  slug: () => props.slug,
  // A task or document is a React page (the router loads it) or a wiki
  // document of this app.
  navigate: (path) => void router.push(path),
});
const { open, count, items, label, badge } = bell;
const { isPending: listPending, isError: listFailed, error: listError } = bell.list;

// As in the React bell, a failed write leaves the panel as it was.
function onItem(item: NotificationItem): void {
  bell.openItem(item).catch(() => undefined);
}

function onReadAll(): void {
  bell.readAll().catch(() => undefined);
}
</script>

<template>
  <div class="relative">
    <UButton
      color="neutral"
      variant="outline"
      square
      icon="i-lucide-bell"
      class="relative"
      :aria-label="label"
      :aria-expanded="open"
      :aria-controls="open ? panelId : undefined"
      @click="open = !open"
    >
      <span
        v-if="count > 0"
        aria-hidden="true"
        class="absolute -top-1.5 -right-1.5 min-w-4 rounded-full bg-error px-1 text-center text-[0.6875rem] leading-4 text-inverted"
        >{{ badge }}</span
      >
    </UButton>
    <div
      v-if="open"
      :id="panelId"
      role="region"
      :aria-label="t('notif.bell.title')"
      class="absolute top-full right-0 z-20 mt-1.5 w-[min(22rem,calc(100vw-1.5rem))] rounded-xl border border-default bg-default shadow-lg"
    >
      <div class="flex items-center justify-between gap-2 border-b border-default px-3 py-2">
        <p class="m-0 text-sm font-semibold">{{ t("notif.bell.title") }}</p>
        <UButton v-if="count > 0" size="sm" variant="outline" color="neutral" @click="onReadAll">{{
          t("notif.readAll")
        }}</UButton>
      </div>
      <p v-if="listPending" class="m-0 p-3 text-sm text-muted">{{ t("load.loading") }}</p>
      <div v-if="listFailed" class="p-3">
        <QueryError :message="loadErrorMessage(listError)" @retry="bell.list.refetch()" />
      </div>
      <p v-if="!listPending && !listFailed && items.length === 0" class="m-0 p-3 text-sm text-muted">
        {{ t("notif.empty") }}
      </p>
      <ul v-if="items.length > 0" class="m-0 max-h-[min(24rem,60vh)] list-none overflow-auto px-0 py-1">
        <li v-for="item in items" :key="item.id">
          <button
            type="button"
            class="flex w-full items-start gap-2 px-3 py-2 text-start text-sm break-keep hover:bg-elevated"
            @click="onItem(item)"
          >
            <span
              aria-hidden="true"
              :class="['mt-1.5 size-1.5 shrink-0 rounded-full', item.readAt ? 'bg-transparent' : 'bg-primary']"
            />
            <span>{{ bell.message(item) }}</span>
          </button>
        </li>
      </ul>
      <div class="flex items-center gap-2 border-t border-default px-3 py-2 text-sm">
        <a :href="notificationsPath(slug)" class="underline underline-offset-2">{{ t("notif.viewAll") }}</a>
      </div>
    </div>
  </div>
</template>

// apps/web/src/features/notifications/notification-bell.tsx
import { notificationMessage, t } from "@fvoci/i18n";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { QueryError, loadErrorMessage } from "@/components/query-status";
import { Button } from "@/components/ui/button";
import {
  notificationHref,
  payloadRecord,
  type NotificationItem,
} from "@/features/notifications/notification-target";
import { api, ensureOk } from "@/lib/api";
import { notificationsPath } from "@/lib/href";
import { notificationListQuery, notificationUnreadCountQuery } from "@/lib/queries";
import "@/features/notifications/notifications.css";

export function NotificationBell({
  slug,
  workspaceId,
}: {
  slug: string;
  workspaceId: string;
}) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const unread = useQuery(notificationUnreadCountQuery(workspaceId));
  const list = useQuery({
    ...notificationListQuery(workspaceId, "all"),
    enabled: open,
  });
  const count = unread.data?.count ?? 0;
  const items = list.data?.items ?? [];

  async function markRead(item: NotificationItem) {
    if (!item.readAt) {
      await ensureOk(
        await api.PATCH("/api/v1/workspaces/{workspace_id}/notifications/{id}", {
          params: { path: { workspace_id: workspaceId, id: item.id } },
          body: { read: true },
        }),
      );
      await queryClient.invalidateQueries({ queryKey: ["notifications", workspaceId] });
      await queryClient.invalidateQueries({ queryKey: ["notifications-unread", workspaceId] });
    }
    const href = notificationHref(slug, item);
    setOpen(false);
    if (href) void navigate(href);
  }

  async function readAll() {
    await ensureOk(
      await api.POST("/api/v1/workspaces/{workspace_id}/notifications/read-all", {
        params: { path: { workspace_id: workspaceId } },
      }),
    );
    await queryClient.invalidateQueries({ queryKey: ["notifications", workspaceId] });
    await queryClient.invalidateQueries({ queryKey: ["notifications-unread", workspaceId] });
  }

  return (
    <div className="notification-bell">
      <button
        type="button"
        className="notification-bell__trigger"
        aria-expanded={open}
        aria-label={count > 0 ? t("notif.unreadCount", { count }) : t("notif.bell.title")}
        onClick={() => setOpen((value) => !value)}
      >
        <span aria-hidden="true">🔔</span>
        {count > 0 ? (
          <span className="notification-bell__badge" aria-hidden="true">
            {count > 99 ? "99+" : count}
          </span>
        ) : null}
      </button>
      {open ? (
        <div className="notification-bell__panel" aria-label={t("notif.bell.title")}>
          <div className="notification-bell__head">
            <p className="notification-bell__title">{t("notif.bell.title")}</p>
            {count > 0 ? (
              <Button type="button" variant="outline" size="sm" onClick={() => void readAll()}>
                {t("notif.readAll")}
              </Button>
            ) : null}
          </div>
          {list.isPending ? (
            <p className="notification-bell__empty">{t("load.loading")}</p>
          ) : null}
          {list.isError ? (
            <div className="notification-bell__empty">
              <QueryError
                message={loadErrorMessage(list.error)}
                onRetry={() => {
                  void list.refetch();
                }}
              />
            </div>
          ) : null}
          {!list.isPending && !list.isError && items.length === 0 ? (
            <p className="notification-bell__empty">{t("notif.empty")}</p>
          ) : null}
          {items.length > 0 ? (
            <ul className="notification-bell__list">
              {items.map((item) => (
                <li key={item.id}>
                  <button
                    type="button"
                    className="notification-bell__item"
                    onClick={() => void markRead(item)}
                  >
                    <span
                      className={
                        item.readAt
                          ? "notification-bell__dot is-read"
                          : "notification-bell__dot"
                      }
                      aria-hidden="true"
                    />
                    <span>{notificationMessage({ verb: item.verb, payload: payloadRecord(item.payload) })}</span>
                  </button>
                </li>
              ))}
            </ul>
          ) : null}
          <div className="notification-bell__foot">
            <Link to={notificationsPath(slug)} onClick={() => setOpen(false)}>
              {t("notif.viewAll")}
            </Link>
          </div>
        </div>
      ) : null}
    </div>
  );
}
