// apps/web/src/vue/features/wiki/WikiHomeView.vue
<script setup lang="ts">
import { t, type I18nKey } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { computed } from "vue";
import { childrenByParent } from "@/features/workspace/wiki-tree";
import { trashPath } from "@/lib/href";
import type { TreeNode } from "@/lib/queries/documents";
import QueryError from "../../components/QueryError.vue";
import QueryLoading from "../../components/QueryLoading.vue";
import WikiBranch from "./WikiBranch.vue";
import "@/features/documents/document-shell.css";

const ROLE_LABEL: Record<string, I18nKey> = {
  guest: "role.guest",
  member: "role.member",
  admin: "role.admin",
  owner: "role.owner",
};

const props = defineProps<{
  slug: string;
  nodes: readonly TreeNode[];
  loading: boolean;
  error: string | null;
  creating: boolean;
  createError: string | null;
  canCreate: boolean;
  role: string;
  onRetry: () => void;
  onCreate: () => void;
}>();

const wikiRoots = computed(() =>
  props.nodes.filter((node) => node.parentId === null && node.projectId === null),
);
const byParent = computed(() => childrenByParent(props.nodes));
const empty = computed(() => !props.loading && !props.error && wikiRoots.value.length === 0);

function roleLabel(role: string): string {
  const key = ROLE_LABEL[role];
  return key ? t(key) : role;
}

function create(): void {
  if (!props.canCreate || props.creating) return;
  props.onCreate();
}
</script>

<template>
  <div class="wiki-home">
    <div class="wiki-home__head">
      <div class="wiki-home__intro">
        <h1 class="wiki-home__title">{{ t("nav.wiki") }}</h1>
        <p class="wiki-home__role">{{ t("wiki.role.current", { role: roleLabel(role) }) }}</p>
        <a class="wiki-home__trash-link underline underline-offset-2" :href="trashPath(slug)">{{
          t("trash.title")
        }}</a>
      </div>
      <UButton v-if="canCreate && !empty" type="button" :disabled="creating" @click="create">
        {{ creating ? t("doc.create.pending") : t("nav.newDocument") }}
      </UButton>
    </div>
    <p v-if="createError" role="alert" class="wiki-home__error">{{ createError }}</p>
    <div
      v-if="empty"
      class="mx-auto flex w-full max-w-lg flex-1 flex-col items-start justify-center gap-3 px-6 py-12"
    >
      <p class="break-keep text-lg font-semibold">{{ t("doc.empty") }}</p>
      <p v-if="canCreate" class="max-w-prose break-keep text-sm leading-relaxed text-muted">
        {{ t("doc.firstHint") }}
      </p>
      <UButton v-if="canCreate" type="button" size="sm" :disabled="creating" @click="create">
        {{ t("nav.newDocument") }}
      </UButton>
    </div>
    <section v-else class="wiki-home__section">
      <QueryLoading v-if="loading" />
      <QueryError v-else-if="error" :message="error" @retry="onRetry" />
      <p v-else-if="wikiRoots.length === 0" class="wiki-home__empty">{{ t("nav.wikiEmpty") }}</p>
      <ul v-else class="wiki-tree">
        <WikiBranch
          v-for="node in wikiRoots"
          :key="node.id"
          :slug="slug"
          :node="node"
          :by-parent="byParent"
        />
      </ul>
    </section>
  </div>
</template>

// apps/web/src/features/workspace/wiki-home-view.tsx
import { t, type I18nKey } from "@fvoci/i18n";
import { Link } from "react-router-dom";
import { EmptyState } from "@/components/empty-state";
import { QueryError, QueryLoading } from "@/components/query-status";
import { Button } from "@/components/ui/button";
import { documentPath, trashPath, wikiDisplayId } from "@/lib/href";
import type { TreeNode } from "@/lib/queries/documents";
import { childrenByParent, childrenOf } from "@/features/workspace/wiki-tree";

function roleLabel(role: string): string {
  const key = (
    {
      guest: "role.guest",
      member: "role.member",
      admin: "role.admin",
      owner: "role.owner",
    } as Record<string, I18nKey>
  )[role];
  return key ? t(key) : role;
}

function statusLabel(status: TreeNode["status"]): string | null {
  if (status === "draft") return t("doc.status.draft");
  if (status === "archived") return t("doc.status.archived");
  return null;
}

function WikiDocRow({
  slug,
  node,
  nested = false,
}: {
  slug: string;
  node: TreeNode;
  nested?: boolean;
}) {
  const status = statusLabel(node.status);
  const ref = wikiDisplayId(node.number);
  return (
    <Link
      to={documentPath(slug, ref)}
      className={nested ? "wiki-tree__row wiki-tree__row--nested" : "wiki-tree__row"}
      data-testid={`wiki-doc-${ref}`}
    >
      {node.icon ? (
        <span className="wiki-tree__icon" aria-hidden>{node.icon}</span>
      ) : null}
      <span className="wiki-tree__title">{node.title}</span>
      {status ? <span className="wiki-tree__status">{status}</span> : null}
      <span className="wiki-tree__key">{ref}</span>
    </Link>
  );
}

function WikiBranch({
  slug,
  node,
  byParent,
  nested = false,
}: {
  slug: string;
  node: TreeNode;
  byParent: ReturnType<typeof childrenByParent<TreeNode>>;
  nested?: boolean;
}) {
  const childNodes = childrenOf(byParent, node.id);
  return (
    <li className={nested ? undefined : "wiki-tree__branch"}>
      <WikiDocRow slug={slug} node={node} nested={nested} />
      {childNodes.length > 0 ? (
        <ul className="wiki-tree wiki-tree--nested">
          {childNodes.map((child) => (
            <WikiBranch key={child.id} slug={slug} node={child} byParent={byParent} nested />
          ))}
        </ul>
      ) : null}
    </li>
  );
}

interface WikiHomeViewProps {
  slug: string;
  nodes: TreeNode[];
  loading: boolean;
  error: string | null;
  creating: boolean;
  createError: string | null;
  canCreate: boolean;
  role: string;
  onRetry: () => void;
  onCreate: () => void;
}

export function WikiHomeView({
  slug,
  nodes,
  loading,
  error,
  creating,
  createError,
  canCreate,
  role,
  onRetry,
  onCreate,
}: WikiHomeViewProps) {
  const wikiRoots = nodes.filter((node) => node.parentId === null && node.projectId === null);
  const byParent = childrenByParent(nodes);
  const empty = !loading && !error && wikiRoots.length === 0;

  return (
    <div className="wiki-home">
      <div className="wiki-home__head">
        <div className="wiki-home__intro">
          <h1 className="wiki-home__title">{t("nav.wiki")}</h1>
          <p className="wiki-home__role">{t("wiki.role.current", { role: roleLabel(role) })}</p>
          <Link className="wiki-home__trash-link" to={trashPath(slug)}>
            {t("trash.title")}
          </Link>
        </div>
        {canCreate && !empty ? (
          <Button type="button" disabled={creating} onClick={onCreate}>
            {creating ? t("doc.create.pending") : t("nav.newDocument")}
          </Button>
        ) : null}
      </div>
      {createError ? (
        <p role="alert" className="wiki-home__error">{createError}</p>
      ) : null}
      {empty ? (
        <EmptyState
          title={t("doc.empty")}
          description={canCreate ? t("doc.firstHint") : undefined}
          actionLabel={canCreate ? t("nav.newDocument") : undefined}
          onAction={canCreate ? onCreate : undefined}
          actionDisabled={creating}
        />
      ) : (
        <section className="wiki-home__section">
          {loading ? <QueryLoading /> : null}
          {!loading && error ? <QueryError message={error} onRetry={onRetry} /> : null}
          {!loading && !error && wikiRoots.length === 0 ? (
            <p className="wiki-home__empty">{t("nav.wikiEmpty")}</p>
          ) : null}
          {!loading && !error && wikiRoots.length > 0 ? (
            <ul className="wiki-tree">
              {wikiRoots.map((node) => (
                <WikiBranch key={node.id} slug={slug} node={node} byParent={byParent} />
              ))}
            </ul>
          ) : null}
        </section>
      )}
    </div>
  );
}
