// apps/web/src/vue/features/workspace/WorkspaceCreateDialog.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { computed, ref, useId } from "vue";
import { ProblemError } from "@/lib/api";
import { workspaceCreateInput } from "@/lib/validators";
import NativeModal from "../../components/NativeModal.vue";
import { issueMessage, useAuthForm } from "../auth/useAuthForm";
import "@/features/workspace/workspace-aux.css";
import "@/features/projects/projects.css";
import "./workspace-home.css";

const props = defineProps<{
  open: boolean;
  onCreate: (input: { name: string; slug: string }) => Promise<void>;
}>();
const emit = defineEmits<{ close: [] }>();

const titleId = useId();
const rootError = ref<string | null>(null);
const form = useAuthForm({
  initial: { name: "", slug: "" },
  schema: workspaceCreateInput,
  ids: { name: "create-workspace-name", slug: "create-workspace-slug" },
});
const fieldError = computed(() => form.errors.name ?? form.errors.slug);

const onSubmit = form.handleSubmit(async (values) => {
  rootError.value = null;
  try {
    await props.onCreate(values);
    emit("close");
  } catch (error) {
    if (error instanceof ProblemError && (error.status === 400 || error.status === 409)) {
      form.setError("slug", issueMessage(error.status === 409 ? "i18n:slug taken" : "i18n:form.invalid"));
    } else {
      rootError.value =
        error instanceof ProblemError && error.titleKnown ? error.title : t("error.workspace.create");
    }
  }
});
</script>

<template>
  <NativeModal :open="open" :labelled-by="titleId" @close="emit('close')">
    <h2 :id="titleId" class="workspace-empty__heading">{{ t("workspace.create.dialog.title") }}</h2>
    <p class="workspace-create__hint">{{ t("workspace.create.dialog.description") }}</p>
    <form class="workspace-create" novalidate @submit="onSubmit">
      <div class="workspace-create__field">
        <label class="workspace-create__label" for="create-workspace-name">{{ t("workspace.create.name") }}</label>
        <input
          id="create-workspace-name"
          name="name"
          class="workspace-create__input"
          :disabled="form.submitting.value"
          @input="form.onInput('name', ($event.target as HTMLInputElement).value)"
        />
      </div>
      <div class="workspace-create__field">
        <label class="workspace-create__label" for="create-workspace-slug">{{ t("workspace.create.slug") }}</label>
        <input
          id="create-workspace-slug"
          name="slug"
          class="workspace-create__input"
          :disabled="form.submitting.value"
          @input="form.onInput('slug', ($event.target as HTMLInputElement).value)"
        />
        <p class="workspace-create__hint">{{ t("form.pattern.slug") }}</p>
      </div>
      <p v-if="fieldError" role="alert" class="workspace-create__alert">{{ fieldError }}</p>
      <p v-if="rootError" role="alert" class="workspace-create__alert">{{ rootError }}</p>
      <div class="workspace-empty__actions">
        <UButton type="submit" :disabled="form.submitting.value">{{ t("workspace.create.action") }}</UButton>
        <UButton type="button" variant="outline" color="neutral" @click="emit('close')">{{ t("common.cancel") }}</UButton>
      </div>
    </form>
  </NativeModal>
</template>

// apps/web/src/features/workspace/workspace-create-dialog.tsx
// Adapted from fvoci/FVOCI apps/web/src/features/workspace/workspace-create-dialog.tsx
import { t, type I18nKey } from "@fvoci/i18n";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ProblemError } from "@/lib/api";
import { formFieldMessage } from "@/lib/form-issues";
import { workspaceCreateInput } from "@/lib/validators";
import "./workspace-aux.css";

export function WorkspaceCreateDialog({
  open,
  onOpenChange,
  onCreate,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreate: (input: { name: string; slug: string }) => Promise<void>;
}) {
  const form = useForm<{ name: string; slug: string }>({
    resolver: zodResolver(workspaceCreateInput),
    defaultValues: { name: "", slug: "" },
  });
  const fieldError =
    formFieldMessage(form.formState.errors.name, "name") ??
    formFieldMessage(form.formState.errors.slug, "slug");

  if (!open) return null;

  return (
    <div className="workspace-create" role="dialog" aria-modal="true">
      <h2 className="workspace-empty__heading">{t("workspace.create.dialog.title")}</h2>
      <p className="workspace-create__hint">{t("workspace.create.dialog.description")}</p>
      <form
        noValidate
        onSubmit={form.handleSubmit(async (values) => {
          try {
            await onCreate(values);
            form.reset();
            onOpenChange(false);
          } catch (error) {
            if (error instanceof ProblemError && (error.status === 400 || error.status === 409)) {
              form.setError("slug", {
                message: error.status === 409 ? "i18n:slug taken" : "i18n:form.invalid",
              });
            } else {
              form.setError("root", {
                message:
                  error instanceof ProblemError && error.titleKnown
                    ? error.title
                    : "i18n:error.workspace.create",
              });
            }
          }
        })}
      >
        <div className="workspace-create__field">
          <Label htmlFor="create-workspace-name">{t("workspace.create.name")}</Label>
          <Input id="create-workspace-name" autoFocus disabled={form.formState.isSubmitting} {...form.register("name")} />
        </div>
        <div className="workspace-create__field">
          <Label htmlFor="create-workspace-slug">{t("workspace.create.slug")}</Label>
          <Input id="create-workspace-slug" disabled={form.formState.isSubmitting} {...form.register("slug")} />
          <p className="workspace-create__hint">{t("form.pattern.slug")}</p>
        </div>
        {fieldError ? <p role="alert" className="workspace-create__alert">{fieldError}</p> : null}
        {form.formState.errors.root?.message ? (
          <p role="alert" className="workspace-create__alert">
            {form.formState.errors.root.message.startsWith("i18n:")
              ? t(form.formState.errors.root.message.slice(5) as I18nKey)
              : form.formState.errors.root.message}
          </p>
        ) : null}
        <div className="workspace-empty__actions">
          <Button type="submit" disabled={form.formState.isSubmitting}>{t("workspace.create.action")}</Button>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{t("common.cancel")}</Button>
        </div>
      </form>
    </div>
  );
}
