// apps/web/src/features/projects/clone-project-form.tsx
import { t } from "@fvoci/i18n";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ProblemError } from "@/lib/api";
import { canonicalizeProjectKey } from "@/lib/href";
import { LeadSelect } from "./lead-select";
import {
  PROJECT_DESCRIPTION_MAX,
  PROJECT_ICON_MAX,
  PROJECT_NAME_MAX,
  projectCreatePayload,
} from "./create-payload";
import type { CloneProjectBody, ProjectListItem } from "./queries";
import type { components } from "@/generated/api";

type Member = components["schemas"]["MemberResponse"];

const cloneSchema = z.object({
  key: z.string().min(1, "i18n:form.too_small"),
  name: z.string().trim().min(1, "i18n:form.too_small").max(PROJECT_NAME_MAX, "i18n:form.too_big"),
  visibility: z.enum(["workspace", "private"]),
  description: z.string().max(PROJECT_DESCRIPTION_MAX, "i18n:form.too_big").optional(),
  icon: z.string().max(PROJECT_ICON_MAX, "i18n:form.too_big").optional(),
  leadUserId: z.string().optional(),
});

type CloneForm = z.infer<typeof cloneSchema>;

export function CloneProjectForm({
  source,
  pending,
  members,
  currentUserId,
  onSubmit,
  onCancel,
}: {
  source: ProjectListItem;
  pending?: boolean;
  members: readonly Member[];
  currentUserId: string | null;
  onSubmit: (input: CloneProjectBody) => Promise<void>;
  onCancel: () => void;
}) {
  const [serverError, setServerError] = useState<string | null>(null);
  const defaultName =
    source.name.length + " (복사)".length > PROJECT_NAME_MAX
      ? source.name.slice(0, PROJECT_NAME_MAX - " (복사)".length) + " (복사)"
      : `${source.name} (복사)`;
  const form = useForm<CloneForm>({
    resolver: zodResolver(cloneSchema),
    defaultValues: {
      key: "",
      name: defaultName,
      visibility: source.visibility === "private" ? "private" : "workspace",
      description: source.description ?? "",
      icon: source.icon ?? "",
      leadUserId: currentUserId ?? undefined,
    },
  });

  return (
    <form
      className="project-form"
      noValidate
      onSubmit={form.handleSubmit(async (values) => {
        setServerError(null);
        const parsed = projectCreatePayload(values);
        if (!parsed.ok) {
          form.setError(parsed.issue.field, { message: `i18n:form.${parsed.issue.code}` });
          return;
        }
        const body: CloneProjectBody = {
          key: parsed.body.key,
          name: parsed.body.name,
          visibility: parsed.body.visibility,
          description: parsed.body.description,
          icon: parsed.body.icon,
          ...(parsed.body.leadUserId ? { leadUserId: parsed.body.leadUserId } : {}),
        };
        try {
          await onSubmit(body);
        } catch (err) {
          setServerError(err instanceof ProblemError ? err.title : t("error.network"));
        }
      })}
    >
      <p className="project-form__hint">{t("project.clone.help")}</p>
      <p className="project-form__hint">
        {t("project.clone.source")}: {source.key} — {source.name}
      </p>
      <div className="project-form__row">
        <div className="project-form__field">
          <Label htmlFor="clone-key">{t("project.keyLabel")}</Label>
          <Input
            id="clone-key"
            autoComplete="off"
            disabled={pending || form.formState.isSubmitting}
            {...form.register("key", {
              onChange: (event) => {
                form.setValue("key", canonicalizeProjectKey(event.target.value));
              },
            })}
          />
        </div>
        <div className="project-form__field">
          <Label htmlFor="clone-name">{t("project.name")}</Label>
          <Input id="clone-name" disabled={pending || form.formState.isSubmitting} {...form.register("name")} />
        </div>
        <LeadSelect
          id="clone-lead"
          value={form.watch("leadUserId")}
          members={members}
          disabled={pending || form.formState.isSubmitting}
          onChange={(userId) => form.setValue("leadUserId", userId)}
        />
      </div>
      {serverError ? (
        <p role="alert" className="project-form__alert">{serverError}</p>
      ) : null}
      <div className="project-form__actions">
        <Button type="submit" disabled={pending || form.formState.isSubmitting}>
          {pending || form.formState.isSubmitting ? t("project.clone.pending") : t("project.clone")}
        </Button>
        <Button type="button" variant="outline" onClick={onCancel}>
          {t("common.cancel")}
        </Button>
      </div>
    </form>
  );
}

// apps/web/src/vue/features/projects/CloneProjectForm.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { computed, ref } from "vue";
import { ProblemError } from "@/lib/api";
import { canonicalizeProjectKey } from "@/lib/href";
import type { CloneProjectBody, ProjectListItem } from "@/features/projects/queries";
import type { components } from "@/generated/api";
import LeadSelect from "./LeadSelect.vue";
import { cloneDefaultName, projectFormPayload } from "./project-form";

type Member = components["schemas"]["MemberResponse"];

const props = defineProps<{
  source: ProjectListItem;
  pending?: boolean;
  members: readonly Member[];
  currentUserId: string | null;
  onSubmit: (input: CloneProjectBody) => Promise<void>;
  onCancel: () => void;
}>();

const key = ref("");
const name = ref(cloneDefaultName(props.source.name));
const visibility = ref<"workspace" | "private">(
  props.source.visibility === "private" ? "private" : "workspace",
);
const description = ref(props.source.description ?? "");
const icon = ref(props.source.icon ?? "");
const leadUserId = ref(props.currentUserId ?? "");
const fieldError = ref<string | null>(null);
const serverError = ref<string | null>(null);
const submitting = ref(false);
const busy = computed(() => props.pending === true || submitting.value);

function onKeyInput(event: Event): void {
  key.value = canonicalizeProjectKey((event.target as HTMLInputElement).value);
}

async function submitForm(event: Event): Promise<void> {
  event.preventDefault();
  fieldError.value = null;
  serverError.value = null;
  const parsed = projectFormPayload({
    key: key.value,
    name: name.value,
    visibility: visibility.value,
    description: description.value,
    icon: icon.value,
    leadUserId: leadUserId.value,
  });
  if (!parsed.ok) {
    fieldError.value = t(parsed.message);
    return;
  }
  const body: CloneProjectBody = {
    key: parsed.body.key,
    name: parsed.body.name,
    visibility: parsed.body.visibility,
    description: parsed.body.description,
    icon: parsed.body.icon,
    ...(parsed.body.leadUserId ? { leadUserId: parsed.body.leadUserId } : {}),
  };
  submitting.value = true;
  try {
    await props.onSubmit(body);
  } catch (err) {
    serverError.value = err instanceof ProblemError ? err.title : t("error.network");
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <form class="project-form" novalidate @submit="submitForm">
    <p class="project-form__hint">{{ t("project.clone.help") }}</p>
    <p class="project-form__hint"
      >{{ t("project.clone.source") }}: {{ source.key }} — {{ source.name }}</p
    >
    <div class="project-form__row">
      <div class="project-form__field">
        <label for="clone-key">{{ t("project.keyLabel") }}</label>
        <input
          id="clone-key"
          :value="key"
          autocomplete="off"
          :disabled="busy"
          @input="onKeyInput"
        />
      </div>
      <div class="project-form__field">
        <label for="clone-name">{{ t("project.name") }}</label>
        <input id="clone-name" v-model="name" :disabled="busy" />
      </div>
      <LeadSelect id="clone-lead" v-model="leadUserId" :members="members" :disabled="busy" />
    </div>
    <p v-if="fieldError" role="alert" class="project-form__alert">{{ fieldError }}</p>
    <p v-if="serverError" role="alert" class="project-form__alert">{{ serverError }}</p>
    <div class="project-form__actions">
      <UButton type="submit" :disabled="busy">
        {{ busy ? t("project.clone.pending") : t("project.clone") }}
      </UButton>
      <UButton type="button" variant="outline" color="neutral" @click="onCancel">
        {{ t("common.cancel") }}
      </UButton>
    </div>
  </form>
</template>
