// apps/web/src/features/projects/projects-view.tsx
import { t } from "@fvoci/i18n";
import { useId, useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState } from "@/components/empty-state";
import { QueryError, QueryLoading } from "@/components/query-status";
import { Button } from "@/components/ui/button";
import { CloneProjectForm } from "./clone-project-form";
import { CreateProjectForm } from "./create-project-form";
import { NativeModal } from "./native-modal";
import "./projects.css";
import type { CloneProjectBody, CreateProjectBody, ProjectListItem } from "./queries";
import type { components } from "@/generated/api";
import { projectTasksPath } from "@/lib/href";

type Member = components["schemas"]["MemberResponse"];

interface ProjectsViewProps {
  slug: string;
  projects: ProjectListItem[];
  members: readonly Member[];
  currentUserId: string | null;
  loading: boolean;
  error: string | null;
  creating?: boolean;
  cloning?: boolean;
  onRetry: () => void;
  onCreate: (input: CreateProjectBody) => Promise<void>;
  onClone: (projectId: string, input: CloneProjectBody) => Promise<void>;
}

export function ProjectsView({
  slug,
  projects,
  loading,
  error,
  members,
  currentUserId,
  creating,
  cloning,
  onRetry,
  onCreate,
  onClone,
}: ProjectsViewProps) {
  const titleId = useId();
  const cloneTitleId = useId();
  const [createOpen, setCreateOpen] = useState(false);
  const [cloneSource, setCloneSource] = useState<ProjectListItem | null>(null);
  const active = projects.filter((project) => project.status === "active");

  return (
    <div className="project-home">
      <div className="project-home__head">
        <h1 className="project-home__title">{t("nav.projects")}</h1>
        {projects.length > 0 ? (
          <Button type="button" onClick={() => setCreateOpen(true)}>
            {t("project.new")}
          </Button>
        ) : null}
      </div>
      {loading ? <QueryLoading /> : null}
      {!loading && error ? <QueryError message={error} onRetry={onRetry} /> : null}
      {!loading && !error && active.length === 0 ? (
        <EmptyState
          title={projects.length === 0 ? t("project.emptyHint") : t("project.emptyArchived")}
          actionLabel={t("project.new")}
          onAction={() => setCreateOpen(true)}
          actionDisabled={creating}
        />
      ) : null}
      {!loading && !error && active.length > 0 ? (
        <ul className="project-list">
          {active.map((project) => (
            <li key={project.id}>
              <Link to={projectTasksPath(slug, project.key)} className="project-list__row">
                <span className="project-list__key">{project.key}</span>
                <span className="project-list__meta">
                  <span className="project-list__name">{project.name}</span>
                  {project.visibility === "private" ? (
                    <span className="project-list__private">{t("project.visibility.private")}</span>
                  ) : null}
                </span>
                <span className="project-list__count">
                  {t("entrance.openTaskCount", { count: project.openTaskCount })}
                </span>
                <Button
                  type="button"
                  variant="outline"
                  className="project-list__clone"
                  onClick={(event) => {
                    event.preventDefault();
                    setCloneSource(project);
                  }}
                >
                  {t("project.clone")}
                </Button>
              </Link>
            </li>
          ))}
        </ul>
      ) : null}
      <NativeModal open={createOpen} labelledBy={titleId} onClose={() => setCreateOpen(false)}>
        <h2 id={titleId} className="project-dialog__title">
          {t("project.new")}
        </h2>
        <CreateProjectForm
          pending={creating}
          members={members}
          currentUserId={currentUserId}
          onSubmit={async (input) => {
            await onCreate(input);
            setCreateOpen(false);
          }}
          onCancel={() => setCreateOpen(false)}
        />
      </NativeModal>
      <NativeModal
        open={cloneSource !== null}
        labelledBy={cloneTitleId}
        onClose={() => setCloneSource(null)}
      >
        {cloneSource ? (
          <>
            <h2 id={cloneTitleId} className="project-dialog__title">
              {t("project.clone.title")}
            </h2>
            <CloneProjectForm
              source={cloneSource}
              pending={cloning}
              members={members}
              currentUserId={currentUserId}
              onSubmit={async (input) => {
                await onClone(cloneSource.id, input);
                setCloneSource(null);
              }}
              onCancel={() => setCloneSource(null)}
            />
          </>
        ) : null}
      </NativeModal>
    </div>
  );
}

// apps/web/src/vue/features/projects/ProjectsView.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { computed, ref, useId } from "vue";
import type { CloneProjectBody, CreateProjectBody, ProjectListItem } from "@/features/projects/queries";
import { projectTasksPath } from "@/lib/href";
import type { components } from "@/generated/api";
import NativeModal from "../../components/NativeModal.vue";
import QueryError from "../../components/QueryError.vue";
import QueryLoading from "../../components/QueryLoading.vue";
import CloneProjectForm from "./CloneProjectForm.vue";
import CreateProjectForm from "./CreateProjectForm.vue";
import "@/features/projects/projects.css";

type Member = components["schemas"]["MemberResponse"];

const props = defineProps<{
  slug: string;
  projects: readonly ProjectListItem[];
  members: readonly Member[];
  currentUserId: string | null;
  loading: boolean;
  error: string | null;
  creating?: boolean;
  cloning?: boolean;
  onRetry: () => void;
  onCreate: (input: CreateProjectBody) => Promise<void>;
  onClone: (projectId: string, input: CloneProjectBody) => Promise<void>;
}>();

const titleId = useId();
const cloneTitleId = useId();
const createOpen = ref(false);
const cloneSource = ref<ProjectListItem | null>(null);
const active = computed(() => props.projects.filter((project) => project.status === "active"));

function openCreate(): void {
  createOpen.value = true;
}

function closeCreate(): void {
  createOpen.value = false;
}

function closeClone(): void {
  cloneSource.value = null;
}

async function submitCreate(input: CreateProjectBody): Promise<void> {
  await props.onCreate(input);
  closeCreate();
}

async function submitClone(input: CloneProjectBody): Promise<void> {
  const source = cloneSource.value;
  if (!source) return;
  await props.onClone(source.id, input);
  closeClone();
}

function onCloneClick(project: ProjectListItem, event: Event): void {
  event.preventDefault();
  event.stopPropagation();
  cloneSource.value = project;
}
</script>

<template>
  <div class="project-home">
    <div class="project-home__head">
      <h1 class="project-home__title">{{ t("nav.projects") }}</h1>
      <UButton v-if="projects.length > 0" type="button" @click="openCreate">{{ t("project.new") }}</UButton>
    </div>
    <QueryLoading v-if="loading" />
    <QueryError v-else-if="error" :message="error" @retry="onRetry" />
    <div
      v-else-if="active.length === 0"
      class="mx-auto flex w-full max-w-lg flex-1 flex-col items-start justify-center gap-3 px-6 py-12"
    >
      <p class="break-keep text-lg font-semibold">
        {{ projects.length === 0 ? t("project.emptyHint") : t("project.emptyArchived") }}
      </p>
      <UButton type="button" size="sm" :disabled="creating" @click="openCreate">{{ t("project.new") }}</UButton>
    </div>
    <ul v-else class="project-list">
      <li v-for="project in active" :key="project.id">
        <a :href="projectTasksPath(slug, project.key)" class="project-list__row">
          <span class="project-list__key">{{ project.key }}</span>
          <span class="project-list__meta">
            <span class="project-list__name">{{ project.name }}</span>
            <span v-if="project.visibility === 'private'" class="project-list__private">{{
              t("project.visibility.private")
            }}</span>
          </span>
          <span class="project-list__count">{{ t("entrance.openTaskCount", { count: project.openTaskCount }) }}</span>
          <UButton
            type="button"
            variant="outline"
            color="neutral"
            class="project-list__clone"
            @click="onCloneClick(project, $event)"
          >
            {{ t("project.clone") }}
          </UButton>
        </a>
      </li>
    </ul>
    <NativeModal :open="createOpen" :labelled-by="titleId" @close="closeCreate">
      <h2 :id="titleId" class="project-dialog__title">{{ t("project.new") }}</h2>
      <CreateProjectForm
        :pending="creating"
        :members="members"
        :current-user-id="currentUserId"
        :on-submit="submitCreate"
        :on-cancel="closeCreate"
      />
    </NativeModal>
    <NativeModal :open="cloneSource !== null" :labelled-by="cloneTitleId" @close="closeClone">
      <template v-if="cloneSource">
        <h2 :id="cloneTitleId" class="project-dialog__title">{{ t("project.clone.title") }}</h2>
        <CloneProjectForm
          :source="cloneSource"
          :pending="cloning"
          :members="members"
          :current-user-id="currentUserId"
          :on-submit="submitClone"
          :on-cancel="closeClone"
        />
      </template>
    </NativeModal>
  </div>
</template>
