// apps/web/src/vue/pages/ProjectHomePage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { projectDocumentsQuery, projectQuery } from "@/features/projects/queries";
import { api, ensureOk, loadErrorMessage } from "@/lib/api";
import { projectsPath } from "@/lib/href";
import QueryError from "../components/QueryError.vue";
import QueryLoading from "../components/QueryLoading.vue";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import ProjectHomeView from "../features/projects/ProjectHomeView.vue";
import { leaveTo } from "../session/navigation";
import { useProjectRef } from "../session/useProjectRef";
import { useWorkspaceSession } from "../session/useWorkspaceSession";
import "@/features/projects/projects.css";

// `/w/:slug/:ref` project overview (archive / unarchive / delete, document
// list). After delete, leaveTo loads the remaining React projects list.
const route = useRoute();
const router = useRouter();
const queryClient = useQueryClient();
const slug = computed(() => String(route.params.slug ?? ""));
const refParam = computed(() => String(route.params.ref ?? ""));

const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const projectRef = useProjectRef(() => workspace.value?.id, refParam);
const listItem = projectRef.project;

const workspaceId = computed(() => workspace.value?.id ?? "");
const projectId = computed(() => listItem.value?.id ?? "");
const project = useQuery(() => projectQuery(workspaceId.value, projectId.value));
const documents = useQuery(() => projectDocumentsQuery(workspaceId.value, projectId.value));

const lifecycleError = ref<string | null>(null);

const lifecycle = useMutation({
  mutationFn: async (action: "archive" | "unarchive" | "delete") => {
    const ws = workspace.value?.id;
    const id = listItem.value?.id;
    if (!ws || !id) throw new Error("missing project");
    const path = { workspace_id: ws, project_id: id };
    if (action === "delete") {
      return ensureOk(
        await api.DELETE("/api/v1/workspaces/{workspace_id}/projects/{project_id}", {
          params: { path },
        }),
      );
    }
    return ensureOk(
      action === "archive"
        ? await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/archive", {
            params: { path },
          })
        : await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/unarchive", {
            params: { path },
          }),
    );
  },
  onSuccess: async (_data, action) => {
    lifecycleError.value = null;
    if (action === "delete") {
      leaveTo(projectsPath(slug.value), {
        assign: (url) => window.location.assign(url),
        push: (path) => void router.push(path),
      });
      return;
    }
    await queryClient.invalidateQueries({ queryKey: ["projects", workspace.value?.id] });
    await queryClient.invalidateQueries({ queryKey: ["project", workspace.value?.id, listItem.value?.id] });
    await queryClient.invalidateQueries({ queryKey: ["trash", workspace.value?.id] });
  },
  onError: (error: unknown, action) => {
    lifecycleError.value =
      action === "archive"
        ? t("project.archive.failed")
        : action === "unarchive"
          ? t("project.unarchive.failed")
          : loadErrorMessage(error);
  },
});

const createDocument = useMutation({
  mutationFn: async () => {
    const rootId = project.data.value?.rootDocumentId;
    const ws = workspace.value?.id;
    const id = listItem.value?.id;
    if (!ws || !id || !rootId) throw new Error("missing project root");
    return ensureOk(
      await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/documents", {
        params: {
          path: { workspace_id: ws, project_id: id },
        },
        body: {
          parentId: rootId,
          title: "새 문서",
        },
      }),
    );
  },
  onSuccess: async () => {
    await queryClient.invalidateQueries({
      queryKey: ["project-documents", workspace.value?.id, listItem.value?.id],
    });
  },
});

const loading = computed(
  () => projectRef.projects.isLoading.value || project.isLoading.value || documents.isLoading.value,
);
const error = computed(() =>
  projectRef.projects.isError.value || project.isError.value || documents.isError.value
    ? loadErrorMessage(projectRef.projects.error.value ?? project.error.value ?? documents.error.value)
    : null,
);

function retry(): void {
  void projectRef.retry();
  void project.refetch();
  void documents.refetch();
}
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :slug="slug" :workspace-id="workspace.id" :workspace-name="workspace.name">
    <p v-if="projectRef.notFound.value" role="alert" class="task-form__alert">{{ t("project.notFound") }}</p>
    <QueryError
      v-else-if="projectRef.failed.value"
      :message="loadErrorMessage(projectRef.projects.error.value)"
      @retry="projectRef.retry()"
    />
    <ProjectHomeView
      v-else-if="project.data.value"
      :slug="slug"
      :project="project.data.value"
      :nodes="documents.data.value?.items ?? []"
      :loading="loading"
      :error="error"
      :creating="createDocument.isPending.value"
      :can-manage="listItem?.canManage ?? false"
      :lifecycle-pending="lifecycle.isPending.value"
      :lifecycle-error="lifecycleError"
      @retry="retry"
      @create-document="createDocument.mutate()"
      @lifecycle="lifecycle.mutate($event)"
    />
    <QueryLoading v-else-if="loading" />
    <p v-else role="alert" class="task-form__alert">{{ error ?? t("error.resource.notFound") }}</p>
  </WorkspaceShell>
</template>

// apps/web/src/pages/ProjectHomePage.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { t } from "@fvoci/i18n";
import { loadErrorMessage } from "@/components/query-status";
import { ProjectHomeView } from "@/features/projects/project-home-view";
import {
  findProjectByKey,
  projectDocumentsQuery,
  projectQuery,
  projectsQuery,
} from "@/features/projects/queries";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { api, ensureOk } from "@/lib/api";
import { canonicalizeProjectKey, projectsPath } from "@/lib/href";

export function ProjectHomePage() {
  const { ref } = useParams<{ ref: string }>();
  const { slug, workspace } = useWorkspaceContext();
  const queryClient = useQueryClient();
  const projectKey = canonicalizeProjectKey(ref ?? "");
  const projects = useQuery(projectsQuery(workspace?.id ?? ""));
  const projectItem = findProjectByKey(projects.data?.items, projectKey);
  const project = useQuery(projectQuery(workspace?.id ?? "", projectItem?.id ?? ""));
  const documents = useQuery(
    projectDocumentsQuery(workspace?.id ?? "", projectItem?.id ?? ""),
  );
  const navigate = useNavigate();
  const [lifecycleError, setLifecycleError] = useState<string | null>(null);

  const lifecycle = useMutation({
    mutationFn: async (action: "archive" | "unarchive" | "delete") => {
      if (!workspace?.id || !projectItem?.id) throw new Error("missing project");
      const path = { workspace_id: workspace.id, project_id: projectItem.id };
      if (action === "delete") {
        return ensureOk(
          await api.DELETE("/api/v1/workspaces/{workspace_id}/projects/{project_id}", {
            params: { path },
          }),
        );
      }
      return ensureOk(
        action === "archive"
          ? await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/archive", {
              params: { path },
            })
          : await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/unarchive", {
              params: { path },
            }),
      );
    },
    onSuccess: async (_data, action) => {
      setLifecycleError(null);
      if (action === "delete") {
        await navigate(projectsPath(slug));
      }
      await queryClient.invalidateQueries({ queryKey: ["projects", workspace?.id] });
      await queryClient.invalidateQueries({ queryKey: ["project", workspace?.id, projectItem?.id] });
      await queryClient.invalidateQueries({ queryKey: ["trash", workspace?.id] });
    },
    onError: (error: unknown, action) => {
      setLifecycleError(
        action === "archive"
          ? t("project.archive.failed")
          : action === "unarchive"
            ? t("project.unarchive.failed")
            : loadErrorMessage(error),
      );
    },
  });

  const createDocument = useMutation({
    mutationFn: async () => {
      const rootId = project.data?.rootDocumentId;
      if (!workspace?.id || !projectItem?.id || !rootId) {
        throw new Error("missing project root");
      }
      return ensureOk(
        await api.POST("/api/v1/workspaces/{workspace_id}/projects/{project_id}/documents", {
          params: {
            path: { workspace_id: workspace.id, project_id: projectItem.id },
          },
          body: {
            parentId: rootId,
            title: "새 문서",
          },
        }),
      );
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: ["project-documents", workspace?.id, projectItem?.id],
      });
    },
  });

  if (!workspace) return null;

  const loading = projects.isLoading || project.isLoading || documents.isLoading;
  const error =
    projects.isError || project.isError || documents.isError
      ? loadErrorMessage(projects.error ?? project.error ?? documents.error)
      : null;

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="projects"
    >
      {project.data ? (
        <ProjectHomeView
          slug={slug}
          project={project.data}
          nodes={documents.data?.items ?? []}
          loading={loading}
          error={error}
          creating={createDocument.isPending}
          onRetry={() => {
            void projects.refetch();
            void project.refetch();
            void documents.refetch();
          }}
          onCreateDocument={() => {
            void createDocument.mutate();
          }}
          canManage={projectItem?.canManage ?? false}
          lifecyclePending={lifecycle.isPending}
          lifecycleError={lifecycleError}
          onLifecycle={(action) => lifecycle.mutate(action)}
        />
      ) : loading ? null : (
        <p role="alert" className="task-form__alert">{error ?? "not found"}</p>
      )}
    </WorkspaceShell>
  );
}
