// apps/web/src/vue/pages/PublicSharePage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/vue-query";
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import {
  sharePublicBodyQuery,
  sharePublicMetaQuery,
  sharePublicTreeQuery,
} from "@/lib/queries/share";
import PublicShareView from "../features/share/PublicShareView.vue";
import { failMessage } from "../features/share/public-share-fail";
import "@/features/share/share.css";

/**
 * Anonymous `/s/:token` reader. It never needs a session and only calls
 * `/api/v1/share/{token}/…` (no `/workspaces`, `/auth/me` or setup guard).
 * Tree and body stay disabled until meta succeeds, matching React `meta.isSuccess`.
 * The boot module still sends this path to React (src/app-boundary.ts).
 * `/s/:token/attachments/...` is a different page (#275).
 */
const route = useRoute();
const token = computed(() => String(route.params.token ?? ""));
const selectedDocumentId = ref<string | null>(null);
const meta = useQuery(() => sharePublicMetaQuery(token.value));
const tree = useQuery(() => sharePublicTreeQuery(token.value, meta.isSuccess.value));
const body = useQuery(() =>
  sharePublicBodyQuery(token.value, selectedDocumentId.value, meta.isSuccess.value),
);

const share = computed(() => meta.data.value);
const metaError = computed(() => (meta.error.value ? failMessage(meta.error.value) : null));
const bodyError = computed(() => (body.error.value ? failMessage(body.error.value) : null));
const activeDocumentId = computed(() => selectedDocumentId.value ?? share.value?.documentId ?? null);

function onSelectDocument(documentId: string): void {
  const rootId = share.value?.documentId;
  selectedDocumentId.value = documentId === rootId ? null : documentId;
}
</script>

<template>
  <div v-if="metaError" class="share-page">
    <div class="share-page__gate">
      <p role="alert" class="share-page__alert">{{ metaError }}</p>
    </div>
  </div>
  <div v-else-if="!share" class="share-page">
    <div class="share-page__gate">
      <p role="status" class="share-page__status">{{ t("doc.loading") }}</p>
    </div>
  </div>
  <PublicShareView
    v-else
    :token="token"
    :title="share.title"
    :expires-at="share.expiresAt"
    :tree="tree.data.value?.items ?? []"
    :active-document-id="activeDocumentId"
    :body="body.data.value ?? null"
    :body-loading="body.isLoading.value"
    :body-error="bodyError"
    @select-document="onSelectDocument"
    @retry-body="() => void body.refetch()"
  />
</template>

// apps/web/src/pages/PublicSharePage.tsx
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { useParams } from "react-router-dom";
import {
  PublicShareGate,
  PublicShareLoading,
  PublicShareView,
} from "@/features/share/public-share";
import { ProblemError } from "@/lib/api";
import {
  sharePublicBodyQuery,
  sharePublicMetaQuery,
  sharePublicTreeQuery,
} from "@/lib/queries/share";

function failMessage(err: unknown): string {
  if (err instanceof ProblemError && err.status === 404) return t("share.expired");
  if (err instanceof ProblemError && err.titleKnown) return err.title;
  if (err instanceof ProblemError) return t("error.share.failed");
  return t("error.network");
}

/**
 * Anonymous `/s/:token` reader. It never needs a session and only calls
 * `/api/v1/share/{token}/…` (no `/workspaces`, `/auth/me` or setup guard).
 */
export function PublicSharePage() {
  const { token = "" } = useParams<{ token: string }>();
  const [selectedDocumentId, setSelectedDocumentId] = useState<string | null>(null);
  const meta = useQuery(sharePublicMetaQuery(token));
  const tree = useQuery(sharePublicTreeQuery(token, meta.isSuccess));
  const body = useQuery(sharePublicBodyQuery(token, selectedDocumentId, meta.isSuccess));

  if (meta.error) {
    return <PublicShareGate message={failMessage(meta.error)} />;
  }
  const data = meta.data;
  if (!data) {
    return <PublicShareLoading />;
  }

  return (
    <PublicShareView
      title={data.title}
      expiresAt={data.expiresAt}
      tree={tree.data?.items ?? []}
      activeDocumentId={selectedDocumentId ?? data.documentId}
      onSelectDocument={(documentId) => {
        setSelectedDocumentId(documentId === data.documentId ? null : documentId);
      }}
      body={body.data ?? null}
      bodyLoading={body.isLoading}
      bodyError={body.error ? failMessage(body.error) : null}
      onRetryBody={() => {
        void body.refetch();
      }}
    />
  );
}
