// apps/web/src/vue/pages/TrashPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { projectsQuery } from "@/features/projects/queries";
import { api, ensureOk, loadErrorMessage } from "@/lib/api";
import { wikiPath } from "@/lib/href";
import { trashQuery } from "@/lib/queries/documents";
import QueryError from "../components/QueryError.vue";
import QueryLoading from "../components/QueryLoading.vue";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import { useWorkspaceSession } from "../session/useWorkspaceSession";
import "@/features/workspace/workspace-aux.css";

const route = useRoute();
const queryClient = useQueryClient();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const workspaceId = computed(() => workspace.value?.id ?? "");

const trash = useQuery(() => ({
  ...trashQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
}));
const projects = useQuery(() => ({
  ...projectsQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
}));
const projectKeys = computed(
  () => new Map((projects.data.value?.items ?? []).map((project) => [project.id, project.key] as const)),
);
const restoreError = ref<string | null>(null);

const restore = useMutation({
  mutationFn: async (item: { id: string; projectId?: string | null }) =>
    item.projectId
      ? ensureOk(
          await api.POST(
            "/api/v1/workspaces/{workspace_id}/projects/{project_id}/documents/{document_id}/restore",
            {
              params: {
                path: {
                  workspace_id: workspaceId.value,
                  project_id: item.projectId,
                  document_id: item.id,
                },
              },
            },
          ),
        )
      : ensureOk(
          await api.POST("/api/v1/workspaces/{workspace_id}/documents/{document_id}/restore", {
            params: {
              path: { workspace_id: workspaceId.value, document_id: item.id },
            },
          }),
        ),
  onSuccess: async (_data, item) => {
    restoreError.value = null;
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ["trash", workspaceId.value] }),
      queryClient.invalidateQueries({ queryKey: ["tree", workspaceId.value] }),
      item.projectId
        ? queryClient.invalidateQueries({
            queryKey: ["project-documents", workspaceId.value, item.projectId],
          })
        : Promise.resolve(),
    ]);
  },
  onError: (error: unknown) => {
    restoreError.value = loadErrorMessage(error);
  },
});

function onRestore(item: { id: string; projectId?: string | null }): void {
  restoreError.value = null;
  restore.mutate(item);
}
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :slug="slug" :workspace-id="workspace.id" :workspace-name="workspace.name" active="wiki">
    <div class="trash-page">
      <div class="trash-page__head">
        <h1 class="trash-page__title">{{ t("trash.title") }}</h1>
        <a :href="wikiPath(slug)">{{ t("nav.toWiki") }}</a>
      </div>
      <p class="trash-page__note">{{ t("doc.trash.retention") }}</p>
      <p v-if="restoreError" role="alert" class="trash-page__error">{{ restoreError }}</p>
      <QueryLoading v-if="trash.isLoading.value" />
      <QueryError
        v-else-if="trash.isError.value"
        :message="loadErrorMessage(trash.error.value)"
        @retry="() => void trash.refetch()"
      />
      <p v-else-if="trash.data.value?.items.length === 0">{{ t("trash.empty") }}</p>
      <ul v-else-if="trash.data.value && trash.data.value.items.length > 0" class="trash-page__list">
        <li v-for="item in trash.data.value.items" :key="item.id" class="trash-page__row">
          <div class="trash-page__copy">
            <span class="trash-page__name">{{ item.title }}</span>
            <span v-if="item.projectId" class="trash-page__project">
              {{ projectKeys.get(item.projectId) ?? t("nav.projects") }}
            </span>
            <time class="trash-page__when" :datetime="item.deletedAt">{{
              new Date(item.deletedAt).toLocaleString()
            }}</time>
          </div>
          <UButton
            type="button"
            size="sm"
            variant="outline"
            color="neutral"
            :disabled="restore.isPending.value"
            :aria-label="`${t('trash.restore')} ${item.title}`"
            @click="onRestore({ id: item.id, projectId: item.projectId })"
          >
            {{ t("trash.restore") }}
          </UButton>
        </li>
      </ul>
    </div>
  </WorkspaceShell>
</template>

// apps/web/src/pages/TrashPage.tsx
import { t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { QueryError, QueryLoading, loadErrorMessage } from "@/components/query-status";
import { Button } from "@/components/ui/button";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { api, ensureOk } from "@/lib/api";
import { wikiPath } from "@/lib/href";
import { trashQuery } from "@/lib/queries/documents";
import { projectsQuery } from "@/features/projects/queries";

export function TrashPage() {
  const queryClient = useQueryClient();
  const { slug, workspace } = useWorkspaceContext();
  const trash = useQuery(trashQuery(workspace?.id ?? ""));
  const projects = useQuery(projectsQuery(workspace?.id ?? ""));
  const projectKeys = new Map(
    (projects.data?.items ?? []).map((project) => [project.id, project.key] as const),
  );
  const [restoreError, setRestoreError] = useState<string | null>(null);

  const restore = useMutation({
    mutationFn: async (item: { id: string; projectId?: string | null }) =>
      item.projectId
        ? ensureOk(
            await api.POST(
              "/api/v1/workspaces/{workspace_id}/projects/{project_id}/documents/{document_id}/restore",
              {
                params: {
                  path: {
                    workspace_id: workspace!.id,
                    project_id: item.projectId,
                    document_id: item.id,
                  },
                },
              },
            ),
          )
        : ensureOk(
            await api.POST("/api/v1/workspaces/{workspace_id}/documents/{document_id}/restore", {
              params: {
                path: { workspace_id: workspace!.id, document_id: item.id },
              },
            }),
          ),
    onSuccess: async (_data, item) => {
      setRestoreError(null);
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["trash", workspace?.id] }),
        queryClient.invalidateQueries({ queryKey: ["tree", workspace?.id] }),
        item.projectId
          ? queryClient.invalidateQueries({
              queryKey: ["project-documents", workspace?.id, item.projectId],
            })
          : Promise.resolve(),
      ]);
    },
    onError: (error: unknown) => {
      setRestoreError(loadErrorMessage(error));
    },
  });

  if (!workspace) return null;

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="wiki"
    >
      <div className="trash-page">
        <div className="trash-page__head">
          <h1 className="trash-page__title">{t("trash.title")}</h1>
          <Link to={wikiPath(slug)}>{t("nav.toWiki")}</Link>
        </div>
        <p className="trash-page__note">{t("doc.trash.retention")}</p>
        {restoreError ? (
          <p role="alert" className="trash-page__error">
            {restoreError}
          </p>
        ) : null}
        {trash.isLoading ? <QueryLoading /> : null}
        {trash.isError ? (
          <QueryError
            message={loadErrorMessage(trash.error)}
            onRetry={() => {
              void trash.refetch();
            }}
          />
        ) : null}
        {!trash.isLoading && !trash.isError && trash.data?.items.length === 0 ? (
          <p>{t("trash.empty")}</p>
        ) : null}
        {!trash.isLoading && !trash.isError && trash.data && trash.data.items.length > 0 ? (
          <ul className="trash-page__list">
            {trash.data.items.map((item) => (
              <li key={item.id} className="trash-page__row">
                <div className="trash-page__copy">
                  <span className="trash-page__name">{item.title}</span>
                  {item.projectId ? (
                    <span className="trash-page__project">
                      {projectKeys.get(item.projectId) ?? t("nav.projects")}
                    </span>
                  ) : null}
                  <time className="trash-page__when" dateTime={item.deletedAt}>
                    {new Date(item.deletedAt).toLocaleString()}
                  </time>
                </div>
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  disabled={restore.isPending}
                  aria-label={`${t("trash.restore")} ${item.title}`}
                  onClick={() => {
                    setRestoreError(null);
                    restore.mutate({ id: item.id, projectId: item.projectId });
                  }}
                >
                  {t("trash.restore")}
                </Button>
              </li>
            ))}
          </ul>
        ) : null}
      </div>
    </WorkspaceShell>
  );
}
