// apps/web/src/vue/pages/WorkspaceSettingsPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { computed, ref, watch, watchEffect } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { showsWorkspaceSso } from "@/features/settings/workspace-sso-scope";
import { api, ensureOk, loadErrorMessage, ProblemError } from "@/lib/api";
import { documentTagsSettingsPath, templatesSettingsPath } from "@/lib/href";
import { workspaceMetaQuery } from "@/lib/queries";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import DeletedProjectsSection from "../features/settings/DeletedProjectsSection.vue";
import NotificationPrefsSection from "../features/settings/NotificationPrefsSection.vue";
import WorkspaceCalendarSection from "../features/settings/WorkspaceCalendarSection.vue";
import WorkspaceEventsSection from "../features/settings/WorkspaceEventsSection.vue";
import WorkspaceExportSection from "../features/settings/WorkspaceExportSection.vue";
import WorkspaceGithubSection from "../features/settings/WorkspaceGithubSection.vue";
import WorkspaceGroupsSection from "../features/settings/WorkspaceGroupsSection.vue";
import WorkspaceIdentitySection from "../features/settings/WorkspaceIdentitySection.vue";
import WorkspaceImportSection from "../features/settings/WorkspaceImportSection.vue";
import WorkspaceMembersSection from "../features/settings/WorkspaceMembersSection.vue";
import WorkspaceSsoSection from "../features/settings/WorkspaceSsoSection.vue";
import WorkspaceTokensSection from "../features/settings/WorkspaceTokensSection.vue";
import WorkspaceWebhooksSection from "../features/settings/WorkspaceWebhooksSection.vue";
import { roleAtLeast } from "../features/settings/workspace-role";
import { useWorkspaceSession } from "../session/useWorkspaceSession";
import "@/features/settings/settings-shell.css";

const route = useRoute();
const queryClient = useQueryClient();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const workspaceId = computed(() => workspace.value?.id ?? "");
const meta = useQuery(() => ({
  ...workspaceMetaQuery(workspaceId.value),
  enabled: Boolean(workspaceId.value),
  retry: false as const,
}));

watchEffect(() => {
  if (
    meta.error.value instanceof ProblemError &&
    (meta.error.value.status === 403 || meta.error.value.status === 404) &&
    workspace.value
  ) {
    window.location.replace("/?denied=workspace");
  }
});

const canManage = computed(() => (workspace.value ? roleAtLeast(workspace.value.role, "admin") : false));
const isOwner = computed(() => workspace.value?.role === "owner");
const memberOrAbove = computed(() => (workspace.value ? roleAtLeast(workspace.value.role, "member") : false));
const showSso = computed(() =>
  workspace.value ? showsWorkspaceSso(workspace.value.kind, canManage.value) : false,
);
const nameError = ref<string | null>(null);
const nameSaved = ref(false);
const deleteError = ref<string | null>(null);

watch(workspaceId, () => {
  nameError.value = null;
  nameSaved.value = false;
  deleteError.value = null;
});

const rename = useMutation({
  mutationFn: async (name: string) =>
    ensureOk(
      await api.PATCH("/api/v1/workspaces/{workspace_id}", {
        params: { path: { workspace_id: workspaceId.value } },
        body: { name },
      }),
    ),
  onSuccess: async () => {
    nameError.value = null;
    nameSaved.value = true;
    await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
    await queryClient.invalidateQueries({ queryKey: ["workspaces", workspaceId.value] });
  },
  onError: (err: unknown) => {
    nameSaved.value = false;
    nameError.value = err instanceof ProblemError ? err.title : t("error.network");
  },
});

const remove = useMutation({
  mutationFn: async (confirmSlug: string) =>
    ensureOk(
      await api.DELETE("/api/v1/workspaces/{workspace_id}", {
        params: { path: { workspace_id: workspaceId.value } },
        body: { confirmSlug },
      }),
    ),
  onSuccess: async () => {
    deleteError.value = null;
    await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
    window.location.replace("/");
  },
  onError: (err: unknown) => {
    deleteError.value = err instanceof ProblemError ? err.title : t("error.network");
  },
});

function onSaveName(name: string): void {
  nameSaved.value = false;
  rename.mutate(name);
}
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :key="`${workspace.id}:${workspace.role}`" :slug="slug" :workspace-id="workspace.id" :workspace-name="workspace.name" active="settings">
    <div v-if="meta.isError.value && !meta.data.value">
      <p role="alert" class="text-muted">{{ loadErrorMessage(meta.error.value) }}</p>
      <UButton size="sm" class="mt-2" @click="meta.refetch()">{{ t("load.retry") }}</UButton>
    </div>
    <div v-else class="settings-page">
      <nav :aria-label="t('nav.workspaceSettings')" class="mb-6 flex flex-wrap gap-3">
        <RouterLink :to="documentTagsSettingsPath(slug)" class="underline underline-offset-2">{{
          t("settings.documentTags.nav")
        }}</RouterLink>
        <RouterLink :to="templatesSettingsPath(slug)" class="underline underline-offset-2">{{
          t("settings.templates")
        }}</RouterLink>
      </nav>
      <WorkspaceIdentitySection
        :workspace-name="meta.data.value?.name ?? workspace.name"
        :workspace-slug="meta.data.value?.slug ?? workspace.slug"
        :workspace-kind="workspace.kind"
        :can-manage="canManage"
        :is-owner="isOwner"
        :name-pending="rename.isPending.value"
        :name-error="nameError"
        :name-saved="nameSaved"
        :delete-pending="remove.isPending.value"
        :delete-error="deleteError"
        @save-name="onSaveName"
        @delete="remove.mutate($event)"
      />
      <WorkspaceMembersSection
        v-if="memberOrAbove"
        :workspace-id="workspace.id"
        :current-user-id="session.me.value?.userId ?? null"
        :current-user-role="workspace.role"
      />
      <WorkspaceGroupsSection v-if="memberOrAbove" :workspace-id="workspace.id" :can-manage="canManage" />
      <WorkspaceExportSection :workspace-id="workspace.id" :can-manage="canManage" />
      <WorkspaceImportSection :workspace-id="workspace.id" :can-manage="canManage" />
      <NotificationPrefsSection v-if="memberOrAbove" :workspace-id="workspace.id" />
      <WorkspaceCalendarSection :workspace-id="workspace.id" />
      <WorkspaceTokensSection v-if="canManage" :workspace-id="workspace.id" />
      <WorkspaceSsoSection v-if="showSso" :workspace-id="workspace.id" />
      <WorkspaceWebhooksSection v-if="canManage" :workspace-id="workspace.id" />
      <WorkspaceGithubSection v-if="canManage" :workspace-id="workspace.id" />
      <DeletedProjectsSection v-if="canManage && workspace.kind === 'team'" :workspace-id="workspace.id" />
      <WorkspaceEventsSection v-if="canManage" :workspace-id="workspace.id" />
    </div>
  </WorkspaceShell>
</template>

// apps/web/src/pages/WorkspaceSettingsPage.tsx
import { t } from "@fvoci/i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { useState } from "react";
import { WorkspaceGroupsSection } from "@/features/settings/workspace-groups";
import { WorkspaceIdentitySection } from "@/features/settings/workspace-identity";
import { WorkspaceMembersSection } from "@/features/settings/workspace-members";
import { WorkspaceCalendarSection } from "@/features/settings/workspace-calendar";
import { WorkspaceTokensSection } from "@/features/settings/workspace-tokens";
import { WorkspaceSsoSection } from "@/features/settings/workspace-sso";
import { WorkspaceWebhooksSection } from "@/features/settings/workspace-webhooks";
import { WorkspaceGithubSection } from "@/features/settings/workspace-github";
import { WorkspaceImportSection } from "@/features/settings/workspace-import";
import { NotificationPrefsSection } from "@/features/notifications/notification-prefs";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { api, ensureOk, ProblemError } from "@/lib/api";
import { meQuery } from "@/lib/queries";
import { documentTagsSettingsPath } from "@/lib/href";

function roleAtLeast(role: string, minimum: string): boolean {
  const order = ["guest", "member", "admin", "owner"];
  return order.indexOf(role) >= order.indexOf(minimum);
}

export function WorkspaceSettingsPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [nameError, setNameError] = useState<string | null>(null);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const me = useQuery(meQuery);
  const { slug, workspace } = useWorkspaceContext();

  const metaQuery = useQuery({
    queryKey: ["workspaces", workspace?.id, "meta"],
    enabled: Boolean(workspace?.id),
    queryFn: async () =>
      ensureOk(
        await api.GET("/api/v1/workspaces/{workspace_id}", {
          params: { path: { workspace_id: workspace!.id } },
        }),
      ),
    retry: false,
  });

  const remove = useMutation({
    mutationFn: async (confirmSlug: string) =>
      ensureOk(
        await api.DELETE("/api/v1/workspaces/{workspace_id}", {
          params: { path: { workspace_id: workspace!.id } },
          body: { confirmSlug },
        }),
      ),
    onSuccess: async () => {
      setDeleteError(null);
      // Leave `/w/:slug` before invalidating the workspace list. Invalidating
      // first makes WorkspaceLayout treat the deleted slug as denied.
      await navigate("/", { replace: true });
      await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
    },
    onError: (err: unknown) => {
      setDeleteError(err instanceof ProblemError ? err.title : t("error.network"));
    },
  });

  const rename = useMutation({
    mutationFn: async (name: string) =>
      ensureOk(
        await api.PATCH("/api/v1/workspaces/{workspace_id}", {
          params: { path: { workspace_id: workspace!.id } },
          body: { name },
        }),
      ),
    onSuccess: async () => {
      setNameError(null);
      await queryClient.invalidateQueries({ queryKey: ["me", "workspaces"] });
      await queryClient.invalidateQueries({ queryKey: ["workspaces", workspace?.id] });
    },
    onError: (err: unknown) => {
      setNameError(err instanceof ProblemError ? err.title : t("error.network"));
    },
  });

  if (me.isError) {
    return <Navigate to="/login" replace />;
  }

  if (!workspace) {
    return <Navigate to="/?denied=workspace" replace />;
  }

  if (metaQuery.isError) {
    return <Navigate to="/?denied=workspace" replace />;
  }

  const canManage = roleAtLeast(workspace.role, "admin");
  const isOwner = workspace.role === "owner";

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="settings"
    >
      <div className="settings-page">
        <nav aria-label={t("nav.workspaceSettings")} className="mb-6 flex flex-wrap gap-3">
          <Link to={documentTagsSettingsPath(slug)} className="text-ui underline underline-offset-2">
            {t("settings.documentTags.nav")}
          </Link>
        </nav>
        <WorkspaceIdentitySection
          workspaceName={metaQuery.data?.name ?? workspace.name}
          workspaceSlug={metaQuery.data?.slug ?? workspace.slug}
          workspaceKind={workspace.kind}
          canManage={canManage}
          isOwner={isOwner}
          namePending={rename.isPending}
          nameError={nameError}
          onSaveName={async (name) => {
            await rename.mutateAsync(name);
          }}
          deletePending={remove.isPending}
          deleteError={deleteError}
          onDelete={async (confirmSlug) => {
            await remove.mutateAsync(confirmSlug);
          }}
        />
        {roleAtLeast(workspace.role, "member") ? (
          <WorkspaceMembersSection
            workspaceId={workspace.id}
            currentUserId={me.data?.userId ?? null}
            currentUserRole={workspace.role}
          />
        ) : null}
        {roleAtLeast(workspace.role, "member") ? (
          <WorkspaceGroupsSection workspaceId={workspace.id} canManage={canManage} />
        ) : null}
        <WorkspaceImportSection workspaceId={workspace.id} canManage={canManage} />
        {roleAtLeast(workspace.role, "member") ? (
          <NotificationPrefsSection workspaceId={workspace.id} />
        ) : null}
        <WorkspaceCalendarSection workspaceId={workspace.id} />
        {canManage ? <WorkspaceTokensSection workspaceId={workspace.id} /> : null}
        {canManage ? <WorkspaceSsoSection workspaceId={workspace.id} /> : null}
        {canManage ? <WorkspaceWebhooksSection workspaceId={workspace.id} /> : null}
        {canManage ? <WorkspaceGithubSection workspaceId={workspace.id} /> : null}
      </div>
    </WorkspaceShell>
  );
}
