// apps/web/src/vue/pages/WorkspaceHomePage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useQuery } from "@tanstack/vue-query";
import { computed } from "vue";
import { useRoute } from "vue-router";
import { projectsQuery } from "@/features/projects/queries";
import { loadErrorMessage } from "@/lib/api";
import { recentQuery, starsQuery } from "@/lib/queries/share";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import WorkspaceEntrance from "../features/projects/WorkspaceEntrance.vue";
import { useWorkspaceSession } from "../session/useWorkspaceSession";
import "@/features/share/share.css";
import "@/features/projects/projects.css";

const dayFormat = new Intl.DateTimeFormat("ko", { month: "numeric", day: "numeric" });

const route = useRoute();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const workspaceId = computed(() => workspace.value?.id ?? "");

const stars = useQuery(() => starsQuery(workspaceId.value));
const recent = useQuery(() => recentQuery(workspaceId.value, 8));
const projects = useQuery(() => projectsQuery(workspaceId.value));

const projectKeyById = computed(
  () => new Map((projects.data.value?.items ?? []).map((project) => [project.id, project.key] as const)),
);

const starItems = computed(() =>
  (stars.data.value?.items ?? []).map((star) => ({
    key: `${star.type}:${star.targetId}`,
    type: star.type,
    projectId: star.projectId,
    number: star.number,
    title: star.title,
  })),
);

const recentItems = computed(() =>
  (recent.data.value?.items ?? []).map((item) => ({
    key: `${item.type}:${item.id}`,
    type: item.type,
    projectId: item.projectId,
    number: item.number,
    title: item.title,
    meta: dayFormat.format(new Date(item.updatedAt)),
  })),
);
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{ t("load.loading") }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell v-else-if="workspace" :slug="slug" :workspace-name="workspace.name">
    <div class="entrance">
      <h1 class="project-home__title">{{ workspace.name }}</h1>
      <WorkspaceEntrance
        :slug="slug"
        :heading="t('star.home')"
        :empty="t('entrance.stars.emptyHint')"
        :items="starItems"
        :loading="stars.isLoading.value"
        :error="stars.isError.value ? loadErrorMessage(stars.error.value) : null"
        :on-retry="() => void stars.refetch()"
        :project-key-by-id="projectKeyById"
      />
      <WorkspaceEntrance
        :slug="slug"
        :heading="t('recent.title')"
        :empty="t('recent.empty')"
        :items="recentItems"
        :loading="recent.isLoading.value"
        :error="recent.isError.value ? loadErrorMessage(recent.error.value) : null"
        :on-retry="() => void recent.refetch()"
        :project-key-by-id="projectKeyById"
      />
    </div>
  </WorkspaceShell>
</template>

// apps/web/src/pages/WorkspaceHomePage.tsx
import { t } from "@fvoci/i18n";
import { useQuery } from "@tanstack/react-query";
import { useId } from "react";
import { Link } from "react-router-dom";
import { QueryError, QueryLoading, loadErrorMessage } from "@/components/query-status";
import { projectsQuery } from "@/features/projects/queries";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { itemPath } from "@/lib/href";
import { recentQuery, starsQuery } from "@/lib/queries/share";
import { starItemDisplayId } from "@/lib/share";
import "@/features/share/share.css";

const dayFormat = new Intl.DateTimeFormat("ko", { month: "numeric", day: "numeric" });

type EntranceItem = {
  key: string;
  type: string;
  projectId: string | null;
  number: number;
  title: string;
  meta?: string;
};

function EntranceSection({
  slug,
  heading,
  empty,
  items,
  loading,
  error,
  onRetry,
  projectKeyById,
}: {
  slug: string;
  heading: string;
  empty: string;
  items: readonly EntranceItem[];
  loading: boolean;
  error: string | null;
  onRetry: () => void;
  projectKeyById: ReadonlyMap<string, string>;
}) {
  const headingId = useId();
  return (
    <section className="entrance__section" aria-labelledby={headingId}>
      <h2 id={headingId} className="entrance__heading">
        {heading}
      </h2>
      {loading ? <QueryLoading /> : null}
      {!loading && error ? <QueryError message={error} onRetry={onRetry} /> : null}
      {!loading && !error && items.length === 0 ? (
        <p className="entrance__empty">{empty}</p>
      ) : null}
      {items.length > 0 ? (
        <ul className="entrance__list">
          {items.map((item) => {
            const displayId = starItemDisplayId(item, projectKeyById);
            const row = (
              <>
                <span className="entrance__key">{displayId ?? "—"}</span>
                <span className="entrance__title">{item.title}</span>
                <span className="entrance__meta">{item.meta ?? ""}</span>
              </>
            );
            return (
              <li key={item.key}>
                {displayId ? (
                  <Link className="entrance__row" to={itemPath(slug, displayId)}>
                    {row}
                  </Link>
                ) : (
                  <span className="entrance__row">{row}</span>
                )}
              </li>
            );
          })}
        </ul>
      ) : null}
    </section>
  );
}

/** Source `workspace-entrance` rail: starred items and recently updated items. */
export function WorkspaceHomePage() {
  const { slug, workspace } = useWorkspaceContext();
  const workspaceId = workspace?.id ?? "";
  const stars = useQuery(starsQuery(workspaceId));
  const recent = useQuery(recentQuery(workspaceId, 8));
  const projects = useQuery(projectsQuery(workspaceId));

  if (!workspace) return null;

  const projectKeyById = new Map(
    (projects.data?.items ?? []).map((project) => [project.id, project.key] as const),
  );

  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="home"
    >
      <div className="entrance">
        <h1 className="wiki-home__title">{workspace.name}</h1>
        <EntranceSection
          slug={slug}
          heading={t("star.home")}
          empty={t("entrance.stars.emptyHint")}
          items={(stars.data?.items ?? []).map((star) => ({
            key: `${star.type}:${star.targetId}`,
            type: star.type,
            projectId: star.projectId,
            number: star.number,
            title: star.title,
          }))}
          loading={stars.isLoading}
          error={stars.isError ? loadErrorMessage(stars.error) : null}
          onRetry={() => {
            void stars.refetch();
          }}
          projectKeyById={projectKeyById}
        />
        <EntranceSection
          slug={slug}
          heading={t("recent.title")}
          empty={t("recent.empty")}
          items={(recent.data?.items ?? []).map((item) => ({
            key: `${item.type}:${item.id}`,
            type: item.type,
            projectId: item.projectId,
            number: item.number,
            title: item.title,
            meta: dayFormat.format(new Date(item.updatedAt)),
          }))}
          loading={recent.isLoading}
          error={recent.isError ? loadErrorMessage(recent.error) : null}
          onRetry={() => {
            void recent.refetch();
          }}
          projectKeyById={projectKeyById}
        />
      </div>
    </WorkspaceShell>
  );
}
