// apps/web/src/vue/pages/WorkspaceRefPage.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { computed, watchEffect } from "vue";
import { useRoute, useRouter } from "vue-router";
import { itemPath, parseRef, projectPath } from "@/lib/href";
import WorkspaceShell from "../components/WorkspaceShell.vue";
import { useWorkspaceSession } from "../session/useWorkspaceSession";

const route = useRoute();
const router = useRouter();
const slug = computed(() => String(route.params.slug ?? ""));
const session = useWorkspaceSession(slug);
const workspace = session.workspace;
const parsed = computed(() => parseRef(String(route.params.ref ?? "")));

watchEffect(() => {
  if (session.status.value !== "ready" || !workspace.value || !parsed.value) return;
  const path =
    parsed.value.kind === "item"
      ? itemPath(slug.value, parsed.value.displayId)
      : projectPath(slug.value, parsed.value.key);
  // Preserve the original encoded query and fragment during canonicalization.
  void router.replace({ path, query: route.query, hash: route.hash });
});
</script>

<template>
  <p v-if="session.status.value === 'loading'" role="status" class="p-8 text-muted">{{
    t("load.loading")
  }}</p>
  <div v-else-if="session.status.value === 'error'" class="p-8">
    <p role="alert" class="text-muted">{{ t("load.failed") }}</p>
    <UButton size="sm" class="mt-2" @click="session.retry()">{{ t("load.retry") }}</UButton>
  </div>
  <WorkspaceShell
    v-else-if="workspace"
    :slug="slug"
    :workspace-id="workspace.id"
    :workspace-name="workspace.name"
    active="projects"
  >
    <p v-if="!parsed" role="alert" class="task-form__alert">{{ t("error.resource.notFound") }}</p>
    <p v-else role="status" class="text-muted">{{ t("load.loading") }}</p>
  </WorkspaceShell>
</template>

// apps/web/src/pages/WorkspaceRefPage.tsx
import { useEffect } from "react";
import { useLocation, useParams } from "react-router-dom";
import { t } from "@fvoci/i18n";
import { WorkspaceShell } from "@/features/workspace/workspace-shell";
import { useWorkspaceContext } from "@/hooks/use-workspace-context";
import { itemPath, projectPath, parseRef } from "@/lib/href";
import "@/features/projects/projects.css";

/**
 * Project and wiki resources are the Vue app's pages (src/app-boundary.ts). An in-app
 * link lands here first, as does a spelling the boundary does not send to
 * Vue but the router decodes to a resource ref (percent-encoded): load the
 * canonical path as a new page so the boot module starts the Vue app.
 */
function ResourceHandoff({ path }: { path: string }) {
  const { search, hash } = useLocation();
  useEffect(() => {
    window.location.replace(`${path}${search}${hash}`);
  }, [path, search, hash]);
  return null;
}

export function WorkspaceRefPage() {
  const { ref } = useParams<{ ref: string }>();
  const { slug, workspace } = useWorkspaceContext();
  const parsed = parseRef(ref ?? "");

  if (parsed?.kind === "item") {
    return <ResourceHandoff path={itemPath(slug, parsed.displayId)} />;
  }
  if (parsed?.kind === "project") {
    return <ResourceHandoff path={projectPath(slug, parsed.key)} />;
  }
  if (!workspace) return null;
  return (
    <WorkspaceShell
      slug={slug}
      workspaceId={workspace.id}
      workspaceName={workspace.name}
      activeNav="projects"
    >
      <p role="alert" className="task-form__alert">
        {t("error.resource.notFound")}
      </p>
    </WorkspaceShell>
  );
}
