// apps/web/src/features/attachments/pdf-viewer.tsx
import { t } from "@fvoci/i18n";
import type { PDFDocumentLoadingTask, PDFDocumentProxy, RenderTask } from "pdfjs-dist";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import {
  PDF_MAX_BYTES,
  PDF_MAX_IMAGE_PIXELS,
  PDF_ZOOM_MAX,
  PDF_ZOOM_MIN,
  renderScale,
  zoomIn,
  zoomOut,
} from "./pdf-limits";
import { pdfjsAssetBase } from "./pdf-assets";
import { downloadCapped, type ViewerPrefetch } from "./viewer-download";
import {
  ViewerErrorPane,
  ViewerLoadingPane,
  ViewerZoomToolbar,
} from "./viewer-shell";

type PdfJs = typeof import("pdfjs-dist");

let pdfJs: Promise<PdfJs> | null = null;

/**
 * pdf.js and its worker load only when a PDF is opened. The worker and the
 * CMap/standard-font/wasm/ICC data it fetches are same-origin build assets.
 */
function loadPdfJs(): Promise<PdfJs> {
  pdfJs ??= Promise.all([
    import("pdfjs-dist"),
    import("pdfjs-dist/build/pdf.worker.min.mjs?url"),
  ]).then(([mod, worker]) => {
    mod.GlobalWorkerOptions.workerSrc = worker.default;
    return mod;
  });
  pdfJs.catch(() => {
    pdfJs = null;
  });
  return pdfJs;
}

type DocState =
  | { status: "loading" }
  | { status: "error"; message: string; retry: boolean }
  | { status: "ready"; doc: PDFDocumentProxy };

/**
 * Renders one page at a time onto a canvas (source `PdfViewer`): page and
 * zoom controls only. No text layer, annotation layer, links, forms or
 * document scripts — pdf.js core never runs PDF JavaScript and nothing here
 * navigates to URLs from the document.
 */
export function PdfViewer({
  downloadUrl,
  prefetch,
}: {
  downloadUrl: string;
  prefetch?: ViewerPrefetch;
}): ReactNode {
  const [generation, setGeneration] = useState(0);
  const [state, setState] = useState<DocState>({ status: "loading" });
  const [page, setPage] = useState(1);
  const [zoom, setZoom] = useState(1);
  const [renderFailed, setRenderFailed] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const controller = new AbortController();
    let alive = true;
    let task: PDFDocumentLoadingTask | null = null;
    setState({ status: "loading" });
    setPage(1);
    setRenderFailed(false);
    void (async () => {
      try {
        const body = await (prefetch?.take(controller.signal) ??
          downloadCapped(downloadUrl, PDF_MAX_BYTES, controller.signal));
        if (!alive) return;
        if (body.status === "failed") {
          setState({ status: "error", message: t("load.failed"), retry: true });
          return;
        }
        if (body.status === "tooLarge") {
          setState({
            status: "error",
            message: t("attachment.viewer.previewUnavailable"),
            retry: false,
          });
          return;
        }
        const pdfjs = await loadPdfJs();
        if (!alive) return;
        const assets = new URL(
          `${import.meta.env.BASE_URL}${pdfjsAssetBase(pdfjs.version)}`,
          window.location.href,
        ).href;
        task = pdfjs.getDocument({
          data: body.bytes,
          enableXfa: false,
          maxImageSize: PDF_MAX_IMAGE_PIXELS,
          cMapUrl: `${assets}cmaps/`,
          cMapPacked: true,
          standardFontDataUrl: `${assets}standard_fonts/`,
          wasmUrl: `${assets}wasm/`,
          iccUrl: `${assets}iccs/`,
        });
        const doc = await task.promise;
        if (alive) setState({ status: "ready", doc });
      } catch (error) {
        if (!alive || (error instanceof Error && error.name === "AbortError")) return;
        setState({ status: "error", message: t("load.failed"), retry: true });
      }
    })();
    return () => {
      alive = false;
      controller.abort();
      void task?.destroy();
    };
  }, [downloadUrl, generation, prefetch]);

  const doc = state.status === "ready" ? state.doc : null;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!doc || !canvas) return;
    let alive = true;
    let render: RenderTask | null = null;
    setRenderFailed(false);
    void (async () => {
      try {
        const pdfPage = await doc.getPage(page);
        if (!alive) return;
        const base = pdfPage.getViewport({ scale: 1 });
        const scale = renderScale(base.width, base.height, zoom, window.devicePixelRatio);
        const viewport = pdfPage.getViewport({ scale });
        canvas.width = Math.floor(viewport.width);
        canvas.height = Math.floor(viewport.height);
        canvas.style.width = `${Math.floor(base.width * zoom)}px`;
        render = pdfPage.render({ canvas, viewport });
        await render.promise;
      } catch (error) {
        if (alive && !(error instanceof Error && error.name === "RenderingCancelledException")) {
          setRenderFailed(true);
        }
      }
    })();
    return () => {
      alive = false;
      render?.cancel();
    };
  }, [doc, page, zoom]);

  const retry = () => setGeneration((n) => n + 1);

  if (state.status === "loading") return <ViewerLoadingPane />;
  if (state.status === "error") {
    return (
      <ViewerErrorPane
        message={state.message}
        downloadUrl={downloadUrl}
        {...(state.retry ? { onRetry: retry } : {})}
      />
    );
  }
  if (renderFailed) {
    return <ViewerErrorPane message={t("load.failed")} downloadUrl={downloadUrl} onRetry={retry} />;
  }
  const pageCount = state.doc.numPages;
  return (
    <div className="attachment-viewer__pane" data-pdf-viewer="">
      <ViewerZoomToolbar
        zoom={zoom}
        canZoomOut={zoom > PDF_ZOOM_MIN}
        canZoomIn={zoom < PDF_ZOOM_MAX}
        onZoomIn={() => setZoom(zoomIn)}
        onZoomOut={() => setZoom(zoomOut)}
        onReset={() => setZoom(1)}
      >
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={page <= 1}
          onClick={() => setPage((p) => Math.max(1, p - 1))}
        >
          {t("attachment.viewer.prevPage")}
        </Button>
        <p className="attachment-viewer__page-label">
          {t("attachment.viewer.page", { current: page, total: pageCount })}
        </p>
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={page >= pageCount}
          onClick={() => setPage((p) => Math.min(pageCount, p + 1))}
        >
          {t("attachment.viewer.nextPage")}
        </Button>
      </ViewerZoomToolbar>
      <div className="attachment-viewer__page-wrap">
        <canvas
          ref={canvasRef}
          className="attachment-viewer__pdf-canvas"
          aria-label={t("attachment.viewer.pdf")}
        />
      </div>
    </div>
  );
}

// apps/web/src/vue/features/attachments/PdfViewer.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import type { PDFDocumentLoadingTask, PDFDocumentProxy, RenderTask } from "pdfjs-dist";
import { computed, ref, shallowRef, useTemplateRef } from "vue";
import { pdfjsAssetBase } from "@/features/attachments/pdf-assets";
import {
  PDF_MAX_BYTES,
  PDF_MAX_IMAGE_PIXELS,
  PDF_ZOOM_MAX,
  PDF_ZOOM_MIN,
  renderScale,
  zoomIn,
  zoomOut,
} from "@/features/attachments/pdf-limits";
import { downloadCapped, type ViewerPrefetch } from "@/features/attachments/viewer-download";
import { useEffectAfterRender } from "../../composables/useEffectAfterRender";
import { loadPdfJs } from "./pdfjs";
import ViewerErrorPane from "./ViewerErrorPane.vue";
import ViewerLoadingPane from "./ViewerLoadingPane.vue";
import ViewerZoomToolbar from "./ViewerZoomToolbar.vue";

/**
 * Renders one page at a time onto a canvas (source `PdfViewer`): page and
 * zoom controls only. No text layer, annotation layer, links, forms or
 * document scripts — pdf.js core never runs PDF JavaScript and nothing here
 * navigates to URLs from the document.
 */
const props = defineProps<{ downloadUrl: string; prefetch?: ViewerPrefetch | undefined }>();

type DocState =
  | { status: "loading" }
  | { status: "error"; message: string; retry: boolean }
  | { status: "ready"; doc: PDFDocumentProxy };

const generation = ref(0);
// Shallow: the pdf.js document keeps private state a reactive proxy would break.
const state = shallowRef<DocState>({ status: "loading" });
const page = ref(1);
const zoom = ref(1);
const renderFailed = ref(false);
const canvas = useTemplateRef<HTMLCanvasElement>("canvas");

useEffectAfterRender([() => props.downloadUrl, generation, () => props.prefetch], () => {
  const controller = new AbortController();
  let alive = true;
  let task: PDFDocumentLoadingTask | null = null;
  state.value = { status: "loading" };
  page.value = 1;
  renderFailed.value = false;
  void (async () => {
    try {
      const body = await (props.prefetch?.take(controller.signal) ??
        downloadCapped(props.downloadUrl, PDF_MAX_BYTES, controller.signal));
      if (!alive) return;
      if (body.status === "failed") {
        state.value = { status: "error", message: t("load.failed"), retry: true };
        return;
      }
      if (body.status === "tooLarge") {
        state.value = { status: "error", message: t("attachment.viewer.previewUnavailable"), retry: false };
        return;
      }
      const pdfjs = await loadPdfJs();
      if (!alive) return;
      const assets = new URL(`${import.meta.env.BASE_URL}${pdfjsAssetBase(pdfjs.version)}`, window.location.href).href;
      task = pdfjs.getDocument({
        data: body.bytes,
        enableXfa: false,
        maxImageSize: PDF_MAX_IMAGE_PIXELS,
        cMapUrl: `${assets}cmaps/`,
        cMapPacked: true,
        standardFontDataUrl: `${assets}standard_fonts/`,
        wasmUrl: `${assets}wasm/`,
        iccUrl: `${assets}iccs/`,
      });
      const doc = await task.promise;
      if (alive) state.value = { status: "ready", doc };
    } catch (error) {
      if (!alive || (error instanceof Error && error.name === "AbortError")) return;
      state.value = { status: "error", message: t("load.failed"), retry: true };
    }
  })();
  return () => {
    alive = false;
    controller.abort();
    void task?.destroy();
  };
});

const doc = computed(() => (state.value.status === "ready" ? state.value.doc : null));

useEffectAfterRender([doc, page, zoom], () => {
  const target = canvas.value;
  const current = doc.value;
  if (!current || !target) return;
  let alive = true;
  let render: RenderTask | null = null;
  renderFailed.value = false;
  void (async () => {
    try {
      const pdfPage = await current.getPage(page.value);
      if (!alive) return;
      const base = pdfPage.getViewport({ scale: 1 });
      const scale = renderScale(base.width, base.height, zoom.value, window.devicePixelRatio);
      const viewport = pdfPage.getViewport({ scale });
      target.width = Math.floor(viewport.width);
      target.height = Math.floor(viewport.height);
      target.style.width = `${Math.floor(base.width * zoom.value)}px`;
      render = pdfPage.render({ canvas: target, viewport });
      await render.promise;
    } catch (error) {
      if (alive && !(error instanceof Error && error.name === "RenderingCancelledException")) {
        renderFailed.value = true;
      }
    }
  })();
  return () => {
    alive = false;
    render?.cancel();
  };
});

const pageCount = computed(() => doc.value?.numPages ?? 0);

function retry(): void {
  generation.value += 1;
}
</script>

<template>
  <ViewerLoadingPane v-if="state.status === 'loading'" />
  <ViewerErrorPane
    v-else-if="state.status === 'error'"
    :message="state.message"
    :download-url="downloadUrl"
    :retryable="state.retry"
    @retry="retry"
  />
  <ViewerErrorPane
    v-else-if="renderFailed"
    :message="t('load.failed')"
    :download-url="downloadUrl"
    retryable
    @retry="retry"
  />
  <div v-else class="attachment-viewer__pane" data-pdf-viewer="">
    <ViewerZoomToolbar
      :zoom="zoom"
      :can-zoom-out="zoom > PDF_ZOOM_MIN"
      :can-zoom-in="zoom < PDF_ZOOM_MAX"
      @zoom-in="zoom = zoomIn(zoom)"
      @zoom-out="zoom = zoomOut(zoom)"
      @reset="zoom = 1"
    >
      <UButton size="sm" variant="outline" color="neutral" :disabled="page <= 1" @click="page = Math.max(1, page - 1)">
        {{ t("attachment.viewer.prevPage") }}
      </UButton>
      <p class="attachment-viewer__page-label">
        {{ t("attachment.viewer.page", { current: page, total: pageCount }) }}
      </p>
      <UButton
        size="sm"
        variant="outline"
        color="neutral"
        :disabled="page >= pageCount"
        @click="page = Math.min(pageCount, page + 1)"
      >
        {{ t("attachment.viewer.nextPage") }}
      </UButton>
    </ViewerZoomToolbar>
    <div class="attachment-viewer__page-wrap">
      <canvas ref="canvas" class="attachment-viewer__pdf-canvas" :aria-label="t('attachment.viewer.pdf')" />
    </div>
  </div>
</template>
