// apps/web/src/vue/features/tasks/TaskParentSelect.vue
<script setup lang="ts">
import { t } from "@fvoci/i18n";
import UButton from "@nuxt/ui/components/Button.vue";
import { useInfiniteQuery } from "@tanstack/vue-query";
import { computed, ref, watch } from "vue";
import { taskParentListQuery } from "@/features/tasks/queries";

const props = withDefaults(
  defineProps<{
    workspaceId: string;
    projectId: string;
    childType: string;
    excludeTaskId: string;
    modelValue: string | null;
    currentTitle?: string;
    disabled?: boolean;
  }>(),
  { disabled: false },
);
const emit = defineEmits<{ "update:modelValue": [value: string | null] }>();

const open = ref(false);
const query = ref("");
const selected = ref<{ id: string; title: string } | null>(null);
const q = computed(() => query.value.trim());

const list = useInfiniteQuery(() => ({
  ...taskParentListQuery(
    props.workspaceId,
    props.projectId,
    props.childType,
    props.excludeTaskId,
    q.value,
  ),
  enabled:
    open.value &&
    Boolean(props.workspaceId) &&
    Boolean(props.projectId) &&
    props.childType !== "epic",
}));

watch(
  () => [props.childType, props.excludeTaskId] as const,
  () => {
    open.value = false;
    query.value = "";
    selected.value = null;
  },
);

const items = computed(() => list.data.value?.pages.flatMap((page) => page.items) ?? []);
const label = computed(() => {
  if (!props.modelValue) return t("task.parent.none");
  if (selected.value?.id === props.modelValue) return selected.value.title;
  return props.currentTitle ?? t("task.parent.current");
});
const listPending = computed(() => open.value && list.isPending.value);
const listError = computed(() => (open.value ? list.error.value : null));
const showEmpty = computed(() => items.value.length === 0 && !list.hasNextPage.value);
const triggerDisabled = computed(
  () => props.disabled || props.childType === "epic" || !props.workspaceId || !props.projectId,
);

function pick(id: string | null, title?: string): void {
  if (id && title) selected.value = { id, title };
  else selected.value = null;
  emit("update:modelValue", id);
  open.value = false;
}
</script>

<template>
  <div class="task-parent-select">
    <UButton
      id="task-edit-parent"
      type="button"
      size="sm"
      variant="outline"
      color="neutral"
      class="task-parent-select__trigger"
      data-testid="task-edit-parent"
      :aria-expanded="open"
      aria-haspopup="listbox"
      :disabled="triggerDisabled"
      @click="open = !open"
    >
      {{ label }}
    </UButton>
    <div v-if="open" class="task-parent-select__panel">
      <input
        v-model="query"
        class="task-form__field-input"
        :aria-label="t('task.parent.search')"
        :placeholder="t('task.parent.search')"
        data-testid="task-edit-parent-search"
        :disabled="disabled"
      />
      <p v-if="listPending" role="status" class="task-home__note">{{ t("task.parent.loading") }}</p>
      <div v-else-if="listError" role="alert">
        <p class="task-form__alert">{{ t("task.parent.failed") }}</p>
        <UButton size="sm" variant="outline" color="neutral" @click="list.refetch()">{{
          t("task.parent.retry")
        }}</UButton>
      </div>
      <ul
        v-else
        class="task-parent-select__list"
        role="listbox"
        :aria-label="t('task.parent.label')"
        :aria-busy="list.isFetching.value"
      >
        <li v-if="childType !== 'subtask'" role="presentation">
          <button
            type="button"
            role="option"
            class="task-parent-select__option"
            :aria-selected="modelValue == null"
            data-testid="task-edit-parent-none"
            @click="pick(null)"
          >
            {{ t("task.parent.none") }}
          </button>
        </li>
        <li v-for="item in items" :key="item.id" role="presentation">
          <button
            type="button"
            role="option"
            class="task-parent-select__option"
            :aria-selected="modelValue === item.id"
            :data-testid="`task-edit-parent-option-${item.id}`"
            @click="pick(item.id, `${item.displayId} ${item.title}`)"
          >
            {{ item.displayId }} {{ item.title }}
          </button>
        </li>
        <li v-if="showEmpty" role="presentation" class="task-home__note">{{
          t("task.parent.empty")
        }}</li>
      </ul>
      <UButton
        v-if="list.hasNextPage.value"
        size="sm"
        variant="outline"
        color="neutral"
        :disabled="list.isFetchingNextPage.value"
        @click="list.fetchNextPage()"
      >
        {{ t("task.parent.more") }}
      </UButton>
    </div>
  </div>
</template>

// apps/web/src/features/tasks/task-parent-select.tsx
import { t } from "@fvoci/i18n";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useDeferredValue, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { taskParentListQuery } from "./queries";

export function TaskParentSelect({
  workspaceId,
  projectId,
  childType,
  excludeTaskId,
  value,
  currentTitle,
  onChange,
  disabled,
}: {
  workspaceId: string;
  projectId: string;
  projectKey: string;
  childType: string;
  excludeTaskId: string;
  value: string | null;
  currentTitle?: string;
  onChange: (value: string | null) => void;
  disabled?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<{ id: string; title: string } | null>(null);
  const q = useDeferredValue(query).trim();

  const list = useInfiniteQuery({
    ...taskParentListQuery(workspaceId, projectId, childType, excludeTaskId, q),
    enabled: open && Boolean(workspaceId) && Boolean(projectId) && childType !== "epic",
  });

  useEffect(() => {
    setOpen(false);
    setQuery("");
    setSelected(null);
  }, [childType, excludeTaskId]);

  const items = useMemo(
    () => list.data?.pages.flatMap((page) => page.items) ?? [],
    [list.data],
  );

  const label = value
    ? selected?.id === value
      ? selected.title
      : (currentTitle ?? t("task.parent.current"))
    : t("task.parent.none");
  const listPending = open && list.isPending;
  const listError = open ? list.error : null;
  const showEmpty = items.length === 0 && !list.hasNextPage;

  return (
    <div className="task-parent-select">
      <Button
        type="button"
        variant="outline"
        className="task-parent-select__trigger"
        id="task-edit-parent"
        data-testid="task-edit-parent"
        aria-expanded={open}
        aria-haspopup="listbox"
        disabled={disabled || childType === "epic" || !workspaceId || !projectId}
        onClick={() => setOpen((current) => !current)}
      >
        {label}
      </Button>
      {open ? (
        <div className="task-parent-select__panel">
          <Input
            autoFocus
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            aria-label={t("task.parent.search")}
            placeholder={t("task.parent.search")}
            data-testid="task-edit-parent-search"
            disabled={disabled}
          />
          {listPending ? (
            <p role="status" className="task-home__note">
              {t("task.parent.loading")}
            </p>
          ) : listError ? (
            <div role="alert">
              <p className="task-form__alert">{t("task.parent.failed")}</p>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => {
                  void list.refetch();
                }}
              >
                {t("task.parent.retry")}
              </Button>
            </div>
          ) : (
            <ul
              className="task-parent-select__list"
              role="listbox"
              aria-label={t("task.parent.label")}
              aria-busy={list.isFetching}
            >
              {childType !== "subtask" ? (
                <li role="presentation">
                  <button
                    type="button"
                    role="option"
                    className="task-parent-select__option"
                    aria-selected={value == null}
                    data-testid="task-edit-parent-none"
                    onClick={() => {
                      onChange(null);
                      setSelected(null);
                      setOpen(false);
                    }}
                  >
                    {t("task.parent.none")}
                  </button>
                </li>
              ) : null}
              {items.map((item) => {
                const text = `${item.displayId} ${item.title}`;
                return (
                  <li key={item.id} role="presentation">
                    <button
                      type="button"
                      role="option"
                      className="task-parent-select__option"
                      aria-selected={value === item.id}
                      data-testid={`task-edit-parent-option-${item.id}`}
                      onClick={() => {
                        setSelected({ id: item.id, title: text });
                        onChange(item.id);
                        setOpen(false);
                      }}
                    >
                      {text}
                    </button>
                  </li>
                );
              })}
              {showEmpty ? (
                <li role="presentation" className="task-home__note">
                  {t("task.parent.empty")}
                </li>
              ) : null}
            </ul>
          )}
          {list.hasNextPage ? (
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={list.isFetchingNextPage}
              onClick={() => void list.fetchNextPage()}
            >
              {t("task.parent.more")}
            </Button>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
